apache/jena

- jena-arq/src/main/java/org/apache/jena/riot/RDFLanguages.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/LangNQuads.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/LangNTriples.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/LangRDFJSON.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/LangRDFXML.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/LangTriG.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/LangTurtle.java
Some of the javadocs linked to the wrong specifications of RDF languages. Updated to a common style.
RDFLanguages javadoc was mostly correct.
> Javadoc rdf lang links

- jena-osgi-test/pom.xml
- jena-osgi/pom.xml
From email thread [Jena OSGi pull request](http://mail-archives.apache.org/mod_mbox/jena-dev/201502.mbox/%3C54CE2655.20006%40apache.org%3E)
jsonld comments in pom, submodules under apache-jena-osgi, millioseconds, and only build jena-osgi-test on -Papache-release.
In addition a rat-plugin configuratoin in parent was modified as it didn't exclude all in target/
> Updates to jena-osgi according to email thread

- jena-osgi/pom.xml
As an explanation of <scope> in jena-osgi/pom.xml was requested, I added it there.
> Explanation about <scope>

- apache-jena-osgi/jena-osgi-test/pom.xml
- apache-jena-osgi/jena-osgi-test/src/test/java/org/apache/jena/osgi/test/JenaOSGITest.java
.. by setting system property
now the only noise is because of duplicate slf4j binding, as slf4j-log4j is inherited from Jena parent.
Also fixes the missing `LATEST` version for jena-osgi
> Quieter jena-osgi-test logging

- apache-jena-osgi/jena-osgi-test/pom.xml
Only compile+run jena-osgi-test in `mvn install` - ignore in `mvn test`.
Note that with #28 this will also work with `mvn verify`.
> Jena osgi integration test

- apache-jena-osgi/jena-osgi-test/pom.xml
- apache-jena-osgi/jena-osgi/pom.xml
- jena-parent/pom.xml
If using Maven 3.0.2, gets rid of error
org.apache.maven.plugins.enforcer.RequirePluginVersions
>> failed with message:
>> [ERROR] Cannot find lifecycle mapping for packaging: 'bundle'.
This was caused by multi-module build where the `<extensions>` from `maven-bundle-plugin` got loaded too late. Note that this bug was not present in newer and older Mavens  - probably bug [MNG-4973](https://jira.codehaus.org/browse/MNG-4973)
See email thread 
http://mail-archives.apache.org/mod_mbox/jena-dev/201502.mbox/%3CD1124C6A.45FC3%25rvesse%40dotnetrdf.org%3E
> Workaround Maven 3.0.2 bug for jena-osgi

- jena-fuseki2/jena-fuseki-core/src/main/webapp/js/app/qonsole-config.js
Fixes JENA-865 by explicitly requiring `owl` and `rdfs` prefixes.
Also SPARQL keywords now in consistent CAPS style.
> JENA-865: Include prefixes in example query

- jena-jdbc/jena-jdbc-driver-tdb/pom.xml
.. instead of /tmp or %TEMP%
Fixes JENA-897 (although it still needs > 35 GB of disk space on Windows)
> JENA-897 Override java.io.tmpdir to write to target/

- jena-text/src/main/java/org/apache/jena/query/text/DatasetGraphText.java
- jena-text/src/main/java/org/apache/jena/query/text/TextIndex.java
- jena-text/src/main/java/org/apache/jena/query/text/TextIndexLucene.java
- jena-text/src/main/java/org/apache/jena/query/text/TextIndexSolr.java
- jena-text/src/main/java/org/apache/jena/query/text/assembler/TextDatasetAssembler.java
- jena-text/src/test/java/org/apache/jena/query/text/assembler/TestTextDatasetAssembler.java
This change to jena-text allows TextDocumentProducers
to access the dataset they are monitoring, and to
create indexes where there is a single (Lucene) document
for a given subject and all its defined properties
rather than a separate document per triple that the
subject appears in.
This allows indexes to be used for conjunctive query
eg a request such as
city: Plymouth AND street: Station
See https://github.com/epimorphics/ppd-text-index for an
an example project that uses conjunctive queries and 
provides a bulk index creation utility.
The changes to jena-text are spread over six files as follows:
The two-phase commit protocol is modified to ensure that a
DatasetChanges monitor finishes() before the commit protocol
starts. It is possible for a DatasetChanges to have buffered-up
changes …
> jena-text updates for constructing documents suitable for conjunctive queries

- jena-text/src/test/java/org/apache/jena/query/text/assembler/TestTextDatasetAssembler.java
When a TextDatasetGraph commits, it finish()es the attached TextDocProducer. If that producer
has buffered state whose flushing may read/write the quads of the dataset, this must happen
before the two-phase commit protocol runs. Pull Request #42 arranged that this was true.
This Pull Request adds a test to TestTextDatasetAssembler which opens, writes, and commits
to a dataset with a TextDocProducer which does a quad add to the dataset, without the commit
failing.
(To see the failure this protects against, edit TextDatasetGraph's commit method to call the
monitor's finish() method at the end of the commit() rather than the beginning.) 
[Sorry, there's a bunch of tab/space layout noise in the diffs; it's much easier to track with ?w=1]
> Test that TextDocProducer with buffered state has opportunity to flush before dataset commits.

- apache-jena-osgi/jena-osgi-test/pom.xml
- apache-jena-osgi/jena-osgi/pom.xml
Re-enable the surefire-plugin for jena-osgi-tests - as the tests didn't actually run on the master.
It needs an explicit <execution> so that it runs in a later phase. I've added comments about this to the pom.
Now that the OSGi tests were running correctly, this highlighted a problem from #45 in that Guava has an optional import on `sun.misc` which prevented starting, so I added that as optional in our shading (as it is in the upstream Guava `META-INF/MANIFEST.MF`).
I also re-added the explicit `<extensions>true</extensions>` as those were added as a workaround for  Maven 3.0.2 (see #32).
> Re-enable jena-osgi-tests

- jena-maven-tools/demo/pom.xml
Fixes JENA-849 in updated `jena-maven-tools/demo`
.. tries to not list the version numbers explicitly as they would go out of date.
> JENA-849 maven tools demo versions

- jena-parent/pom.xml
This patch upgrades the code quality reporting plugins in use to versions that will work with Java 8, re-enabling `mvn site`.
> JENA-941: Upgrading code quality plugin versions

- jena-text/src/main/java/org/apache/jena/query/text/DatasetGraphText.java
- jena-text/src/main/java/org/apache/jena/query/text/Entity.java
- jena-text/src/main/java/org/apache/jena/query/text/TextHit.java
- jena-text/src/main/java/org/apache/jena/query/text/TextHitConverter.java
- jena-text/src/main/java/org/apache/jena/query/text/TextIndex.java
- jena-text/src/main/java/org/apache/jena/query/text/TextIndexConfig.java
- jena-text/src/main/java/org/apache/jena/query/text/TextIndexLucene.java
- jena-text/src/main/java/org/apache/jena/query/text/TextIndexSolr.java
- jena-text/src/main/java/org/apache/jena/query/text/TextQueryFuncs.java
- jena-text/src/main/java/org/apache/jena/query/text/TextQueryPF.java
- jena-text/src/main/java/org/apache/jena/query/text/assembler/TextIndexLuceneAssembler.java
- jena-text/src/main/java/org/apache/jena/query/text/assembler/TextVocab.java
- jena-text/src/test/java/org/apache/jena/query/text/TS_Text.java
- jena-text/src/test/java/org/apache/jena/query/text/TestDatasetWithLuceneStoredLiterals.java
This PR implements a feature where it's possible to store the original literal values in the jena-text Lucene index and to access them when querying the index. It works like this:
1) Configure jena-text to store literals (default is off) using the new `text:storeValues` setting. Note that you also need the `text:langField` setting in the entity map for language tags and datatypes to be handled correctly.
```
<#indexLucene> a text:TextIndexLucene ;
#text:directory <file:Lucene> ;
text:directory "mem" ;
text:storeValues true ;
text:entityMap <#entMap> ;
.
<#entMap> a text:EntityMap ;
text:entityField "uri" ;
text:langField "lang" ;
[...]
```
2) Add some data, say this triple:
```
:myresource rdfs:label "My resource"@en .
```
3) Query like this:
```
SELECT * {
(?s ?score ?literal) text:query …
```
> jena-text stored literals: initial functionality and tests for Lucene

- jena-arq/src/main/java/org/apache/jena/sparql/core/mem/PMapQuadTable.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/mem/PMapTripleTable.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/mem/QuadTableForm.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/mem/TripleTableForm.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/mem/TestDatasetGraphInMemory.java
Introduces new ordering methods `PMapTripleTable::triple` and `PMapQuadTable::quad` to provide correct ordering in the construction of tuples for query results.
> Fix for ordering problem in JENA-624

- jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetGraphCaching.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetGraphSimpleMem.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetGraphTriplesQuads.java
- jena-arq/src/test/java/org/apache/jena/sparql/modify/AbstractTestUpdateGraphMgt.java
- jena-sdb/src/main/java/org/apache/jena/sdb/store/DatasetGraphSDB.java
- jena-tdb/src/main/java/org/apache/jena/tdb/store/DatasetGraphTDB.java
JENA-1068: Remove use of DatasetGraphCaching.
Removed everywhere then the class put back, deprecated, just in case any external party is using it.
> J1068 remove dsg caching

- jena-text/src/main/java/org/apache/jena/query/text/analyzer/ConfigurableAnalyzer.java
- jena-text/src/main/java/org/apache/jena/query/text/assembler/ConfigurableAnalyzerAssembler.java
- jena-text/src/main/java/org/apache/jena/query/text/assembler/TextAssembler.java
- jena-text/src/main/java/org/apache/jena/query/text/assembler/TextVocab.java
- jena-text/src/test/java/org/apache/jena/query/text/TS_Text.java
- jena-text/src/test/java/org/apache/jena/query/text/TestDatasetWithConfigurableAnalyzer.java
- jena-text/src/test/java/org/apache/jena/query/text/assembler/TestEntityMapAssembler.java
This is a configurable Analyzer implementation for jena-text / Lucene. It is similar to what can be achieved in [Solr configuration](https://wiki.apache.org/solr/AnalyzersTokenizersTokenFilters). The current implementation only supports a few basic tokenizers and filters included in Lucene. More can be added later if necessary, though some tokenizers and filters require extra configuration parameters and currently there is no mechanism for specifying these.
Tokenizers:
* StandardTokenizer
* KeywordTokenizer
* WhitespaceTokenizer
* LetterTokenizer
Filters:
* StandardFilter
* LowerCaseFilter
* ASCIIFoldingFilter
Configuration can be done in the assembler like this:
```
text:analyzer [
a text:ConfigurableAnalyzer ;
text:tokenizer text:KeywordTokenizer ;
text:filters (text:ASCIIFoldingFilter, …
```
> JENA-1062: configurable Lucene analyzer for jena-text

- jena-arq/src/main/java/org/apache/jena/sparql/core/mem/DatasetGraphInMemory.java
Correction to transaction begin for DatasetGraphInMemory to include default graph as well as quad table.
> JENA-624: Correction to transaction begin for DatasetGraphInMemory

- jena-arq/src/main/java/org/apache/jena/sparql/core/mem/DatasetGraphInMemory.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/mem/TestDatasetGraphInMemoryThreading.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/mem/TestDatasetGraphInMemoryTransactions.java
(Cleaned version of PR #107)
This revision
* Puts the transaction finalization code inside the commit/abort code that takes the system lock. This mean the lock is taken once at the finishing of a transaction.
* Reorganises the code to a rigid pattern for operations.
* Renames commitLock as systemLock
* Uses ReentrantLock, not ReentrantReadWriteLock (only the write lock was used; the implement of a ReentrantReadWriteLock.WriteLock and ReentrantLock is much the same for our usage, just calls to the sync object).
As well as code review, design review would be appreciated. 
Compared to the original design, this makes abort take a lock and call abort on indexes whereas previously it simply did nothing, knowing the index implementations would cope. Because abort is a not a performance critical …
> JENA-1085: Common pattern for transaction lifecycle. Always call down to index operations.

- jena-arq/src/main/java/org/apache/jena/sparql/core/TransactionalComponent.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/TransactionalOfOne.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/mem/HexTable.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/mem/PMapTupleTable.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/mem/TriTable.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/mem/TupleTable.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/mem/AbstractTestTupleTable.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/mem/TestHexTable.java
Mantis has a more general concept of transaction.  As part of that, it differentiates between `Transactional` (the view from users of a transaction system) and `TransactionalComponent` (units of code that participate in providing transactionality).
See [the code for TransactionalComponent](https://github.com/afs/mantis/blob/master/dboe-transaction/src/main/java/org/seaborne/dboe/transaction/txn/TransactionalComponent.java) -- for example, that has a explicit `Transaction` object and only the upper layers manage the `Transaction` by thread.
For the in-memory dataset, the difference is currently small but introducing this now prepares for more complex setups, without disturbing `Transactional`.  It also removes the need for components to know whether they are in a transaction or not; that …
> Introduce interface TransactionalComponent.

- jena-core/src/main/java/org/apache/jena/rdf/model/ModelCon.java
- jena-core/src/main/java/org/apache/jena/rdf/model/impl/ModelCom.java
Proposal to fix JENA-1082 issue that further overloads ModelCon#listLiteralStatements() method. The only required implementation of such method follows the same idea behind of other listLiteralStatements() methods.
> Fixes JENA-1082.

- jena-core/src/main/java/org/apache/jena/datatypes/xsd/AbstractDateTime.java
- jena-core/src/main/java/org/apache/jena/datatypes/xsd/XSDDuration.java
- jena-core/src/test/java/org/apache/jena/datatypes/TestDatatypeValues.java
- jena-core/src/test/java/org/apache/jena/datatypes/TestPackage.java
This PR provides canonicalization of the date/time duration in comparison, equality and hashcode operations based on year-month and day-time parts. (e.g. if it is 110seconds, it become 1minute 50seconds).
Only year-month and day-time durations are fully comparable but applications may, indeed probably do, use the xsd:duration datatype, not the appropriate subtype.
This does not affect SPARQL.
> JENA-149: Duration equality by value.

- jena-core/src/main/java/org/apache/jena/assembler/Assembler.java
Attempting to capture @afs's comment [here](https://github.com/apache/jena/pull/123#issuecomment-174306928) as advice in the Javadocs.
> Add Javadoc for Assembler indicating that Model values are advisory

- jena-fuseki2/jena-fuseki-core/src/main/webapp/js/lib/qonsole.js
This issue is related to https://issues.apache.org/jira/browse/JENA-1123 and https://github.com/OpenTriply/YASGUI.YASR/issues/83. 
It solves the issue of query response values not properly getting escaped when the results are drawn in a YASR datatable
> fixed query response values not getting html-escaped

- jena-arq/src/main/java/org/apache/jena/riot/lang/LangEngine.java
- jena-arq/src/main/java/org/apache/jena/riot/system/FactoryRDF.java
- jena-arq/src/main/java/org/apache/jena/riot/system/FactoryRDFCaching.java
- jena-arq/src/main/java/org/apache/jena/riot/system/FactoryRDFStd.java
- jena-arq/src/main/java/org/apache/jena/riot/system/ParserProfile.java
- jena-arq/src/main/java/org/apache/jena/riot/system/ParserProfileBase.java
- jena-arq/src/main/java/org/apache/jena/riot/system/ParserProfileChecker.java
- jena-arq/src/main/java/org/apache/jena/riot/system/ProgressStreamRDF.java
- jena-arq/src/main/java/org/apache/jena/riot/system/RiotLib.java
- jena-arq/src/main/java/org/apache/jena/riot/system/SerializationFactoryFinder.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/binding/BindingInputStream.java
- jena-arq/src/test/java/org/apache/jena/riot/system/TS_RiotSystem.java
- jena-arq/src/test/java/org/apache/jena/riot/system/TestFactoryRDF.java
- jena-arq/src/test/java/org/apache/jena/riot/system/TestFactoryRDFCaching.java
- jena-base/src/main/java/org/apache/jena/atlas/lib/cache/CacheInfo.java
- jena-cmds/src/main/java/riotcmd/CmdLangParse.java
- jena-elephas/jena-elephas-io/src/main/java/org/apache/jena/hadoop/rdf/io/input/util/RdfIOUtils.java
FactoryRDF is an interface to abstract the creation of nodes, triples and quads from constituent elements, e.g. to create a URI Node, the operation takes a string for the URI. This allows different policies to be slotted in. This PR covers the use of FactoryRDF by ParserProfile.
> JENA-1147 : Introduce FactoryRDF 

- jena-arq/src/main/java/org/apache/jena/sparql/expr/nodevalue/XSDFuncOp.java
- jena-arq/src/main/java/org/apache/jena/sparql/function/library/sprintf.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/TestFunctions.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/TestFunctions2.java
Hi,
I implemented the afn:sprintf function. In order to implement it, I had to:
- create a sprintf.java class in the sparql function part.
- implement in the XSDFuncOp.java a function dealing with making sprintf
- create a series of tests checking that the function is working correctly.
While implementing, I realized that the example described in the bug is just one of the possibilities (printing numbers) as by the Java specification, String.Format works with all types. I thus implemented the function to work with all the type that made sense in my opinion (we can discuss about this).
There is still one problem that I am not sure how to solve:
Test 04 and 07 and 08 depend on the user locale (it will be printed as 1.2.. or 1,2.. or with date the day or month depend on the locale). In order …
> JENA-967: afn:Sprintf implementation

- apache-jena-osgi/jena-osgi-features/pom.xml
- apache-jena-osgi/jena-osgi-features/src/main/resources/features.xml
- apache-jena-osgi/jena-osgi-test/pom.xml
- apache-jena-osgi/jena-osgi-test/src/test/java/org/apache/jena/osgi/test/JenaOSGITest.java
- apache-jena-osgi/jena-osgi/pom.xml
- apache-jena-osgi/jena-osgi/src/main/java/org/apache/jena/osgi/Activator.java
- apache-jena-osgi/pom.xml
- jena-core/src/main/java/org/apache/jena/system/JenaSubsystemRegistryBasic.java
This is a suggestion to fix errors in static initialization of Jena 3 in OSGi environments folowing the OSGi ServiceLoader Mediator spec. The appropriate manifest headers and a bundle activator were added: 
http://mail-archives.apache.org/mod_mbox/jena-users/201603.mbox/%3C2804-56ee5500-b-5266a380%40181641092%3E
The original integration test (jena-osgi-test) was ineffective. Missing a runtime configuration the test methods did not run/never failed on my side. It works for Apache Karaf now. 
Please install the uploaded, OSGi-fied dependency com.github.andrewoma.dexx:collection: 
mvn install:install-file -Dfile=collection-0.4.0.jar -DgroupId=com.github.andrewoma.dexx -DartifactId=collection -Dversion=0.4.0 -Dpackaging=jar
and run the integration test: mvn -Drat.ignoreErrors=true clean …
> Fix Jena initialization in OSGi environments

- jena-arq/src/main/java/org/apache/jena/query/ARQ.java
- jena-arq/src/main/java/org/apache/jena/riot/system/ParserProfileBase.java
- jena-arq/src/main/java/org/apache/jena/riot/system/ParserProfileChecker.java
- jena-arq/src/main/java/org/apache/jena/riot/system/RiotLib.java
- jena-arq/src/main/java/org/apache/jena/sparql/lang/ParserBase.java
- jena-cmds/src/main/java/arq/cmdline/ModContext.java
- jena-cmds/src/main/java/arq/qparse.java
- jena-cmds/src/main/java/jena/qparse.java
- jena-cmds/src/main/java/jena/riot.java
- jena-cmds/src/main/java/jena/sparql.java
JENA-1165 : Support for handlign undefined prefixes, especially in command line tools.
The default setting everywhere is "off".
> Unset prefixes

- jena-text/src/main/java/org/apache/jena/query/text/TextQueryPF.java
- jena-text/src/test/java/org/apache/jena/query/text/TestTextTDB.java
It seems that jena-text used to support blank nodes in the text index (there is some infrastructure to support this, particularly in TextQueryFuncs) but this was broken by JENA-999 (internal caching) or possibly even earlier. There were no unit tests involving blank nodes that would have caught this.
This PR restores support for blank node subjects. There are a couple of very basic unit tests that check the basic functionality.
> JENA-1172: restore support for blank nodes in jena-text

- apache-jena-osgi/jena-osgi/pom.xml
See also https://github.com/apache/jena/pull/134#issuecomment-209474708 of why this should be optional.
> Optional xerces bundle dependency

- jena-elephas/jena-elephas-mapreduce/src/test/java/org/apache/jena/hadoop/rdf/mapreduce/characteristics/CharacteristicSetReducerTest.java
- jena-elephas/pom.xml
- jena-parent/pom.xml
There are two commits in this PR. The first, I think, should be entirely straightforward. The second contains a minor version bump for `mrunit`. In order to do this, I updated `CharacteristicSetReducerTest` to meet what seems to be a slight change in the semantics for `mrunit`'s `TestDriver` type at this new version (it cannot be "reused" by calling `runTest()` and then `run()`, you have to use a new test driver). I believe I did this correctly, but it should be examined extra-carefully.
> Version bumps

- jena-maven-tools/src/main/java/org/apache/jena/tools/schemagen/SchemagenMojo.java
After converting the String to an absolute path it can still contain backslashes, possibly resulting in compilation errors in the generated code. For example if one of the folder starts with "u" the path contains "\uXXXXX" which is usually not a valid Unicode escape and thus compilation fails.
> Fix the complete Windows path, not just the filename

- jena-arq/src/main/java/org/apache/jena/sparql/core/assembler/AssemblerUtils.java
- jena-cmds/pom.xml
- jena-tdb/src/main/java/org/apache/jena/tdb/assembler/VocabTDB.java
- jena-tdb/testing/Assembler/tdb-dataset-embed.ttl
- jena-tdb/testing/Assembler/tdb-dataset.ttl
- jena-tdb/testing/Assembler/tdb-graph-embed.ttl
- jena-tdb/testing/Assembler/tdb-graph-ref-dataset.ttl
- jena-tdb/testing/Assembler/tdb-graph.ttl
- jena-tdb/testing/Assembler/tdb-named-graph-1.ttl
- jena-tdb/testing/Assembler/tdb-named-graph-2.ttl
- jena-text/src/main/java/org/apache/jena/query/text/TextIndexLucene.java
- jena-text/src/test/java/org/apache/jena/query/text/AbstractTestDatasetWithAnalyzer.java
- jena-text/src/test/java/org/apache/jena/query/text/TS_Text.java
- jena-text/src/test/java/org/apache/jena/query/text/TestDatasetWithComplexPhraseQueryParser.java
- jena-text/src/test/java/org/apache/jena/query/text/TestDatasetWithKeywordAnalyzer.java
This PR expands on JENA-1134, which added support for new query parsers in jean-text. ComplexQueryParser is useful for performing wildcard or fuzzy search on terms in phrases.
I’ve attempted to follow the pattern for adding a query parser as in JENA-1134, but I may have duplicated some functionality in the unit test, when I should have restructured instead.
The test needs to specify the TTL spec analyzer and parser, which is available in TestDatasetWithConfigurableAnalyzer’s method makeSpec. However, TestDatasetWithConfigurableAnalyzer inherits from TestDatasetWithKeywordAnalyzer, which isn’t the analyzer the ComplexPhraseQuery needs to test.
> JENA-1180: Add support for ComplexPhraseQueryParser to jena-text

- jena-arq/src/main/java/org/apache/jena/sparql/expr/nodevalue/XSDFuncOp.java
- jena-arq/src/main/java/org/apache/jena/sparql/function/StandardFunctions.java
- jena-arq/src/main/java/org/apache/jena/sparql/function/library/FN_AdjustDatetimeToTimezone.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/TestFunctions.java
I implemented two new XPath 3 functions: fn:adjust-datetime-to-timezone, fn:adjust-date-to-timezone and fn:adjust-time-to-timezone. I used the examples of the specification for the tests + I decided to implement both using the same underlying function as it seems to me that in jena there is no distinction between date and datetime (date and datetime are using the same object and from the time we can also get the same object).
> JENA-508: implemented fn:adjust-datetime-to-timezone, fn:adjust-date-to-timezone and fn:adjust-time-to-timezone

- jena-core/pom.xml
- jena-core/src/main/java/org/apache/jena/reasoner/rulesys/impl/LPBRuleEngine.java
- jena-core/src/test/java/org/apache/jena/reasoner/rulesys/impl/TestLPBRuleEngine.java
- jena-core/src/test/java/org/apache/jena/reasoner/rulesys/test/TestPackage.java
This patch builds on the discussion pull request #45 - so if #45 goes through, this is how to use Guava within Jena - importing `org.apache.jena.ext.com.google.common.cache.Cache`.
The considerations of #45 apply here - so because `jena-core` gets a new dependency `jena-shadowed-ext` - even though that is our own brand new JAR - that should not go out as a patch-level upgrade, but forces a new minor version on pretty much everything jena-core and downstream. (We've been told of for adding dependencies in a patch before)
See also a second pull request #48 .
> JENA-901 LPDRuleEngine cache Guava from jena-shadowed-ext

- jena-arq/src/main/java/org/apache/jena/sparql/expr/nodevalue/XSDFuncOp.java
- jena-arq/src/main/java/org/apache/jena/sparql/function/StandardFunctions.java
- jena-arq/src/main/java/org/apache/jena/sparql/function/library/FN_FormatNumber.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/TestFunctions.java
Implementation and tests for `fn:format-number`.
For the "decimal-format-name	" third argument.  F&O says it is something defined in the static context but does not provide any more guidance.
> JENA-508:  fn:format-number

- jena-core/src/main/java/org/apache/jena/reasoner/rulesys/Builtin.java
- jena-core/src/main/java/org/apache/jena/reasoner/rulesys/BuiltinRegistry.java
- jena-core/src/main/java/org/apache/jena/reasoner/rulesys/FBRuleReasoner.java
- jena-core/src/main/java/org/apache/jena/reasoner/rulesys/Functor.java
- jena-core/src/main/java/org/apache/jena/reasoner/rulesys/MapBuiltinRegistry.java
- jena-core/src/main/java/org/apache/jena/reasoner/rulesys/OverrideBuiltinRegistry.java
- jena-core/src/main/java/org/apache/jena/reasoner/rulesys/Rule.java
- jena-core/src/main/java/org/apache/jena/reasoner/rulesys/impl/BindingStack.java
- jena-core/src/main/java/org/apache/jena/reasoner/rulesys/impl/BindingVector.java
- jena-core/src/test/java/org/apache/jena/reasoner/rulesys/test/TestBugs.java
- jena-core/src/test/java/org/apache/jena/reasoner/rulesys/test/TestGenericRuleReasonerConfig.java
This patch introduces support for multiple BuiltinRegistry classes implemented in a simple way which is parallel to the existing architecture.  (i.e. the BuiltinRegistry is a property of the Rules Engine parser,  not the Reasoner)
> [JENA-1204] support for multiple BuiltinRegistry for different rule sets

- jena-arq/src/main/java/org/apache/jena/atlas/json/JsonObject.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/mgt/ActionStats.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/server/DataAccessPointRegistry.java
- jena-fuseki2/jena-fuseki-core/src/test/java/org/apache/jena/fuseki/TS_Fuseki.java
- jena-fuseki2/jena-fuseki-embedded/pom.xml
- jena-fuseki2/jena-fuseki-embedded/src/main/java/org/apache/jena/fuseki/embedded/FusekiEmbeddedServer.java
- jena-fuseki2/jena-fuseki-embedded/src/test/java/org/apache/jena/fuseki/embedded/TS_EmbeddedFuseki.java
- jena-fuseki2/jena-fuseki-embedded/src/test/java/org/apache/jena/fuseki/embedded/TestEmbeddedFuseki.java
- jena-fuseki2/jena-fuseki-embedded/testing/FusekiEmbedded/config.ttl
- jena-fuseki2/pom.xml
This add a new module under jena-fuseki2 for running Fuseki embedded.
It is a new module so it can have it's own POM. The POM excludes all unecessary dependencies from jena-fuseki-core including logging provider, and modules jena-text and jena-spatial.
> JENA-1221: Embedded Fuseki server

- jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetGraphTrackActive.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetGraphWrapper.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetImpl.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/TransactionalLock.java
- jena-arq/src/test/java/org/apache/jena/sparql/api/TestAPI.java
- jena-arq/src/test/java/org/apache/jena/sparql/modify/TestUpdateOperations.java
- jena-cmds/src/main/java/tdb/cmdline/CmdTDBGraph.java
- jena-cmds/src/main/java/tdb/tdbloader.java
- jena-spatial/src/main/java/org/apache/jena/query/spatial/DatasetGraphSpatial.java
- jena-tdb/src/main/java/org/apache/jena/tdb/TDBLoader.java
- jena-tdb/src/main/java/org/apache/jena/tdb/solver/OpExecutorTDB1.java
- jena-tdb/src/main/java/org/apache/jena/tdb/store/DatasetGraphTDB.java
- jena-tdb/src/main/java/org/apache/jena/tdb/store/GraphNonTxnTDB.java
- jena-tdb/src/main/java/org/apache/jena/tdb/store/GraphTDB.java
- jena-tdb/src/main/java/org/apache/jena/tdb/store/GraphTxnTDB.java
- jena-tdb/src/main/java/org/apache/jena/tdb/transaction/DatasetGraphTransaction.java
- jena-tdb/src/main/java/org/apache/jena/tdb/transaction/DatasetGraphTxn.java
- jena-tdb/src/main/java/org/apache/jena/tdb/transaction/Transaction.java
- jena-tdb/src/main/java/org/apache/jena/tdb/transaction/TransactionManager.java
- jena-tdb/src/test/java/org/apache/jena/tdb/assembler/TestTDBAssembler.java
- jena-tdb/src/test/java/org/apache/jena/tdb/store/TestLoader.java
- jena-tdb/src/test/java/org/apache/jena/tdb/transaction/AbstractTestNodeTableTrans.java
- jena-tdb/src/test/java/org/apache/jena/tdb/transaction/AbstractTestObjectFileTrans.java
- jena-tdb/src/test/java/org/apache/jena/tdb/transaction/TS_TransactionTDB.java
- jena-tdb/src/test/java/org/apache/jena/tdb/transaction/TestTransPromote.java
- jena-tdb/src/test/java/org/apache/jena/tdb/transaction/TestTransactionTDB.java
- jena-text/src/main/java/org/apache/jena/query/text/DatasetGraphText.java
This PR is for discussion and is not yet ready for merging.
It adds to TDB the ability for a read transaction to promote to a write transaction.
Currently (to avoid general API changes outside TDB) this happens automatically in `DatasetGraphTransaction.getW()`.
It needs to be enabled with `DatasetGraphTransaction.promotion = true`
If this is useful, we can add new modes to `ReadWrite` and/or add `begin()` (no args).
There is a big design point: at the point at which a transaction becomes a writer their are two choices as to what to do if another write transaction happened between this one starting and this one promoting.
1. The transaction can now see changes made by the other writer. A limited form of "read committed" behaviour. Downside: results from actions during the read phase may be …
> Plain begin - read transactions promoting to write transactions.

- jena-arq/src/main/java/org/apache/jena/sparql/core/mem/DatasetGraphInMemory.java
JENA-1225: Remove prefix map when graph is deleted in TIM
> JENA-1225: Remove prefix map when graph is deleted in TIM

- jena-tdb/src/main/java/org/apache/jena/tdb/transaction/Transaction.java
- jena-tdb/src/main/java/org/apache/jena/tdb/transaction/TransactionManager.java
- jena-tdb/src/test/java/org/apache/jena/tdb/transaction/TS_TransactionTDB.java
- jena-tdb/src/test/java/org/apache/jena/tdb/transaction/TestTransControl.java
This adds additional control over the queue in the journal.
If the journal gets large, as measured by the journal file size in bytes (JENA-1222) then try to flush the journal.
If the journal becomes excessive long in terms of pending commits (JENA-1224) then after a writer, flip to exclusive mode, flush the journal and flip back to normal mode.
> JENA-1222 and JENA-1224: Flush queue when large by byte size or by pending commits.

- jena-arq/src/main/java/org/apache/jena/sparql/algebra/optimize/TransformFilterPlacement.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/ExprList.java
- jena-arq/src/test/java/org/apache/jena/sparql/algebra/optimize/TestOptimizer.java
- jena-arq/src/test/java/org/apache/jena/sparql/algebra/optimize/TestTransformFilterPlacement.java
This provides filter placement for OpDisjunction (a generalization of OpUnion generated internally e.g. for expanding `||` in filters).
> JENA-1235: Filter placement and OpDisjunction

- jena-arq/src/main/java/org/apache/jena/sparql/core/mem/DatasetGraphInMemory.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/mem/PMapTupleTable.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/mem/TS_DatasetTxnMem.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/mem/TestDatasetGraphInMemoryIsolation.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/mem/TestDatasetGraphInMemoryPromote.java
- jena-arq/src/test/java/org/apache/jena/sparql/transaction/AbstractTestTransPromote.java
- jena-arq/src/test/java/org/apache/jena/sparql/transaction/AbstractTestTransactionIsolation.java
- jena-arq/src/test/java/org/apache/jena/sparql/transaction/AbstractTestTransactionLifecycle.java
- jena-tdb/src/main/java/org/apache/jena/tdb/store/nodetable/NodeTableReadonly.java
- jena-tdb/src/main/java/org/apache/jena/tdb/store/nodetable/NodeTableWrapper.java
- jena-tdb/src/main/java/org/apache/jena/tdb/transaction/TransactionManager.java
- jena-tdb/src/test/java/org/apache/jena/tdb/transaction/TS_TransactionTDB.java
- jena-tdb/src/test/java/org/apache/jena/tdb/transaction/TestTransIsolation.java
- jena-tdb/src/test/java/org/apache/jena/tdb/transaction/TestTransPromote.java
- jena-tdb/src/test/java/org/apache/jena/tdb/transaction/TestTransPromoteTDB.java
Machinery for transaction promotion for the in-memory transactional dataset.
> JENA-1223: Txn promotion for TIM (includes patch for JENA-1237)

- jena-core/src/main/java/org/apache/jena/reasoner/rulesys/impl/ConsumerChoicePointFrame.java
- jena-core/src/test/java/org/apache/jena/reasoner/rulesys/impl/TestLPBRuleEngine.java
Each time a `LPRuleEngine` gets called to find a triple for which a cached `Generator` exists in `tabledGoals` a new `ConsumerChoicePointFrame` is registered as a consumer of this Generator.
The leak is that it is never unregistered from the consumer, the solution was simply to call the unregistering from the `close()` method of the `ConsumerChoicePointFrame`
> Solving a memory leak from LPRuleEngine

- jena-arq/src/main/java/org/apache/jena/atlas/data/AbstractDataBag.java
- jena-arq/src/main/java/org/apache/jena/atlas/data/DataBag.java
- jena-arq/src/main/java/org/apache/jena/atlas/test/Gen.java
- jena-arq/src/main/java/org/apache/jena/riot/writer/JsonLDWriter.java
- jena-arq/src/test/java/org/apache/jena/atlas/data/TestDistinctDataNet.java
- jena-arq/src/test/java/org/apache/jena/riot/system/TestJsonLDReadWrite.java
Just a couple of orthogonal commits that use library code in `Collections`, switch to using `default` methods where it seems appropriate, remove assignments with no effect, that sort of thing. If no one has any objection within a couple of days, I'll merge it myself.
> Using library code in a few classes

- jena-core/src/main/java/org/apache/jena/n3/N3JenaWriterCommon.java
I made a small change to the N3JenaWriterCommon writePrefixes function so that it does not need to make a call from the hashmap.
> Small optimization for writePrefixes()

- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/jetty/JettyFuseki.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/server/DataAccessPointRegistry.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/server/FusekiServerListener.java
- jena-fuseki2/jena-fuseki-core/src/test/java/org/apache/jena/fuseki/ServerCtl.java
- jena-fuseki2/jena-fuseki-embedded/src/main/java/org/apache/jena/fuseki/embedded/FusekiEmbeddedServer.java
- jena-fuseki2/jena-fuseki-embedded/src/test/java/org/apache/jena/fuseki/embedded/FusekiTestServer.java
- jena-fuseki2/jena-fuseki-embedded/src/test/java/org/apache/jena/fuseki/embedded/TS_EmbeddedFuseki.java
- jena-fuseki2/jena-fuseki-embedded/src/test/java/org/apache/jena/fuseki/embedded/TestEmbeddedFuseki.java
- jena-fuseki2/jena-fuseki-embedded/src/test/java/org/apache/jena/fuseki/embedded/TestMultipleEmbedded.java
Also includes the test server control code ported from jena-fuseki-core.
> JENA-1248: Fuseki registry update

- apache-jena/bin/tdbloader2
- apache-jena/bin/tdbloader2index
Allow env variable SORT_ARGS to be used for multiflag sort args
Do not override parallel flag if it is set on CLI in --sort-args or in env SORT_ARGS
> SORT_ARGS behavior

- jena-arq/src/main/java/org/apache/jena/query/ParameterizedSparqlString.java
- jena-arq/src/main/java/org/apache/jena/sparql/graph/GraphPrefixesProjection.java
- jena-arq/src/main/java/org/apache/jena/sparql/util/PrefixMapping2.java
- jena-core/src/main/java/org/apache/jena/graph/compose/PolyadicPrefixMappingImpl.java
- jena-core/src/main/java/org/apache/jena/rdf/model/ModelFactory.java
- jena-core/src/main/java/org/apache/jena/rdf/model/impl/ModelCom.java
- jena-core/src/main/java/org/apache/jena/shared/PrefixMapping.java
- jena-core/src/main/java/org/apache/jena/shared/impl/PrefixMappingImpl.java
- jena-core/src/test/java/org/apache/jena/rdf/model/test/TestModelFactory.java
- jena-core/src/test/java/org/apache/jena/rdf/model/test/TestModelPrefixMapping.java
- jena-core/src/test/java/org/apache/jena/shared/AbstractTestPrefixMapping.java
- jena-permissions/src/main/java/org/apache/jena/permissions/graph/impl/SecuredPrefixMappingImpl.java
- jena-permissions/src/main/java/org/apache/jena/permissions/impl/SecuredItemImpl.java
- jena-permissions/src/main/java/org/apache/jena/permissions/model/impl/SecuredModelImpl.java
- jena-permissions/src/test/java/org/apache/jena/permissions/MockPrefixMapping.java
- jena-permissions/src/test/java/org/apache/jena/permissions/model/SecuredModelDetailTest.java
- jena-permissions/src/test/java/org/apache/jena/permissions/query/DataSetTest.java
- jena-permissions/src/test/java/org/apache/jena/permissions/query/QueryEngineTest.java
- jena-tdb/src/main/java/org/apache/jena/tdb/store/DatasetPrefixesTDB.java
This PR contains:
1. Change to ModelCom to not touch prefixes if the inclusion is empty
1. Deprecates default prefixes (ModelCom, ModelFactory)
1. Add `PrefixMapping.noMappings()` and `PrefixMapping.numPrefixes()`
In addition it has some changes to make initialization more robust.
> JENA1249:  Default prefixes

- jena-arq/src/main/java/org/apache/jena/riot/lang/LangNTriples.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/LangNTuple.java
- jena-arq/src/main/java/org/apache/jena/riot/system/ParserProfileChecker.java
- jena-arq/src/main/java/org/apache/jena/riot/tokens/TokenizerText.java
Puts in place the structure for warnings not being tokenizer errors.
This is not enabled - it needs testing to see what knock-on effects it has. Ideally, it should be combined with parsers that can do some level of error recovery.
https://issues.apache.org/jira/browse/JENA-1252
> JENA-1252: Tokenizer cleaup

- jena-arq/src/main/java/org/apache/jena/riot/system/InitRIOT.java
- jena-arq/src/main/java/org/apache/jena/riot/system/SNode.java
- jena-arq/src/main/java/org/apache/jena/riot/system/SQuad.java
- jena-arq/src/main/java/org/apache/jena/riot/system/STriple.java
- jena-arq/src/main/java/org/apache/jena/riot/system/Serializer.java
- jena-arq/src/main/java/org/apache/jena/riot/system/SerializerRDF.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/Quad.java
- jena-arq/src/test/java/org/apache/jena/riot/system/TS_RiotSystem.java
- jena-arq/src/test/java/org/apache/jena/riot/system/TestSerializable.java
- jena-core/src/main/java/org/apache/jena/graph/Node.java
- jena-core/src/main/java/org/apache/jena/graph/Triple.java
- jena-core/src/main/java/org/apache/jena/system/Serializer.java
Note: this works if and only if both jena-core and jena-arq are used.
> JENA-1233: Serializable for Node/Triple/Quad.

- jena-cmds/src/main/java/riotcmd/CmdLangParse.java
A pull request with a simple approach for JENA-1197. When validate is checked, errors parsing a file will also be reported back, through a `CmdException`.
Quite hard to write a unit test for this, so did some simple regression test locally.
```
kinow@localhost:~/Development/java/jena/jena/apache-jena/bin$ JENA_HOME=/home/kinow/Desktop/JENA/apache-jena-3.1.1 ./riot --validate /tmp/invalid.ttl ; echo $?
23:34:46 ERROR riot                 :: [line: 1, col: 1 ] Out of place: [KEYWORD:I]
0
kinow@localhost:~/Development/java/jena/jena/apache-jena/bin$ JENA_HOME=../target/apache-jena-3.1.2-SNAPSHOT ./riot --validate /tmp/invalid.ttl ; echo $?
23:34:55 ERROR riot                 :: [line: 1, col: 1 ] Out of place: [KEYWORD:I]
1
kinow@localhost:~/Development/java/jena/jena/apache-jena/bin$ …
```
> JENA-1197 return exit code 1 when there is a problem validating a file with riot

- jena-cmds/src/main/java/riotcmd/CmdLangParse.java
See discussion on PR #188.
This PR incorporates #188 and returns a record describing the outcome of each call of the parser.  The records are retained, then the command can decide how to return/exit based on all parser attempts.
> JENA-1197: Record parse run outcomes

- jena-spatial/src/main/java/org/apache/jena/query/spatial/SpatialIndexLucene.java
This PR proposes removing the `distSort` parameter from the Lucene spatial query performed by jena-spatial. Dropping the sorting gives a massive performance boost; in the Geonames example given in JENA-1277, the query time drops from over 20 seconds to less than 200 ms.
I suppose that the sorting is not necessary since jena-spatial results are just raw material for the SPARQL engine anyway.
> JENA-1277: don't use sorting in spatial queries, for much better performance

- jena-arq/src/main/java/org/apache/jena/riot/writer/JsonLDWriter.java
small refactoring of JsonLDWriter to expose a static method that allows to convert jena RDF data to JsonLD-java API's object.
This can be useful, because you can then modify this object (generally a Map or a List representing the jsonld) the way you want (for instance, to reorder the items it contains to put more important ones at the beginning, or to make it look more "jsonish".)
(Note that this code could be moved to the JenaRDF2JSONLD class. I didn't move it, because this class is not public. But that would probably be a better place for this code)
> JsonLDWriter.toJsonLDJavaAPI: create a JsonLD API object from jena data

- jena-arq/src/main/java/org/apache/jena/query/ResultSetFactory.java
- jena-arq/src/main/java/org/apache/jena/query/SortCondition.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIterCommonParent.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIterRepeatApply.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIteratorBase.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/main/StageGeneratorGeneric.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/optimizer/reorder/ReorderProcIndexes.java
- jena-arq/src/main/java/org/apache/jena/sparql/lang/ParserARQUpdate.java
- jena-arq/src/main/java/org/apache/jena/sparql/lang/ParserSPARQL11Update.java
- jena-arq/src/main/java/org/apache/jena/sparql/lib/Metadata.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementService.java
- jena-base/src/main/java/org/apache/jena/atlas/io/IndentedWriter.java
- jena-base/src/main/java/org/apache/jena/atlas/logging/Log.java
- jena-core/src/main/java/org/apache/jena/rdf/model/impl/RDFReaderFImpl.java
- jena-core/src/main/java/org/apache/jena/rdf/model/impl/RDFWriterFImpl.java
- jena-tdb/src/main/java/org/apache/jena/tdb/base/objectfile/ObjectFileStorage.java
- jena-tdb/src/main/java/org/apache/jena/tdb/base/page/PageBase.java
- jena-tdb/src/main/java/org/apache/jena/tdb/base/recordbuffer/RecordRangeIterator.java
- jena-tdb/src/main/java/org/apache/jena/tdb/index/bplustree/BPlusTreeParams.java
- jena-tdb/src/main/java/org/apache/jena/tdb/lib/NodeLib.java
- jena-tdb/src/main/java/org/apache/jena/tdb/solver/BindingTDB.java
- jena-tdb/src/main/java/org/apache/jena/tdb/store/nodetable/NodecLib.java
- jena-tdb/src/main/java/org/apache/jena/tdb/sys/FileRef.java
- jena-tdb/src/main/java/org/apache/jena/tdb/sys/SystemTDB.java
- jena-tdb/src/main/java/org/apache/jena/tdb/transaction/BlockMgrJournal.java
- jena-tdb/src/main/java/org/apache/jena/tdb/transaction/JournalEntryType.java
- jena-tdb/src/main/java/org/apache/jena/tdb/transaction/TransactionManager.java
This PR renames the helper `Log` operations from `fatal` to `error` as being the more usual naming these days.
It also contains adding a clone operation to `IndentedWriter` which makes it much easier necessary to create an `IndentedWriter` for stdout/stderr by cloning the standard ones. The clone can be used to indent etc without affecting the system provided ones.
(both these come from working with some complex multiline logging needs mixing 
the usual one line logging and multiline datastructures)
> Logging fatal to error

- jena-arq/src/main/java/org/apache/jena/atlas/json/io/parser/JSONP.java
- jena-arq/src/main/java/org/apache/jena/atlas/json/io/parser/JSONParserBase.java
- jena-arq/src/main/java/org/apache/jena/atlas/json/io/parser/TokenizerJSON.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/LangNTuple.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/LangRDFJSON.java
- jena-arq/src/main/java/org/apache/jena/riot/system/ParserProfileBase.java
- jena-arq/src/main/java/org/apache/jena/riot/tokens/StringType.java
- jena-arq/src/main/java/org/apache/jena/riot/tokens/Token.java
- jena-arq/src/main/java/org/apache/jena/riot/tokens/TokenType.java
- jena-arq/src/main/java/org/apache/jena/riot/tokens/TokenizerText.java
- jena-arq/src/main/java/org/apache/jena/sparql/resultset/JSONInputIterator.java
- jena-arq/src/test/java/org/apache/jena/riot/tokens/TestTokenizer.java
- jena-core/src/main/java/org/apache/jena/graph/GraphUtil.java
- jena-core/src/test/java/org/apache/jena/graph/test/AbstractTestGraph.java
Having 4 separate string token types means that all four cases have to be considered, yet the more common case is that a string has been seen. Only sometimes does the exact form of the string matter.
This PR changes Jena to have one token type for STRING and separately record the string type seen for when it is needed.
> JENA-1285: One token type for strings

- jena-arq/src/main/java/org/apache/jena/query/ARQ.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/assembler/AssemblerUtils.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/optimizer/reorder/ReorderFixed.java
- jena-arq/src/main/java/org/apache/jena/sparql/pfunction/StandardPropertyFunctions.java
- jena-core/src/main/java/org/apache/jena/assembler/assemblers/AssemblerGroup.java
- jena-core/src/main/java/org/apache/jena/assembler/assemblers/OntModelAssembler.java
- jena-core/src/main/java/org/apache/jena/assembler/assemblers/OntModelSpecAssembler.java
- jena-core/src/main/java/org/apache/jena/vocabulary/OWL.java
- jena-core/src/main/java/org/apache/jena/vocabulary/RDF.java
- jena-core/src/main/java/org/apache/jena/vocabulary/RDFS.java
- jena-core/src/test/java/org/apache/jena/test/RDFSJenaInitTestApp.java
- jena-core/src/test/java/org/apache/jena/test/TestSystemSetup.java
- jena-tdb/src/test/java/org/apache/jena/tdb/sys/TS_Sys.java
Fixes for RDFS - use functions for constants during initialization.
This fixes initialization as reported (TestParameterizedSparqlString).
RDF and OWL still to do in the same style for some rather unusual ways to trigger the same effect.
> JENA-1294: Don't use contants during initialization.

- jena-text/src/main/java/org/apache/jena/query/text/DatasetGraphText.java
- jena-text/src/main/java/org/apache/jena/query/text/TextIndex.java
- jena-text/src/main/java/org/apache/jena/query/text/TextIndexLucene.java
- jena-text/src/main/java/org/apache/jena/query/text/TextQueryPF.java
In the development of JENA-1305 (Elasticsearch backend for jena-text) it surfaced that the current division of labor between TextQueryPF and TextIndex is awkward. The Lucene (or Solr) query string is mostly formed already on the TextQueryPF side, which makes it difficult to implement a backend that uses a different query language.
I have refactored the TextIndex interface, separating out the graph and language information away from the query string into separate method parameters, and changed the code in TextQueryPF and TextIndexLucene correspondingly.
I'm opening this PR to ask for comments on the change. If there is no opposition, I will merge it to master within a few days.
> Refactor TextIndex and TextQueryPF in jena-text (preparation for JENA-1305)

- jena-arq/src/main/java/org/apache/jena/riot/RDFDataMgr.java
- jena-arq/src/main/java/org/apache/jena/riot/RDFParser.java
- jena-arq/src/main/java/org/apache/jena/riot/RDFParserBuilder.java
- jena-arq/src/main/java/org/apache/jena/riot/RDFParserRegistry.java
- jena-arq/src/main/java/org/apache/jena/riot/ReaderRIOTFactory.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/JsonLDReader.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/LangBase.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/ReaderTriX.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/RiotParsers.java
- jena-arq/src/main/java/org/apache/jena/riot/process/StreamRDFApplyObject.java
- jena-arq/src/main/java/org/apache/jena/riot/process/normalize/CanonicalizeLiteral.java
- jena-arq/src/main/java/org/apache/jena/riot/process/normalize/DatatypeHandler.java
- jena-arq/src/main/java/org/apache/jena/riot/process/normalize/NormalizeValue.java
- jena-arq/src/main/java/org/apache/jena/riot/process/normalize/StreamCanonicalLiterals.java
- jena-arq/src/main/java/org/apache/jena/riot/system/MakerRDFStd.java
- jena-arq/src/main/java/org/apache/jena/riot/system/ParserProfile.java
- jena-arq/src/main/java/org/apache/jena/riot/system/ParserProfileBase.java
- jena-arq/src/main/java/org/apache/jena/riot/system/RiotLib.java
- jena-arq/src/test/java/org/apache/jena/riot/TestRDFParser.java
- jena-arq/src/test/java/org/apache/jena/riot/lang/TestLangNTuples.java
- jena-arq/src/test/java/org/apache/jena/riot/lang/TestTriXReader.java
- jena-arq/src/test/java/org/apache/jena/riot/process/TestNormalization.java
- jena-cmds/src/main/java/riotcmd/CmdLangParse.java
This PR:
- adds the ability to put in a "canonicalise literals" step into the parsing process (more for JENA-1306).
- adds `RDFParser.source` operations to create a parser builder and set the source in one step (reduces the need to see RDFParserBuilder for common cases)
- Removes explicit ReaderRIOTFactory.create(Language) which does not fit well with `RDFParser`, leaving a default method in the interface.
> RDFParser refinements.

- jena-core/src/main/java/org/apache/jena/rdf/model/Literal.java
Tried to clarify what happens when users provide Long values that fit into Integers, for [JENA-733](https://issues.apache.org/jira/browse/JENA-733).
I think if the docs are good to be merged, then the issue in JIRA can be closed too.
Cheers
Bruno
> JENA-733 add documentation for narrower data type case

- jena-arq/src/main/java/org/apache/jena/riot/writer/JsonLDWriter.java
- jena-arq/src/test/java/org/apache/jena/riot/writer/TestJsonLDWriter.java
"" prefix are not allowed in jsonld's @context. "" ns prefix defined in a model were therefore ignored. This pull request proposes to define @vocab with the ns corresponding to such an "" prefix. Everything else remained unchanged.
cf. JENA-1292
> jsonld: @vocab in @context for "" ns prefix

- jena-arq/src/main/java/org/apache/jena/riot/lang/ReaderRIOTRDFXML.java
Set the IRIFactory to the IRI version, if parsing via RIOT and in RDF 1.1 mode.
> JENA-1324: Check for spaces in URIs (if RDF 1.1)

- jena-text-es/LICENSE
- jena-text-es/NOTICE
- jena-text-es/pom.xml
- jena-text-es/src/main/java/examples/JenaESTextExample.java
- jena-text-es/src/main/java/org/apache/jena/query/text/es/ESSettings.java
- jena-text-es/src/main/java/org/apache/jena/query/text/es/InitJenaTextES.java
- jena-text-es/src/main/java/org/apache/jena/query/text/es/TextESDatasetFactory.java
- jena-text-es/src/main/java/org/apache/jena/query/text/es/TextIndexES.java
- jena-text-es/src/main/java/org/apache/jena/query/text/es/assembler/TextIndexESAssembler.java
- jena-text-es/src/main/resources/META-INF/LICENSE
- jena-text-es/src/main/resources/META-INF/NOTICE
- jena-text-es/src/main/resources/META-INF/services/org.apache.jena.system.JenaSubsystemLifecycle
- jena-text-es/src/main/resources/data-es.ttl
- jena-text-es/src/main/resources/org/apache/jena/query/text/properties.xml
- jena-text-es/src/main/resources/text-config-es.ttl
- jena-text-es/src/test/java/org/apache/jena/query/text/es/it/BaseESTest.java
- jena-text-es/src/test/java/org/apache/jena/query/text/es/it/TextIndexESIT.java
- jena-text-es/src/test/resources/log4j.properties
- jena-text-es/testing/TextQuery/data.skos
- jena-text-es/testing/TextQuery/data1.ttl
- jena-text-es/testing/TextQuery/text-config-union.ttl
- jena-text-es/testing/TextQuery/text-config.ttl
- jena-text-es/text-config.ttl
- jena-text/src/main/java/org/apache/jena/query/text/TextDatasetFactory.java
- jena-text/src/main/java/org/apache/jena/query/text/assembler/TextAssembler.java
- jena-text/src/main/java/org/apache/jena/query/text/assembler/TextVocab.java
- pom.xml
This PR makes the ElasticSearch a separate module, that depends on jena-text.
Fuseki incorporates jena-text, not jena-text-es, and the server jar is 25M.
This is a proof-of-concept for discussion.
> jena-text-es: Separate module for ElasticSearch text search

- jena-arq/src/main/java/org/apache/jena/sparql/algebra/TableFactory.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/QueryIterator.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/binding/BindingRoot.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIterRoot.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/main/OpExecutor.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/main/QueryEngineMain.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/main/StageGeneratorGeneric.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/ref/Eval.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/ref/EvaluatorSimple.java
- jena-arq/src/main/java/org/apache/jena/sparql/path/eval/PathEngine.java
Don't test for class `QueryIterRoot`.
Don't use `QueryIterRoot` to hold a binding with set variables.
> JENA-1329: Define and use QueryIterator.isJoinIdentity.

- jena-arq/src/main/java/org/apache/jena/riot/RDFParserRegistry.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/ReaderRIOTCSV.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/RiotParsers.java
- jena-cmds/src/main/java/riotcmd/CmdLangParse.java
- jena-cmds/src/main/java/riotcmd/riot.java
Changed the style to be based on the configuration of an `RDFParserBuilder` so as not to duplicate policies such as file/URI to InputStream and determining syntax.
> JENA-1340: Handle riot command --base

- jena-arq/src/main/java/org/apache/jena/atlas/web/TypedInputStream.java
- jena-arq/src/main/java/org/apache/jena/riot/RDFDataMgr.java
- jena-fuseki1/pom.xml
- jena-fuseki2/pom.xml
Jetty dependency updates for Fuseki2 and Fuseki1.
> JENA-1341: Fuseki jetty upgrade

- jena-arq/src-examples/arq/examples/riot/ExRIOT_2.java
- jena-arq/src-examples/arq/examples/riot/ExRIOT_4.java
- jena-arq/src-examples/arq/examples/riot/ExRIOT_6.java
- jena-arq/src-examples/arq/examples/riot/ExRIOT_7.java
- jena-arq/src/main/java/org/apache/jena/riot/RDFDataMgr.java
- jena-arq/src/main/java/org/apache/jena/riot/RDFParser.java
- jena-arq/src/main/java/org/apache/jena/riot/web/HttpResponseLib.java
- jena-arq/src/main/java/org/apache/jena/sparql/modify/UpdateEngineWorker.java
- jena-arq/src/test/java/org/apache/jena/riot/lang/TestParserFactory.java
- jena-arq/src/test/java/org/apache/jena/riot/lang/TestPipedRDFIterators.java
- jena-arq/src/test/java/org/apache/jena/riot/lang/TestTriXBad.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/mgt/ActionDatasets.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/migrate/GraphLoadUtils.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/validation/json/DataValidatorJSON.java
- jena-fuseki2/jena-fuseki-core/src/test/java/org/apache/jena/fuseki/TestDatasetOps.java
RDFDataMgr was duplicating the functionality of RDFParser but was not making the same decisions. Use RDFParser execlusively by creating 3 paths in RDFDataMgr, one each for the three cases of reading from a URI, from an InputStream and from a Reader.
> JENA-1349: Use RDFParser for conneg.

- jena-arq/src/main/java/org/apache/jena/query/Dataset.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetGraph.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetGraphBase.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetGraphBaseFind.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetGraphWrapper.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetImpl.java
- jena-arq/src/main/java/org/apache/jena/sparql/graph/GraphUnionRead.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/AbstractDatasetGraphFind.java
- jena-core/src/main/java/org/apache/jena/graph/Graph.java
This PR adds:
`DatasetGraph.getUnionGraph`
`Dataset.getUnionModel`
It also adds a convenience `Graph.find()`.
> JENA-1074: Provide a union graph for DatasetGraph

- jena-arq/src/main/java/org/apache/jena/sparql/expr/NodeValue.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/nodevalue/NodeFunctions.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/nodevalue/NodeValueSortKey.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/nodevalue/NodeValueString.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/nodevalue/NodeValueVisitor.java
- jena-arq/src/main/java/org/apache/jena/sparql/function/StandardFunctions.java
- jena-arq/src/main/java/org/apache/jena/sparql/function/library/FN_Collation.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/TestNodeValue.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/nodevalue/TestNodeFunctions.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/nodevalue/TestNodeValueSortKey.java
- jena-arq/src/test/java/org/apache/jena/sparql/function/library/TestFunctionCollation.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/rewriters/NodeValueRewriter.java
Mimics the behaviour of Dydra described [here](http://blog.dydra.com/2015/05/06/collation).
When there are strings with the same language, then instead of simply comparing the text, it uses [java.text.Collator](https://docs.oracle.com/javase/7/docs/api/java/text/Collator.html) and the language locale to compare strings.
This does not create a collate:collate function as described in JENA-1313 as a possible solution, but could be still useful for users that expect the sort results to follow the values' language collation.
Needs further tests and discussion.
> JENA-1313: compare using a Collator when both literals are tagged with same language

- jena-arq/src/main/java/org/apache/jena/sparql/expr/NodeValue.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/nodevalue/NodeValueSortKey.java
- jena-arq/src/main/java/org/apache/jena/sparql/function/library/FN_Collation.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/nodevalue/TestNodeFunctions.java
- NodeValue.sameAs (complete switch statement)
- Add NodeValue.getSortKey() and use instead of casts.
- javadoc fixes
> JENA-1313: Some cleanup around NodeValueSortKey

- jena-arq/src/main/java/org/apache/jena/sparql/pfunction/library/strSplit.java
- jena-arq/src/test/java/org/apache/jena/sparql/pfunction/library/TestStrSplit.java
This is a patch to improve the behaviour of `apf:strSplit` in cases where it is invoked with inputs other than the obvious node types.
The general syntax of the property function is:
?parts apf:strSplit (?input ?regex)
The patch changes various cases that previously would have thrown `ExprEvalException` or `NotLiteralException`:
- If `?input` is an unbound variable, return no match
- If `?input` is an IRI or blank node, return no match
- If `?regex` is not a literal, return no match
- If `?parts` is a plain literal that equals one of the tokens of the parts of `?input`, return true (one match, no new variable bindings)
- If `?parts` is anything else but not a variable, return no match
- If the object is a list but does not have two elements, throw `QueryBuildException`
The patch also adds …
> JENA-1367: Improve apf:strSplit corner cases

- jena-arq/src/main/java/org/apache/jena/riot/RDFParser.java
- jena-arq/src/main/java/org/apache/jena/riot/RDFParserBuilder.java
- jena-arq/src/main/java/org/apache/jena/riot/web/HttpOp.java
...while still respecting any direct HttpClient setup.
> JENA-1378 : Set the accept header in the default use case.

- jena-base/pom.xml
- jena-core/src/main/java/org/apache/jena/util/FileUtils.java
- jena-core/src/test/java/org/apache/jena/test/TestSystemSetup.java
- jena-fuseki2/jena-fuseki-core/pom.xml
- jena-project/pom.xml
As a follow-on to JENA-1386 (update jsonld-java), this PR puts commons:commons-io as a dependency of jena-base.  It was being picked up anyway by via jsonld-java so putting into jena-base makes it more easily available.
Use std libraries (JDK, CommonsIO) in (old) `FileUtils`.
> Add commons-io to jena-base as dependency.

- jena-arq/src/main/java/org/apache/jena/sparql/util/Context.java
- jena-base/src/main/java/org/apache/jena/atlas/lib/Callback.java
Seems like we could deprecate `Callback<T>` in the next release and remove in the following, unless I am missing something about the contract for callbacks.
> Deprecate Jena's Callback<T> in favor of Java API's Consumer<T>

- jena-arq/src/main/java/org/apache/jena/riot/out/NodeFormatterTTL.java
- jena-arq/src/main/java/org/apache/jena/riot/system/PrefixMapBase.java
- jena-arq/src/main/java/org/apache/jena/riot/system/PrefixMapStd.java
- jena-arq/src/main/java/org/apache/jena/sparql/util/FmtUtils.java
- jena-arq/src/test/java/org/apache/jena/riot/out/TestNodeFmt.java
- jena-arq/src/test/java/org/apache/jena/sparql/util/TestFmtUtils.java
This PR includes the patch on [JENA-1393](https://issues.apache.org/jira/browse/JENA-1393) and also applies the same to Turtle writing.
":" in prefix local names is used on output which is spec-legal.
> JENA-1393: Format prefix names

- jena-arq/src/main/java/org/apache/jena/sparql/expr/E_StrReplace.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/RegexJava.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/nodevalue/XSDFuncOp.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/TestFunctions.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/TestXSDFuncOp.java
This includes PR#291, and consolidates pattern exceptions into RegexJava.
Full handling with Xerces regexp for "replace" functionality is a lot of work as Xerces has a separate, parallel set of classes; it is only the "x" flag that is missing from Java. JDK regex is likely to be faster. JDK has been the normal setting; Xerces is there for exact spec compliance in REGEX only.
We don't want more Xerces specific dependencies.
> JENA-1403: Tidy up regex pattern handling.

- apache-jena/pom.xml
- jena-fuseki1/pom.xml
- jena-fuseki2/apache-jena-fuseki/pom.xml
- jena-sdb/pom.xml
This sets tarLongFileMode=posix for all the tarballs created in the build.
See https://issues.apache.org/jira/browse/JENA-1411
> JENA-1411: use posix tar format with maven-assembly-plugin

- jena-text-es/pom.xml
This attempts to fix intermittent build problems with jena-text-es by increasing the startup timeout.
See https://issues.apache.org/jira/browse/JENA-1413
> JENA-1413: increase Elasticsearch startup timeout to 60 seconds

- jena-db/jena-dboe-trans-data/src/test/java/org/apache/jena/dboe/trans/recovery/TestRecovery.java
- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/sys/DatabaseOps.java
- jena-db/jena-tdb2/src/test/java/org/apache/jena/tdb2/sys/TestDatabaseOps.java
While testing 3.5.0 RC2 on Windows found another test failure. Spent some five minutes looking into this, and turns out it could be fixed by the `TemporaryFolder` rule too.
Previously, I mistakenly used `toString()` on the `TemporaryFolder`, but that prints the wrong data. You need to actually call `getRoot()` (or `newFolder()` if you want a new temp folder).
Fixed that in the previous test as well.
But more importantly, there is a limitation in `jena/tdb2/sys/DatabaseOps.java`, where it uses the timestamp formatted with colons. However, Windows doesn't like colons in file names (see https://support.microsoft.com/en-us/help/289627/how-to-enable-file-name-character-translation).
So I removed the colon characters, and the time is now formatted with `yyyy-MM-dd_HHmmss`, but happy if someone …
> Fixing tests on Windows for 3.5.0 RC2

- jena-project/pom.xml
- pom.xml
This simplifies and speeds up the quick development profile.
* Don't skip jena-iri and jena-shared-guava in -Pdev. Skipping does not always seem to work when there are new Jenkins built snapshots as well. The time difference is small.
* Remove -Pbootstrap because it is now the same as -Pdev
* Don't build javadoc when running -Pdev
(see the JIRA for some timings)
> JENA-1408: Quicker -Pdev; simplify profiles.

- jena-csv/pom.xml
- jena-fuseki2/pom.xml
- jena-project/pom.xml
- jena-spatial/pom.xml
- jena-text-es/pom.xml
- jena-text/pom.xml
This extracts the suggested version upgrades from PR#304.
It removes [maven-eclipse-plugin](http://maven.apache.org/plugins/maven-eclipse-plugin/) which is retired and no longer maintained.
> JENA-1418: Upgrade some versions

- jena-arq/src/main/java/org/apache/jena/riot/RDFParser.java
- jena-arq/src/main/java/org/apache/jena/riot/RDFParserBuilder.java
- jena-arq/src/main/java/org/apache/jena/riot/process/normalize/CanonicalizeLiteral.java
- jena-arq/src/main/java/org/apache/jena/riot/process/normalize/StreamCanonicalLangTag.java
- jena-arq/src/main/java/org/apache/jena/riot/process/normalize/StreamCanonicalLiterals.java
- jena-arq/src/test/java/org/apache/jena/riot/TestRDFParser.java
RDFParser options to handle canonical lexcial form for values ("+0123" becomes "123" for an xsd:integer) and options for handling language tags (to RFC-canonical form; to lowercase).
> JENA-1384: Canonical literals: lexical form and langTags

- jena-base/src/main/java/org/apache/jena/atlas/iterator/Iter.java
- jena-base/src/test/java/org/apache/jena/atlas/iterator/TestIter.java
- jena-core/src/main/java/org/apache/jena/graph/GraphUtil.java
- jena-core/src/test/java/org/apache/jena/graph/TestGraphUtil.java
- jena-core/src/test/java/org/apache/jena/graph/test/TestPackage.java
This PR rstructures `GraphUtil.deleteFrom` to put the decision on whether to loop on the target (_dst_) graph or the source (_src_) graph.
There are 3 algorithms for discussion:
1. Use the size of the graphs - this is the current Jena 3.5.0 policy
2. Use the size of the _src_ and iterate on the _dst_ to compare sizes
3. Iterator on both _src_ and _dst_ to compare sizes. `Graph.size` is not used at all.
The cost of `Graph.size()` can be small (already known) or large (needs to be calculated to be accurate). The latter is bad for large persistent graphs.
The PR also adds javadoc to explain how to call a specific algorithm (_src_ loop or _dst_ loop).
> Algorithms for JENA-1414

- jena-text/src/main/java/org/apache/jena/query/text/TextQueryPF.java
Fixes JENA-1439 graph queries fail to preserve text:query 'lang:xx' arg. TextQueryPF.extractArg(...) removed the arg unnecessarily from the input list, side-effecting the list which was saved in an OpPropFunc for repeated use on graph iterations and thus the argument was only present on the first graph in the iteration
> fix JENA-1439  graph queries fail 'lang:xx'

- jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetGraphBase.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetGraphOne.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetGraphSink.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetGraphZero.java
- jena-arq/src/main/java/org/apache/jena/sparql/graph/GraphFactory.java
- jena-arq/src/main/java/org/apache/jena/sparql/graph/GraphSink.java
- jena-arq/src/main/java/org/apache/jena/sparql/graph/GraphZero.java
- jena-arq/src/main/java/org/apache/jena/sparql/graph/PrefixMappingSink.java
- jena-arq/src/main/java/org/apache/jena/sparql/graph/PrefixMappingZero.java
- jena-arq/src/main/java/org/apache/jena/sparql/graph/TransactionHandlerNull.java
- jena-arq/src/main/java/org/apache/jena/sparql/util/graph/GraphSink.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/TS_Core.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/TestSpecialGraphNames.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/TestSpecials.java
A collection of datasets and associated graphs and machinery, for one-graph view datasets, empty and sink datasets.
More details on [JENA-1447](https://issues.apache.org/jira/browse/JENA-1447).
> JENA-1447: Special case datasets

- jena-elephas/jena-elephas-io/pom.xml
- pom.xml
Top level POM changes to be able to build with Java9, output for Java8.
> JENA-1475: Build with Java9

- jena-elephas/pom.xml
- jena-text-es/pom.xml
- pom.xml
Issues:
* jena-maven-tools does not pass its tests. This module is commented out. (This has happened before on an Apeche parent update.)
* the enforcer plugin has changed and now fails builds on multi-version dependency choices, requiring explicit choices which in itself is good
* jena-text-es set to use the  jackson-core that jsonld-java depends on (ElasticSearch depends on an earlier one: v2.9.0 vs 2.8.6)
* Hadoop2 is internally inconsistent so the enforcer plugin is turned off for jena-elephas
> JENA-1474: Update Apache parent POM v18 -> v19

- jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetGraphSink.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetGraphZero.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/TransactionalNotSupported.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/TransactionalNull.java
- jena-tdb/src/main/java/org/apache/jena/tdb/solver/BindingTDB.java
1. Yet another check for JENA-1482
2. Put some cut-and-paste internal code as compiled java so it stay up to date.
The (2) code is because Jena does not do multiple inheritance.
> Small improvements

- jena-arq/src/main/java/org/apache/jena/query/ParameterizedSparqlString.java
- jena-arq/src/test/java/org/apache/jena/query/TestParameterizedSparqlString.java
Logical flaws in using continue vs break inside inner loops where
causing the wrong delimiter positions to be detected and leading to
false positives being reported for potential injection attacks.  Fixing
the logic allows the user test case to pass.
> Fix delimiter parsing logic (JENA-1497)

- jena-core/src/test/java/org/apache/jena/graph/test/TestTypedLiterals.java
Follow on from JENA-1503.
This splits up some `TestTypeLiteral` tests and removes the old testing for GregorianYear< 0 which didn't test correctly, and couldn't.
> Refactor tests; don't test for GregorianYear< 0

- jena-fuseki2/apache-jena-fuseki/assembly-dist.xml
- jena-fuseki2/apache-jena-fuseki/dist/README
- jena-fuseki2/apache-jena-fuseki/fuseki.service
This adds a systemd unit file to the Fuseki2 distribution.
This is the same file that was circulated on the users list (in response to a question by @jneubert), but with reduced default memory setting (2GB), an ASF license header and some hopefully helpful comments about how to set it up.
See https://issues.apache.org/jira/browse/JENA-1501
> JENA-1501: add systemd unit file for Fuseki

- jena-arq/src/main/java/org/apache/jena/query/ParameterizedSparqlString.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIterGroup.java
- jena-arq/src/test/java/org/apache/jena/query/TestParameterizedSparqlString.java
Reformat `QueryIterGroup` prior to work on aggregates.
Remove print out in from `TestParameterizedQueryString`.
Remove a couple info warnings.
> Reformat QueryIterGroup; no test output from TestParameterizedSparqlString

- apache-jena-osgi/jena-osgi-features/src/main/resources/features.xml
- apache-jena-osgi/jena-osgi/pom.xml
This marks the `com.google.errorprone.annotations.concurrent` package
as optional. It also adds the (currently missing) `commons-codec` dependency
to the `features.xml` file.
> JENA-1508 Update OSGi provisioning features

- jena-arq/pom.xml
- jena-base/pom.xml
- jena-cmds/pom.xml
- jena-core/pom.xml
- jena-csv/pom.xml
- jena-db/pom.xml
- jena-rdfconnection/pom.xml
- jena-spatial/pom.xml
- jena-tdb/pom.xml
- jena-text-es/pom.xml
- jena-text/pom.xml
See comments here: 
https://github.com/apache/jena/pull/399
It is possible that there are more artifacts that might want this.
FYI: This does not include the following top level projects:
apache-jena, apache-jena-libs, apache-jena-osgi, jena-elephas, jena-examples, jena-extras, jena-fuseki1, jena-fuseki, jena-integration-tests, jena-iri, jena-jdbc, jena-maven-tools, jena-permissions, jena-sdb, jena-shaded-guava
> [JENA-1525] Add <Automatic-Module-Name> to <manifestEntries> for each jar module

- jena-arq/src/main/java/org/apache/jena/sparql/core/NamedGraphWrapper.java
- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/TransInteger.java
- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/TransactionCoordinator.java
- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/sys/TDBInternal.java
- jena-rdfconnection/src/main/java/org/apache/jena/rdfconnection/RDFConnectionRemoteBuilder.java
- jena-tdb/src/main/java/org/apache/jena/tdb/sys/TDBInternal.java
- jena-tdb/src/main/java/org/apache/jena/tdb/transaction/BlockMgrJournal.java
- jena-tdb/src/main/java/org/apache/jena/tdb/transaction/ObjectFileTrans.java
- jena-tdb/src/main/java/org/apache/jena/tdb/transaction/ObjectFileTransComplex.java
- jena-tdb/src/main/java/org/apache/jena/tdb/transaction/Transaction.java
- jena-tdb/src/main/java/org/apache/jena/tdb/transaction/TransactionLifecycle.java
- jena-tdb/src/main/java/org/apache/jena/tdb/transaction/TransactionManager.java
- jena-tdb/src/test/java/org/apache/jena/tdb/transaction/AbstractTestObjectFileTrans.java
- jena-tdb/src/test/java/org/apache/jena/tdb/transaction/AbstractTestObjectFileTransComplex.java
- jena-text/src/main/java/org/apache/jena/query/text/DatasetGraphText.java
- jena-text/src/main/java/org/apache/jena/query/text/TextIndexDB.java
- jena-text/src/main/java/org/apache/jena/query/text/TextIndexTDB1.java
- jena-text/src/test/java/org/apache/jena/query/text/TS_Text.java
- jena-text/src/test/java/org/apache/jena/query/text/TestTextNonTxn.java
- jena-text/src/test/java/org/apache/jena/query/text/TestTextNonTxnTDB1.java
- jena-text/src/test/java/org/apache/jena/query/text/TestTextTxn.java
- jena-text/src/test/java/org/apache/jena/query/text/TestTextTxnTDB.java
Includes the fix for JENA-1302.
Integrate a lucene text index into the transaction systems for TDB1 and DBOE/TDB2.  This way, the prepare/commit for Lucene happens during database commit and the synchronization dance (JENA-1302) does not happen.
JENA-1302 only effects TDB1, not TDB2. Only TDB1 has a commit queue that can build up under load and need to be flushed, which in turn causes a thread to take the exclusive lock and so cause the JENA-1302 lockup.
Includes the fix for JENA-1302.
Integrate a Lucene text index into the transaction systems for TDB1 and DBOE/TDB2.  This way, the prepare/commit for Lucene happens during database commit and the synchronization dance (JENA-1302) does not happen.
JENA-1302 only effects TDB1, not TDB2 or any other DatasetGraph implementation. Only TDB1 has …
> JENA-1542: Integrate Lucene index in transaction lifecycle (TDB1, TDB2).

- jena-arq/src/main/java/org/apache/jena/riot/writer/TurtleShell.java
added another constructor to `TurtleShell` that can be used to pass a custom `NodeFormatter` to `TurtleShell`
> pass a custom NodeFormatter to TurtleShell

- jena-arq/pom.xml
- jena-arq/src/main/java/org/apache/jena/riot/RDFLanguages.java
- jena-arq/src/main/java/org/apache/jena/riot/thrift/BinRDF.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/mem/TestDatasetGraphInMemoryThreading.java
- jena-base/pom.xml
- jena-base/src/main/java/org/apache/jena/atlas/io/IO.java
- jena-base/src/test/java/org/apache/jena/atlas/io/TS_IO.java
- jena-base/src/test/java/org/apache/jena/atlas/io/TestFilenameExtensions.java
- jena-base/src/test/java/org/apache/jena/atlas/lib/TestAlarmClock.java
- jena-core/pom.xml
- jena-core/src/test/java/org/apache/jena/shared/TestLockMRPlusSW.java
- pom.xml
JENA-1555, JENA-1554: Update awaitility ; add Apache Commons compress
JENA-1554: Add bz2 compression/decompression
> JENA-1554, JENA-1555: Support bz2 compressed files directly from Java.

- apache-jena-osgi/jena-osgi-features/src/main/resources/features.xml
- apache-jena-osgi/jena-osgi/pom.xml
Resolves: JENA-1557
This adds an exclusion for `org.checkerframework.checker.*`, which is now pulled in by `jena-shaded-guava`. This also adds guava (jsonld-java depends on this) and commons-compress to the `features.xml` file.
In addition, this reformats the `Import-Package` definition to make it easier to read (and maintain).
It is worth noting that the Guava version (24.1-jre) is hard-coded in the `features.xml` file. I was reluctant to add a variable for this in the root `pom.xml` file given [the note](https://github.com/apache/jena/blob/master/jena-shaded-guava/pom.xml#L46) in jena-shaded-guava. However, there may be a better way to structure that value so that it is obvious that it is tied to the jsonld-java dependency.
> Update OSGi imports

- jena-core/src/main/java/org/apache/jena/util/PrefixMappingUtils.java
- jena-core/src/test/java/org/apache/jena/util/TestPackage.java
- jena-core/src/test/java/org/apache/jena/util/TestPrefixMappingUtils.java
Some utility code that can be useful.
> JENA-1560: PrefixMappingUtils

- jena-core/src/main/java/org/apache/jena/ontology/OntModel.java
Fixed order of parameters description as they appear in the corresponding method signature (first `uri`, then `cls`).
> Fix javadoc in OntModel

- jena-arq/src/main/java/org/apache/jena/sparql/sse/builders/BuilderBinding.java
- jena-arq/src/test/java/org/apache/jena/sparql/syntax/TestSSE_Builder.java
JENA-1566 reports an issue with round tripping through SSE of tables that contain boolean literals i.e. `true` and `false`
This was due to overly strict checking in `BuilderBinding` which has been removed although a missing test for non-blank-ness was added.  Various unit tests are added around this issue.
> Fix SSE parsing on table with boolean values (JENA-1566)

- jena-arq/src/test/java/org/apache/jena/sparql/transaction/AbstractTestTransactionLifecycle.java
- jena-tdb/src/main/java/org/apache/jena/tdb/StoreConnection.java
- jena-tdb/src/main/java/org/apache/jena/tdb/setup/Build.java
- jena-tdb/src/main/java/org/apache/jena/tdb/sys/TDBMaker.java
- jena-tdb/src/main/java/org/apache/jena/tdb/transaction/DatasetGraphTransaction.java
- jena-tdb/src/test/java/org/apache/jena/tdb/TestTDBFactory.java
- jena-tdb/src/test/java/org/apache/jena/tdb/store/TestLoader.java
- jena-tdb/src/test/java/org/apache/jena/tdb/transaction/TestTransRestart.java
TDBMarker.reset and TDBMaker.createDatasetGraphTDB are operations that should not be called by applications. This PR deprecates them. If applications want to tinker with the internal of the system, they should understand the implications by seeing StoreConnection calls.
> Deprecate low level non-application operations

- jena-arq/src/main/java/org/apache/jena/riot/RDFWriter.java
Eclipse alerted for some Dead code in this class, and after having a look, I thought we actually had to check the `lang` in the second `if`, not `ct`?
Very hard to write a unit test, as the map backing the languages registry will pretty much always return a language, once you have the content type (I think).
> JENA-1590: fix if statement in RDFWriter#output

- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/TransactionCoordinator.java
Another one found in Eclipse while I was reading some other code for UUID's. The value returned from the `Set` object will be a `boolean`, so the `== null` won't ever eval to true.
This pull request uses the expression `! x` as that's what I thought we actually wanted to test. But happy to update it if I made the wrong assumption.
Could not find an easy way to generate a unit test, but if there's some simple approach, please let me know and I will update the pull request.
Thanks
Bruno
> JENA-1591: use boolean value in if expression

- jena-base/src/main/java/org/apache/jena/atlas/io/IO.java
- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/store/StorageTDB.java
- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/sys/TDBInternal.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/FusekiLib.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/build/FusekiBuildLib.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/build/FusekiBuilder.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/build/FusekiConfig.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/mgt/ActionDatasets.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/server/DataAccessPoint.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/server/DataService.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/server/DataServiceStatus.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/server/FusekiVocab.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/HttpAction.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/REST_Quads_RW.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/SPARQL_GSP_RW.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/SPARQL_Update.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/SPARQL_Upload.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/ServiceRouter.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/system/Upload.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/system/UploadDetailsWithName.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/webapp/FusekiServerListener.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/webapp/FusekiSystem.java
- jena-fuseki2/jena-fuseki-core/src/main/webapp/WEB-INF/web.xml
- jena-fuseki2/jena-fuseki-core/src/test/java/org/apache/jena/fuseki/ServerCtl.java
- jena-fuseki2/jena-fuseki-core/src/test/java/org/apache/jena/fuseki/TS_Fuseki.java
- jena-fuseki2/jena-fuseki-core/src/test/java/org/apache/jena/fuseki/TestAdmin.java
- jena-fuseki2/jena-fuseki-core/src/test/java/org/apache/jena/fuseki/TestAdminAPI.java
- jena-fuseki2/jena-fuseki-embedded/src/main/java/org/apache/jena/fuseki/embedded/FusekiServer.java
- jena-tdb/src/main/java/org/apache/jena/tdb/sys/TDBInternal.java
This follows on from PR #458 so it shows the commits for that PR in the comparison to Jena master.
It is the 3 individual commits after "Delete databases and expel from JVM".
It is a number of internal tidy-ups and updates of internal operations following from the new Jena transaction TxnType. For uploading, there are comments about file upload and moving the multitarget upload code to the `Upload` library.
> Fuseki code maintenance.

- apache-jena-osgi/jena-osgi-features/src/main/resources/features.xml
- pom.xml
This upgrades jsonld-java to the latest version. That version does not require an extra import of Guava in an OSGi environment (Guava is shaded in jsonld-java, but the bundle manifest was incorrect in 0.12.0), so the extra import can be removed from Jena's `feature.xml` file.
Tested in Karaf 4.2.0 and 4.2.1 under JDK8 and JDK10. With JDK10, one will need to also install `javax.annotation-api` in the Karaf console, but that is separate from this issue.
> JENA-1599: Upgrade to jsonld-java 0.12.1

- jena-elephas/jena-elephas-mapreduce/src/main/java/org/apache/jena/hadoop/rdf/mapreduce/filter/AbstractNodeTupleFilterMapper.java
- jena-jdbc/jena-jdbc-driver-bundle/pom.xml
- pom.xml
Simplified version of PR #474 avoiding the dependency weirdness by adding the missing dependency only for the execution of the Javadoc plugin on the offending module
cc @lewismc
> Fix JDK10 Build (JENA-1609)

- jena-db/jena-dboe-base/src/main/java/org/apache/jena/dboe/base/file/BlockAccessBase.java
- jena-db/jena-dboe-trans-data/src/main/java/org/apache/jena/dboe/trans/data/TransBinaryDataFile.java
Close file channel when closing a block to release open file descriptors
> JENA-1615 - Compaction leaks file descriptors

- jena-fuseki2/jena-fuseki-access/pom.xml
- jena-fuseki2/jena-fuseki-core/pom.xml
- jena-fuseki2/jena-fuseki-main/pom.xml
The jena-fuseki-access, jena-fuseki-core and jena-fuseki-main modules
have invalid data for Automatic-Module-Name.
This aligns the data from those modules with the existing fuseki2 module.
> JENA-1635 Fix invalid Automatic-Module-Name values

- jena-cmds/src/main/java/jena/schemagen.java
When using schemagen from the maven plugin the `header` option does not work. `header` is intended to be a template string and when `isTrue` is checked the string is cast to a boolean and the `BadBooleanException` is thrown. I believe we should check for existence here instead of "truthiness"
Also, it appears that the maven tools are no being built as part of the main project. Is that the case?
> JENA-1642: Check has value for header instead of is true

- jena-arq/src/main/java/org/apache/jena/sparql/core/GraphView.java
- jena-tdb/src/main/java/org/apache/jena/tdb/store/GraphTDB.java
The fix is the one line change in method `clear()`.
> JENA-1643: Use transactional dataset in clear().

- jena-arq/src/main/java/org/apache/jena/query/ParameterizedSparqlString.java
- jena-arq/src/test/java/org/apache/jena/query/TestParameterizedSparqlString.java
ParameterizedSparqlString now accepts an empty list of values rather than throwing a StringIndexOutOfBoundsException.
> JENA-1644 ParameterizedSparqlString Empty List fix

- jena-text/src/main/java/org/apache/jena/query/text/TextIndex.java
- jena-text/src/main/java/org/apache/jena/query/text/TextIndexLucene.java
- jena-text/src/main/java/org/apache/jena/query/text/TextQueryPF.java
Added URI predicate to the Lucene search in case of concrete subject search. 
Method added in TextIndex interface made default with a fallback to the previous implementation.
> JENA-1645: Use uri predicate in concrete subject query.

- jena-arq/src/main/java/org/apache/jena/query/ResultSetFormatter.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/optimizer/reorder/ReorderLib.java
- jena-arq/src/main/java/org/apache/jena/sparql/util/QueryExecUtils.java
- jena-db/jena-dboe-base/src/main/java/org/apache/jena/dboe/base/block/Block.java
- jena-db/jena-dboe-base/src/main/java/org/apache/jena/dboe/base/block/BlockMgr.java
- jena-db/jena-dboe-base/src/main/java/org/apache/jena/dboe/base/block/BlockMgrCache.java
- jena-db/jena-dboe-base/src/main/java/org/apache/jena/dboe/base/page/Page.java
- jena-db/jena-dboe-base/src/main/java/org/apache/jena/dboe/base/page/PageBlockMgr.java
- jena-db/jena-dboe-trans-data/src/main/java/org/apache/jena/dboe/trans/bplustree/BPT.java
- jena-db/jena-dboe-trans-data/src/main/java/org/apache/jena/dboe/trans/bplustree/BPTreeNode.java
- jena-db/jena-dboe-trans-data/src/main/java/org/apache/jena/dboe/trans/bplustree/BPTreeRecords.java
Remove one "abstract" in an interface.
Correct QueryExecUtils handling of RDF-format result sets.
> Cleanup of comments and javadoc. Trivial fixes.

- pom.xml
This removed jena-csv and jena-fuseki1 from the top POM.
> JENA-1649, JENA-1650: Remove jena-csv and jena-fuseki1 from the build

- jena-db/jena-dboe-base/pom.xml
- jena-db/jena-dboe-index-test/pom.xml
- jena-db/jena-dboe-index/pom.xml
- jena-db/jena-dboe-trans-data/pom.xml
- jena-db/jena-dboe-transaction/pom.xml
- jena-db/pom.xml
This sets a unique Automatic-Module-Name value for the modules in jena-db.
This also removes the default value in the parent pom to make it less likely that there will be future duplicates.
N.B. I scanned through all of the other artifacts generated by `mvn install -Pdev` and for the modules that advertise an AMN value, there were no other duplicates.
> JENA-1653 ensure unique automatic-module-names

- jena-core/src/main/java/org/apache/jena/rdf/model/impl/LiteralImpl.java
- jena-core/src/test/java/org/apache/jena/rdf/model/test/TestLiteralImpl.java
Was passing through the LiteralImpl class while reading code for another issue, and found the `field` variable that appeared to be not used.
Removed it, and then realized it could do with `StringBuilder` instead of String concatenation... It could also get a new formatting in the source for homogeneity, and delete a deprecated method that has been commented out... but this can be done later, and I thought keeping this smaller/simpler was better.
Two unit tests added. One for the working/happy path, and the other one for when the exception occurs. Tests working fine before and after the patch. Issue created and assigned to 3.10.0.
Cheers
Bruno
> JENA-1654: Use StringBuilder in Literal#asNumber, and remove field variable

- jena-cmds/src/main/java/jena/schemagen.java
- jena-cmds/src/test/java/jena/cmd/Test_schemagen.java
From JENA-204, when you use an input such as http://www.w3.org/ns/org#, that contains comments in multiple languages such as:
```
org:basedAt a owl:ObjectProperty, rdf:Property;
rdfs:label "based At"@en;
rdfs:label "basé à"@fr;
rdfs:label "basata a"@it;
rdfs:domain foaf:Person;
rdfs:range  org:Site;  
rdfs:comment """Indicates the site at which a person is based. We do not restrict the possibility that a person is based at multiple sites."""@en;
rdfs:comment """Indique le site sur lequel une personne est basée. Nous ne limitons pas le nombre de sites sur lesquels une personne peut être basée."""@fr;    
rdfs:comment """Indica la sede in cui una è stabilita una persona. Non esclude la possibilità che una persona sia allocata su più sedi."""@it;
rdfs:comment …
```
> JENA-204: Language aware schemagen

- jena-maven-tools/pom.xml
- jena-maven-tools/src/main/java/org/apache/jena/tools/schemagen/Source.java
- jena-maven-tools/src/test/java/org/apache/jena/tools/schemagen/SourceParameterTest.java
Following up the work on JENA-204, now this one does 2 things:
1) adds the option `lang`, so users can use the following in their configuration
```
<build>
<plugins>
<plugin>
<groupId>org.apache.jena</groupId>
<artifactId>jena-maven-tools</artifactId>
<version>3.10.0-SNAPSHOT</version>
<executions>
<execution>
<id>schemagen</id>
<goals>
<goal>translate</goal>
</goals>
</execution>
</executions>
<configuration>
<includes>
<include>src/vocabs/*</include>
</includes>
<fileOptions>
<source>
<input>src/vocabs/org.ttl</input>
<package-name>org.example.test</package-name>
<lang>fr</lang>  <-----------------
</source>
</fileOptions>
</configuration>
</plugin>
</plugins>
</build>
```
Attaching screenshot of the `Org` ontology from JENA-204 generated in French.
2) interestingly, the build was …
> JENA-204: Fix schemagen maven plugin

- jena-tdb/src/main/java/org/apache/jena/tdb/store/NodeId.java
This adds in all the derived types (some were missing) to the informational function (not used by TDB1 itself).
No on-disk change.
> Complete list of inlined types.

- jena-tdb/src/main/java/org/apache/jena/tdb/base/file/LocationLock.java
- jena-tdb/src/test/java/org/apache/jena/tdb/base/file/TestLocationLock.java
Since the lock files have slightly different formats TDB can detect when a lock file appears to be TDB2 and issue an appropriate error message to suggest users try using TDB2 instead.
This should avoid user confusion as seen in JENA-1658
> Improve error message trying to use TDB2 location with TDB (JENA-1658)

- jena-sdb/src/main/java/org/apache/jena/sdb/SDB.java
- jena-sdb/src/main/java/org/apache/jena/sdb/compiler/TransformOptimizeSubqueryFragments.java
- jena-sdb/src/main/java/org/apache/jena/sdb/engine/QueryEngineSDB.java
- jena-sdb/src/test/java/org/apache/jena/sdb/test/SDBTestMisc.java
- jena-sdb/src/test/java/org/apache/jena/sdb/test/compiler/TestTransformOptimizeSubqueryFragments.java
Algebra transformation that finds applicable restrictions that bind to e.g. OPTIONAL subqueries, and adds those restrictions into the subquery.
This reduces the amount of data that the subquery returns, and in so doing reduces that amount of data that is considered when joining to the outer query, improving performance.
e.g. Queries with multiple OPTIONALs that would take over 400msecs to execute in SQL, are transformed into ones that take 1msec.
(This is on a local MySQL containing approx 500,000 quads, and 100,000 nodes)
Currently, this is enabled by default (all unit tests still pass, not encountered any queries that fail), but there is an option to disable it in the context (optimizeSubqueryFragments = false).
> SDB Transform - improve performance of OPTIONAL, MINUS

- jena-sdb/src/main/java/org/apache/jena/sdb/layout2/TupleLoaderBase.java
- jena-sdb/src/main/java/org/apache/jena/sdb/layout2/TupleLoaderDirect.java
- jena-sdb/src/main/java/org/apache/jena/sdb/layout2/hash/TupleLoaderHashMySQL.java
Add a new interface to the TupleLoader that allows database engines with appropriate query constructs to bypass the use of a temporary table when adding data to the store.
Currently, this has only been implemented for MySQL using a layout2/hash, although in theory it could be possible to do it for other databases - e.g. Postgres 9.5+.
For a MySQL database, this reduces writing times by about 30%, (based on a local 5.7 instance running on an SSD)
> Allow direct loading of tuples without temporary tables

- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/store/value/DoubleNode62.java
- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/store/value/FloatNode.java
- jena-db/jena-tdb2/src/test/java/org/apache/jena/tdb2/store/TS_Store.java
- jena-db/jena-tdb2/src/test/java/org/apache/jena/tdb2/store/value/TestDoubleNode62.java
- jena-db/jena-tdb2/src/test/java/org/apache/jena/tdb2/store/value/TestFloatNode.java
- jena-db/jena-tdb2/src/test/java/org/apache/jena/tdb2/store/value/TestNodeIdInline.java
Add TestFloatNode for value-based testing of FloatNode.
Use canonical NaN for packing Double.NaN.
> JENA-1674: Don't sign extend Float.floatToIntBits.

- jena-arq/src/main/java/org/apache/jena/sparql/core/Transactional.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/AbstractDatasetGraphFind.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/AbstractDatasetGraphFindPatterns.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/AbstractDatasetGraphTests.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/AbstractTestDataset.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/AbstractTestGraphOverDatasetGraph.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/TestDatasetGraphViewGraphs.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/TestDatasetGraphsRegular.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/TestGraphOverDatasetMem.java
- jena-db/jena-dboe-base/src/main/java/org/apache/jena/dboe/base/file/BufferChannel.java
- jena-db/jena-dboe-trans-data/src/main/java/org/apache/jena/dboe/trans/bplustree/BPlusTree.java
- jena-db/jena-dboe-trans-data/src/main/java/org/apache/jena/dboe/trans/data/TransBinaryDataFile.java
- jena-db/jena-dboe-trans-data/src/main/java/org/apache/jena/dboe/trans/data/TransBlob.java
- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/store/GraphTDB.java
- jena-db/jena-tdb2/src/test/java/org/apache/jena/tdb2/graph/TestGraphOverDatasetTDB.java
- jena-tdb/src/main/java/org/apache/jena/tdb/index/bplustree/BPlusTree.java
- jena-tdb/src/test/java/org/apache/jena/tdb/graph/TestGraphOverDatasetTDB.java
This PR is clean up that have accumulated on some of my local branches:
- add some javadoc on test classes
- miscellaneous comment typos
- rename a test class
- remove two unused functions in `tdb2/store/GraphTDB` (not needed for TDB2; old from TDB1 fork)
- some automatic whitespace fixes
> Comments cleanup; remove unused functions.

- jena-arq/src/main/java/org/apache/jena/query/ARQ.java
- jena-arq/src/main/java/org/apache/jena/system/Txn.java
- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/Transaction.java
- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/TransactionCoordinator.java
- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/TransactionalBase.java
- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/journal/Journal.java
- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/journal/JournalControl.java
- jena-tdb/src/main/java/org/apache/jena/tdb/transaction/BlockMgrJournal.java
- jena-tdb/src/main/java/org/apache/jena/tdb/transaction/Journal.java
- jena-tdb/src/main/java/org/apache/jena/tdb/transaction/JournalEntry.java
- jena-tdb/src/main/java/org/apache/jena/tdb/transaction/ObjectFileTrans.java
- jena-tdb/src/main/java/org/apache/jena/tdb/transaction/Transaction.java
[JENA-1676](https://issues.apache.org/jira/browse/JENA-1676) : TDB1
[JENA-1677](https://issues.apache.org/jira/browse/JENA-1677) : TDB2
> JENA-1676 , JENA-1677: Make the commit step more robust against external factors

- jena-arq/pom.xml
- pom.xml
Expicit control the version of jackson.core so we can pick ones with security fixes.
> JENA-1696: Control of jackson versions. Update jsonld-java

- jena-text/src/main/java/org/apache/jena/query/text/TextIndexLucene.java
- jena-text/src/test/java/org/apache/jena/query/text/TS_Text.java
- jena-text/src/test/java/org/apache/jena/query/text/TestDatasetWithSurroundQueryParser.java
PR to add [SurroundQueryParser ](https://lucene.apache.org/core/7_1_0/queryparser/org/apache/lucene/queryparser/surround/parser/QueryParser.html) in jena-text.
> Add support SurroundQueryParser to jena-text

- jena-arq/src/test/java/org/apache/jena/sparql/expr/TestFunctions.java
This adjusts the timezone function tests to pass when run in a timezone to the west of GMT.
This is a follow-on to JENA-1659
> JENA-1659: Improve tests for western hemisphere timezones

- jena-arq/src/main/java/org/apache/jena/query/ParameterizedSparqlString.java
- Add getSyntax()/setSyntax()
- Add overloads of asQuery() and asUpdate() that take the desired Syntax
- Some white space and formatting clean up
> Support configuring syntax for Parameterized SPARQL (JENA-1705)

- pom.xml
This updates the javadoc configuration so that JDK11-based builds will succeed at the javadoc stage. As with the current maven configuration, the Java source is set to be Java8.
> Update javadoc configuration to support jdk11 builds

- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/TransactionCoordinator.java
- jena-db/jena-dboe-transaction/src/test/java/org/apache/jena/dboe/transaction/AbstractTestTxn.java
- jena-db/jena-dboe-transaction/src/test/java/org/apache/jena/dboe/transaction/TestThreadingTransactions.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TS_FusekiMain.java
- jena-tdb/src/test/java/org/apache/jena/tdb/TC_TDB.java
- jena-tdb/src/test/java/org/apache/jena/tdb/TS_TDBFactory.java
- jena-tdb/src/test/java/org/apache/jena/tdb/TestTDBFactory.java
- jena-tdb/src/test/java/org/apache/jena/tdb/store/TestDatasetTDBPersist.java
- jena-tdb/src/test/java/org/apache/jena/tdb/store/TestDynamicDatasetTDB.java
- jena-tdb/src/test/java/org/apache/jena/tdb/store/TestGraphTDB.java
- jena-tdb/src/test/java/org/apache/jena/tdb/store/TestLoader.java
- jena-tdb/src/test/java/org/apache/jena/tdb/store/TestStoreConnectionsMapped.java
- jena-tdb/src/test/java/org/apache/jena/tdb/transaction/TestTransRestart.java
- jena-tdb/src/test/java/org/apache/jena/tdb/transaction/TestTransactionTDB.java
- jena-text/src/test/java/org/apache/jena/query/text/assembler/TestTextDatasetAssembler.java
This PR cleans warning due to potentially locked or unlocked databases.
These are due to:
- Cleanup not happening at all levels sometimes.
- Deleting disk files before resetting TDB1.
- Tests for error conditions with expected exceptions not cleaning up.
> Clean up test WARN messages

- jena-core/src/main/java/org/apache/jena/reasoner/rulesys/impl/LPInterpreter.java
- jena-core/src/main/java/org/apache/jena/reasoner/rulesys/impl/SafeTripleIterator.java
- jena-core/src/main/java/org/apache/jena/reasoner/rulesys/impl/TopLevelTripleMatchFrame.java
- jena-core/src/main/java/org/apache/jena/reasoner/rulesys/impl/TripleMatchFrame.java
- jena-core/src/test/java/org/apache/jena/reasoner/rulesys/impl/TestRestartableLBRule.java
- jena-core/src/test/java/org/apache/jena/reasoner/rulesys/test/TestPackage.java
Provides a workaround to #JENA-1719.
Underlying problem is that when inferences are not run to completion
then tabled goals and associated interpreters and agenda entries can
get retained and in some cases can hold on to uncompleted iterators.
Correct fix would be to clean these up but doing this safely, especially 
in the presence of concurrent queries is tricky.
Long term solution might need serious redesign of the backward engine with 
concurrency and transactions in mind. 
This workaround wraps the iterators so that if one is retained and 
and reused across a transaction boundary then it will attempt to restart
it. So doesn't fix the underlying problem but does workaround it for this test case.
> JENA-1719: Work around for iterators being held across transactions

- jena-geosparql/src/main/java/org/apache/jena/geosparql/configuration/GeoSPARQLOperations.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/configuration/ModeSRS.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/geo/topological/GenericGeometryPropertyFunction.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/geo/topological/GenericPropertyFunction.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/geo/topological/SpatialObjectGeometryLiteral.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/spatial/SpatialIndex.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/spatial/property_functions/GenericSpatialPropertyFunction.java
- jena-geosparql/src/test/java/org/apache/jena/geosparql/configuration/GeoSPARQLOperationsTest.java
- SpatialObject no longer has to be asserted or inferred for spatial queries to complete. Instead only Feature and Geometry class relations are required.
- hasSerialization no longer has to be asserted or inferred if asGML and asWKT properties are being used.
> Geosparql schema checks

- jena-fuseki2/jena-fuseki-geosparql/src/main/java/org/apache/jena/fuseki/geosparql/DatasetOperations.java
- jena-fuseki2/jena-fuseki-geosparql/src/test/java/org/apache/jena/fuseki/geosparql/EmptyTest.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/configuration/GeoSPARQLConfig.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/spatial/SpatialIndex.java
- running the geosparql-fuseki server with an empty dataset now emits a logging warning rather than an SpatialIndexException.
- JavaDoc tidy up.
> Geosparql empty dataset

- jena-fuseki2/jena-fuseki-geosparql/pom.xml
- jena-geosparql/pom.xml
This adjusts the AMN metadata to valid names (hyphens are not allowed)
> JENA-1741 Invalid Automatic-Module-Name values

- apache-jena-osgi/jena-osgi/pom.xml
Add exclusion for google appengine and apphosting packages
Note: with this change, I am able to successfully deploy Jena in Karaf 4.x
> JENA-1742: Fix OSGi imports

- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/TransactionalFactory.java
- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/ComponentGroup.java
- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/Transaction.java
- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/TransactionCoordinator.java
- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/TransactionListener.java
- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/TransactionalComponentBase.java
- jena-db/jena-dboe-transaction/src/test/java/org/apache/jena/dboe/transaction/TestTxnSwitching.java
- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/store/TDB2StorageBuilder.java
- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/store/nodetable/NodeTableCache.java
- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/store/nodetable/ThreadBufferingCache.java
- jena-db/jena-tdb2/src/test/java/org/apache/jena/tdb2/TS_Factory.java
- jena-db/jena-tdb2/src/test/java/org/apache/jena/tdb2/TestTDB2.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/server/Operation.java
- jena-text/src/main/java/org/apache/jena/query/text/DatasetGraphText.java
Introduces `ThreadBufferingCache` and `TransactionListener`.
Adds a layer of caching for a write transaction so the caches can be aborted.
> JENA-1746: TDB2 abort

- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/loader/main/DataToTuples.java
This prevents the thread from running until after a loading operation has returned, which can cause problems when the dataset is used immediately thereafter.
> JENA-1758: Wait for the thread to complete when finishing bulk loading

- jena-base/src/main/java/org/apache/jena/atlas/iterator/Iter.java
- jena-core/src/main/java/org/apache/jena/graph/GraphUtil.java
- jena-db/jena-dboe-storage/src/main/java/org/apache/jena/dboe/storage/StorageRDF.java
- jena-db/jena-dboe-storage/src/main/java/org/apache/jena/dboe/storage/prefixes/PrefixMapI.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/ExprFactory.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/UpdateBuilder.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/handlers/ValuesHandler.java
- jena-extras/jena-querybuilder/src/test/java/org/apache/jena/arq/querybuilder/ExprFactoryTest.java
- jena-extras/jena-querybuilder/src/test/java/org/apache/jena/arq/querybuilder/UpdateBuilderExampleTests.java
- jena-extras/jena-querybuilder/src/test/java/org/apache/jena/arq/querybuilder/rewriters/NodeValueRewriterTest.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/server/ActionServiceFactory.java
- jena-jdbc/jena-jdbc-core/src/test/java/org/apache/jena/jdbc/utils/TestUtils.java
- jena-text-es/pom.xml
- pom.xml
Preparation for 3.13.0 release.
> Clean javadoc

- jena-db/jena-dboe-storage/pom.xml
- jena-elephas/jena-elephas-common/pom.xml
- jena-elephas/jena-elephas-io/pom.xml
- jena-elephas/jena-elephas-mapreduce/pom.xml
- jena-elephas/jena-elephas-stats/pom.xml
- jena-jdbc/jena-jdbc-core/pom.xml
- jena-jdbc/jena-jdbc-driver-bundle/pom.xml
- jena-jdbc/jena-jdbc-driver-mem/pom.xml
- jena-jdbc/jena-jdbc-driver-remote/pom.xml
- jena-jdbc/jena-jdbc-driver-tdb/pom.xml
- jena-shacl/pom.xml
- This adds missing AMN metadata to `jena-dboe-storage` (an empty string is invalid)
- This fixes incorrect AMN for `jena-shacl` (it currently duplicates the tdb module name)
- This also fixes duplicate AMN metadata for the `jena-elephas-*` and `jena-jdbc-*` modules
> JENA-1764: Fix Automatic-Module-Name metadata

- jena-arq/src/main/java/org/apache/jena/riot/RDFDataMgr.java
- jena-arq/src/main/java/org/apache/jena/riot/RDFParserBuilder.java
- jena-arq/src/main/java/org/apache/jena/riot/RDFWriterBuilder.java
- jena-arq/src/main/java/org/apache/jena/riot/RIOT.java
- jena-arq/src/main/java/org/apache/jena/riot/system/RiotLib.java
- jena-arq/src/main/java/org/apache/jena/riot/writer/TurtleShell.java
Two halves or JENA-1761:
"General option setting for RDFParser and RDFWriter" -- the mechanism
"Option to write Turtle with PREFIX and BASE" -- used for Turtle.
The default remains the "@prefix" forms.
> JENA-1761: General option setting for RDFParser and RDFWriter

- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/server/Operation.java
- jena-fuseki2/jena-fuseki-webapp/src/main/webapp/js/app/models/dataset.js
JENA-1766 corrected a bug but also showed that the case of an endpoint on the dataset itself never works. i.e the interface did not handle "/ds?query=". It didn't show because when using the old configuration happen to put "/ds/sparql" before "/ds" in the list of endpoint options (by chance - the server has a hash map).
This PR fixes this - with the new endpoint configuration (JENA-1731), it is now easier to write a configuration with dataset level query only and it is also now documented how to configure that with:
fuseki:endpoint  [ fuseki:operation fuseki:query ] ;
>  JENA-1766: (more) Handle the case of dataset endpoint (service name = "")

- jena-arq/src/main/java/org/apache/jena/riot/system/stream/LocatorClassLoader.java
- jena-core/src/main/java/org/apache/jena/util/LocatorClassLoader.java
This responds to the report on users@.
The problem is that the Java resource name is illegal (it has a ":" in it). Until Java13, it seems this was accepted without an exception being thrown.
Solution: protect the call and ignore the exception.
Due to maximising legacy (at the time) there are two LocatorClassLoader - the non-riot one gets used if jena-core is used its own but it also gets touched when installing the RIOT StreamManager code.
> JENA-1775: Protect against a bad resource name

- jena-base/src/main/java/org/apache/jena/atlas/lib/cache/CacheSimple.java
- jena-base/src/test/java/org/apache/jena/atlas/lib/cache/CacheSimpleTest.java
Added an explicit check for keys' equality
> JENA-1784 CacheSimple doesn't check keys for equality

- jena-core/src/main/java/org/apache/jena/vocabulary/DCAT.java
The **Data Catalog Vocabulary (DCAT)** [Version 1](https://www.w3.org/TR/2014/REC-vocab-dcat-20140116/) has been extended to [Version 2](https://www.w3.org/TR/2019/PR-vocab-dcat-2-20191119/) on 19 November 2019 as W3C Proposed Recommendation.
In Apache Jena, there is [org.apache.jena.vocabulary.DCAT](https://github.com/apache/jena/blob/d11b5c8ea739068abd1ab53fc1360e536d6ea471/jena-core/src/main/java/org/apache/jena/vocabulary/DCAT.java) containing Resources (classes) and Properties of version 1.
The additions of this pull request were generated based on data from official docs:
https://github.com/projekt-opal/vocabulary-enhancement
Added a fix to #644
> DCAT vocabulary version 2

- jena-core/src/main/java/org/apache/jena/vocabulary/DCAT.java
Double-checked DCAT2 changes with https://w3c.github.io/dxwg/dcat/rdf/dcat.ttl
dcat:Resource is the only missing URI in namespace.
Code: https://github.com/projekt-opal/vocabulary-enhancement/blob/197a19ab369420a6b43961738a5dbe3140417e0b/src/main/java/org/dice_research/opal/vocabulary_enhancement/RdfImporter.java#L26
> Added dcat:Resource

- jena-arq/pom.xml
- jena-base/pom.xml
- jena-base/src/main/java/org/apache/jena/atlas/lib/StrUtils.java
- jena-cmds/pom.xml
- jena-core/pom.xml
- jena-db/jena-dboe-base/pom.xml
- jena-db/jena-dboe-storage/pom.xml
- jena-db/pom.xml
- jena-elephas/jena-elephas-io/pom.xml
- jena-elephas/pom.xml
- jena-fuseki2/jena-fuseki-geosparql/pom.xml
- jena-geosparql/pom.xml
- jena-geosparql/src/main/java/org/apache/jena/geosparql/configuration/GeoSPARQLOperations.java
- jena-integration-tests/pom.xml
- jena-iri/pom.xml
- jena-jdbc/jena-jdbc-core/src/main/java/org/apache/jena/jdbc/metadata/JenaMetadata.java
- jena-jdbc/jena-jdbc-core/src/main/java/org/apache/jena/jdbc/results/JenaResultSet.java
- jena-jdbc/jena-jdbc-core/src/main/java/org/apache/jena/jdbc/statements/JenaStatement.java
- jena-jdbc/jena-jdbc-driver-bundle/pom.xml
- jena-permissions/pom.xml
- jena-rdfconnection/pom.xml
- jena-sdb/pom.xml
- jena-shacl/pom.xml
- jena-tdb/pom.xml
- pom.xml
Also some general tidying to prepare for the 3.14.0 release: 
* Remove unnecessary <groupId> and <version> (Eclipse warnings of duplicates)
* POM fix to jena-db (old style causes a warning with Apache POM v22).
* A few plugin version updates
* Remove some code warnings.
* A javadoc fix.
>  JENA-1814: Update to Apache parent POM v22.

- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/TransactionCoordinator.java
- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/store/nodetable/NodeTableCache.java
- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/store/nodetable/ThreadBufferingCache.java
- jena-db/jena-tdb2/src/test/java/org/apache/jena/tdb2/TestTDB2.java
The relevant change is:
https://github.com/apache/jena/compare/master...afs:jena1817_tdb2_node_cache?expand=1#diff-e27c3f5f1ae576b9ebb6655fb0585cb6L328
[The test](https://github.com/apache/jena/compare/master...afs:jena1817_tdb2_node_cache?expand=1#diff-d0b153bc6d2468facb2de0d2cf244206R104) in involves waiting points.
From experience, this isn't safe long term. On build systems under load, we have seen very long pauses (many seconds) in thread scheduling. Therefore, the test may need to be tweaked or removed. It has done the necessary proof - undo the fix and the test reliably fails.
> JENA-1817: Flush NodeTableCache in CommitFinish

- jena-arq/src/main/java/org/apache/jena/riot/lang/BlankNodeAllocatorFixedSeedHash.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/BlankNodeAllocatorHash.java
- jena-base/src/main/java/org/apache/jena/atlas/lib/Bytes.java
- pom.xml
Use Murmur3-128bit for blank node label allocation. This code is called when a blank node appears in RDF syntax.
This is an alternative to #667 as discussed at [JENA-1812](https://issues.apache.org/jira/browse/JENA-1812) (Security software is being to flag up the use of MD5)
Murmur3-128 retains the length of blank node labels at 32 hex digits while not triggering security scans.
The murmurs implementation is the one from Apache Commons Codec. The differences between it and the Guava implementation are, for this usage, slight. For reference, the Guava version is includes in the source but the compiler does not generate any bytecode.
> JENA-1812: Switch to Murmur3 for blank node allocation

- jena-fuseki2/apache-jena-fuseki/fuseki-server
- jena-fuseki2/apache-jena-fuseki/fuseki.service
Sets Fuseki server (full server) to 4G, up from 1.2G or 2G.
[JENA-1832](https://issues.apache.org/jira/browse/JENA-1832)
> JENA-1832: Default max heap size setting

- jena-sdb/src/main/java/org/apache/jena/sdb/compiler/TransformOptimizeSubqueryFragments.java
- jena-sdb/src/test/java/org/apache/jena/sdb/test/compiler/TestTransformOptimizeSubqueryFragments.java
Encountered a case using a UNION in a query to select e.g. objects where type is asserted as X, Y or Z (but not A, B, C, etc.)
Pull request prevents the transformer from copying restrictions out of a UNION so that the algebra is correct in this case.
Includes a test for a query that exhibits the problem. All previously existing transformer tests are unmodified and continue to pass, as do all the other unit tests in SDB.
https://issues.apache.org/jira/browse/JENA-1831
> JENA-1831: Fix SDB transform issue with using UNION in restrincting a query

- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/ResponseDataset.java
The pretty (aka abbreviated) RDF/XML serialization of Fuseki RDF responses (CONSTRUCT and DESCRIBE queries) sometimes takes excessive amounts of time and CPU to generate. This PR makes Fuseki use plain RDF/XML instead, which is faster to generate.
I had to pass a `RDFFormat` instead of `Lang` to `RDFDataMgr.write()` as it allows more fine-grained control over the serialization syntax. The logic was copied from the GSP_R class.
Jira link: https://issues.apache.org/jira/browse/JENA-1826
> JENA-1826: use plain RDF/XML in Fuseki RDF responses

- jena-core/src/main/java/org/apache/jena/datatypes/DatatypeFormatException.java
This implements the TODO in this class.
> JENA-1835: Capture and expose lexicalForm and dataType in DatatypeFormatException

- jena-geosparql/src/main/java/org/apache/jena/geosparql/geo/topological/SpatialObjectGeometryLiteral.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/spatial/SpatialIndex.java
- jena-geosparql/src/test/java/org/apache/jena/geosparql/geo/topological/SpatialObjectGeometryLiteralTest.java
GeoSPARQL
- multiple cases of geo:lat or geo:lon now result in an exception and closure of iterators.
- geo:lat and geo:lon made required properties.
> GeoSPARQL: Malformed geo:lat and geo:lon checks

- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/loader/main/DataToTuples.java
- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/loader/main/Indexer.java
- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/loader/main/PhasedOps.java
This is a minor change to handle the signalling at the end of thread execution to follow the pattern used elsewhere in TDB2 tdbloader.
> JENA-1758: Use a semaphore to notify thread has finished

- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/AbstractQueryBuilder.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/AskBuilder.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/ConstructBuilder.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/Converters.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/DescribeBuilder.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/ExprFactory.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/SelectBuilder.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/UpdateBuilder.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/WhereBuilder.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/clauses/ValuesClause.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/clauses/WhereClause.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/handlers/WhereHandler.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/updatebuilder/QuadIteratorBuilder.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/updatebuilder/SingleQuadHolder.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/updatebuilder/WhereQuadHolder.java
- jena-extras/jena-querybuilder/src/test/java/org/apache/jena/arq/querybuilder/AbstractQueryBuilderTest.java
- jena-extras/jena-querybuilder/src/test/java/org/apache/jena/arq/querybuilder/ConvertersTest.java
- jena-extras/jena-querybuilder/src/test/java/org/apache/jena/arq/querybuilder/ExprFactoryTest.java
Moved all Node type buiding statics methods to new Converters class.
Deprecated old methods if they were moved to Converters.
Updated classes to call new Converters methods.
Added Converters.makeLiteral( Object ) that throws
IllegalArgumentException if Object class does not have a registered
Datatype.
Added Converters.makeLiteral( String value , String typeUri ) to build
arbitrary literals suitable for query building and serialization output.
Modified Converters.makeNode() to call Converters.makeLiteral() if a
literal is required.
> Fixes for JENA-1841

- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/SPARQLQueryProcessor.java
The old documentation said this:
// Does not matter about race condition here because the same Set should be
// created on any call to generateAcceptedParams.
But this does not make the race in any way benign.
Since we are doing racy reads, it is in fact possible that after
any of the `if(acceptedParams_ == null)` evaluates to true
- and replaces acceptedParams_ with a non-null value -
`return acceptedParams_` can still return null!
Other possible ways to solve this problem are detailed [here](https://shipilev.net/blog/2014/safe-public-construction/#_safe_publication).
> JENA-1866: Add volatile to make method thread-safe

- jena-db/jena-dboe-trans-data/src/test/java/org/apache/jena/dboe/trans/bplustree/TestBPlusTreeNonTxn.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/AuthFilter.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/cmds/FusekiMain.java
- jena-tdb/src/test/java/org/apache/jena/tdb/base/record/RecordLib.java
- jena-tdb/src/test/java/org/apache/jena/tdb/index/IndexTestLib.java
- jena-text/src/main/java/org/apache/jena/query/text/TextIndexDB.java
Various code cleanup.
The "unused imports" originate from Eclipse now reporting things it wasn't reporting. I can't tell whether this is local to my installation (e.g. config bug) or an Eclipse change.
> Cleanup code

- jena-fuseki2/jena-fuseki-webapp/src/main/webapp/js/lib/qonsole.js
This caused a mixed-content error and the call was blocked by the browser (thereby rendering the entire prefix.cc lookup as useless) when Fuseki was run via https.
> JENA-1878: switched API call to prefix.cc from http to https

- jena-arq/src/main/java/org/apache/jena/query/Query.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementData.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementPathBlock.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/ElementTransformCopyBase.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/ExprTransformApplyElementTransform.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/QueryTransformOps.java
- jena-arq/src/test/java/org/apache/jena/query/TestQueryCloningCornerCases.java
- jena-arq/src/test/java/org/apache/jena/query/TestQueryCloningEssentials.java
This PR changes the implementation of Query.clone to make use of the syntax transform machinery.
A parameterized test case runner with 1230 queries is provided in TestQueryCloningEssentials
A test case for inital corner cases is provided in TestQueryCloningCornerCases - the main purpose is to check that modification of elements of a clone do not affect the original query. Note, that  Query.elementDataBlock is not cloned, I'd said this is an issue in QueryTransformOps.
A little commented out by means of "// @ Test" benchmark runner is provided in TestQueryCloningCornerCases as well.
> JENA-1862: Query.clone is slow

- apache-jena-osgi/jena-osgi/pom.xml
This excludes the log4j2 dependency from the OSGi bundle metadata
> JENA-1888: Mark log4j2 optional in OSGi bundle

- jena-base/src/main/java/org/apache/jena/atlas/lib/StrUtils.java
- jena-base/src/test/java/org/apache/jena/atlas/lib/TestStrUtils.java
- jena-cmds/src/main/java/tdb/tdbloader.java
- jena-cmds/src/main/java/tdb2/tdbloader.java
Only affects URIs which also have a hex-encoded character (currently, "_", which is the marker character or " ").
> JENA-1890: Correctly decode URI with multibyte codepoints

- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/StrMaxLengthConstraint.java
- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/StrMinLengthConstraint.java
I had a look at the tests and because of the [optional properties](https://github.com/apache/jena/blob/master/jena-shacl/src/main/java/org/apache/jena/shacl/validation/VR.java#L161) the resultMessage values aren't checked in the validation checks.
> JENA-1891 reversed resultMessage values

- jena-arq/src/main/java/org/apache/jena/riot/resultset/rw/JSONResultsKW.java
- jena-arq/src/main/java/org/apache/jena/riot/resultset/rw/ResultSetReaderJSON.java
- jena-arq/src/main/java/org/apache/jena/riot/resultset/rw/ResultsReader.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetGraphMap.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/TransactionalLock.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/nodevalue/XSDFuncOp.java
- jena-arq/src/test/java/org/apache/jena/rdf_star/TestSPARQLStarExtra.java
- jena-arq/src/test/java/org/apache/jena/sparql/TC_Scripted.java
- jena-arq/testing/ARQ/RDF-Star/Other/alternate-results.srj
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/Fuseki.java
The JSON result form changes are not defined in RDF* so there are variations.
This PR adds being about to read RDF4J variation of JSON results.
Also some cleanups that got noticed.
> JENA-1881: Add being able to read variations of RDF* JSON syntax.

- jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIterBlockTriplesStar.java
- jena-core/src/main/java/org/apache/jena/enhanced/EnhNode.java
- jena-core/src/main/java/org/apache/jena/rdf/model/Model.java
- jena-core/src/main/java/org/apache/jena/rdf/model/RDFNode.java
- jena-core/src/main/java/org/apache/jena/rdf/model/RDFVisitor.java
- jena-core/src/main/java/org/apache/jena/rdf/model/Resource.java
- jena-core/src/main/java/org/apache/jena/rdf/model/ResourceFactory.java
- jena-core/src/main/java/org/apache/jena/rdf/model/impl/ModelCom.java
- jena-core/src/main/java/org/apache/jena/rdf/model/impl/ResourceImpl.java
- jena-core/src/main/java/org/apache/jena/rdf/model/impl/StatementImpl.java
- jena-core/src/test/java/org/apache/jena/rdf/model/test/TestRDFNodes.java
- jena-core/src/test/java/org/apache/jena/rdf/model/test/TestResourceFactory.java
- jena-permissions/src/main/java/org/apache/jena/permissions/model/impl/SecuredModelImpl.java
- jena-permissions/src/main/java/org/apache/jena/permissions/model/impl/SecuredRDFNodeImpl.java
- jena-permissions/src/main/java/org/apache/jena/permissions/model/impl/SecuredResourceImpl.java
- jena-permissions/src/test/java/org/apache/jena/permissions/model/SecuredRDFNodeTest.java
- jena-permissions/src/test/java/org/apache/jena/permissions/model/SecuredResourceTest.java
This PR adds triple term to the mode API by making them a kind of "Resource", along side URI and blank node.
This is the only way to incorporate triple terms without a major change to the type-safe API because they can appear in the subject position.
> JENA-1881: Model API changes for RDF*

- pom.xml
Details: [JENA-1898](https://issues.apache.org/jira/browse/JENA-1898).
> JENA-1898: Exclude commons-codec from httpcomponents dependencies

- jena-shaded-guava/pom.xml
Update to Guava 29.0-jre.
Clear up the shaded artifact POM a little to reflect the current dependency state of Guava itself.
> JENA-1896: Update Google Guava

- jena-base/src/main/java/org/apache/jena/atlas/io/BufferingWriter.java
- jena-base/src/test/java/org/apache/jena/atlas/io/TestBufferingWriter.java
[JENA-1920](https://issues.apache.org/jira/browse/JENA-1920): BufferingWriter.java will flush the entirety of a char array despite provided length.
[JENA-1919](https://issues.apache.org/jira/browse/JENA-1919): ArrayIndexOutOfBounds in BufferingWriter.java
> JENA-1919, JENA-1920: Fixes for BufferingWriter

- jena-arq/src/main/java/org/apache/jena/atlas/json/io/parser/TokenizerJSON.java
- jena-arq/src/main/java/org/apache/jena/riot/RDFParser.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/RiotParsers.java
- jena-arq/src/main/java/org/apache/jena/riot/system/ErrorHandlerFactory.java
- jena-arq/src/main/java/org/apache/jena/riot/system/RiotChars.java
- jena-arq/src/main/java/org/apache/jena/riot/system/stream/LocationMapper.java
- jena-arq/src/main/java/org/apache/jena/riot/system/stream/StreamManager.java
- jena-arq/src/main/java/org/apache/jena/riot/tokens/ErrorHandlerTokenizer.java
- jena-arq/src/main/java/org/apache/jena/riot/tokens/Token.java
- jena-arq/src/main/java/org/apache/jena/riot/tokens/TokenizeTextBuilder.java
- jena-arq/src/main/java/org/apache/jena/riot/tokens/TokenizerFactory.java
- jena-arq/src/main/java/org/apache/jena/riot/tokens/TokenizerText.java
- jena-arq/src/test/java/org/apache/jena/riot/lang/AbstractTestLangNTuples.java
- jena-arq/src/test/java/org/apache/jena/riot/lang/TestLangTrig.java
- jena-arq/src/test/java/org/apache/jena/riot/lang/TestLangTurtle.java
- jena-arq/src/test/java/org/apache/jena/riot/tokens/TestTokenizer.java
- jena-arq/testing/RIOT/Lang/Changes
- jena-arq/testing/RIOT/Lang/TrigStd/manifest.ttl
- jena-arq/testing/RIOT/Lang/TurtleStd/manifest.ttl
- jena-core/src/main/java/org/apache/jena/util/FileManagerImpl.java
- jena-db/jena-dboe-base/src/main/java/org/apache/jena/dboe/sys/Sys.java
- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/sys/SystemTDB.java
- jena-db/jena-tdb2/src/test/java/org/apache/jena/tdb2/ConfigTest.java
- jena-fuseki2/jena-fuseki-webapp/src/test/java/org/apache/jena/fuseki/TestAdminAPI.java
- jena-iri/src/main/java/org/apache/jena/iri/impl/Parser.java
This PR fixes for JENA-1924 (Turtle, NT etc, not RDF/XML) both the reported character and caharacters byond the Unicode Basic Plane. This in turn revealed illegal IRIs in WG 2 tests.
* Configurable `ErrorHandler` for TokenizerText.
* Differentiate "fatal" errors in tokens (always unrecoverable) and "error" where the data is wrong (bad IRI) but tokenizing can continue.
* Allow a configurable ErrorHandler for TokenizerText.
* Fix Turtle/Trig WG tests because the tests themselves contain bad IRIs.
* (unrelated) minor cleaning tweaks to StreamManager trigger noticed during recent users@ discussions.
> JENA-1924: Test for ucschar in tokenizer.

- jena-arq/src/main/java/org/apache/jena/riot/lang/RiotParsers.java
- jena-arq/src/main/java/org/apache/jena/riot/system/IteratorStreamRDFText.java
- jena-arq/src/main/java/org/apache/jena/riot/system/RiotLib.java
- jena-arq/src/main/java/org/apache/jena/riot/system/SerializationFactoryFinder.java
- jena-arq/src/main/java/org/apache/jena/riot/tokens/TokenizerFactory.java
- jena-arq/src/main/java/org/apache/jena/riot/tokens/TokenizerText.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/binding/BindingInputStream.java
- jena-arq/src/main/java/org/apache/jena/sparql/util/NodeFactoryExtra.java
- jena-arq/src/test/java/org/apache/jena/riot/lang/AbstractTestLangNTuples.java
- jena-arq/src/test/java/org/apache/jena/riot/lang/TestLangRdfJson.java
- jena-arq/src/test/java/org/apache/jena/riot/lang/TestParserFactory.java
- jena-arq/src/test/java/org/apache/jena/riot/lang/TestTurtleTerms.java
- jena-arq/src/test/java/org/apache/jena/riot/tokens/TestTokenizer.java
- jena-arq/src/test/java/org/apache/jena/sparql/engine/binding/TestBindingStreams.java
- jena-cmds/src/main/java/riotcmd/CmdLangParse.java
- jena-cmds/src/main/java/riotcmd/CmdTokens.java
- jena-elephas/jena-elephas-io/src/main/java/org/apache/jena/hadoop/rdf/io/input/readers/AbstractLineBasedNodeTupleReader.java
- jena-extras/jena-querybuilder/src/test/java/org/apache/jena/arq/querybuilder/clauses/DatasetClauseTest.java
- jena-extras/jena-querybuilder/src/test/java/org/apache/jena/arq/querybuilder/clauses/PrologClauseTest.java
- jena-extras/jena-querybuilder/src/test/java/org/apache/jena/arq/querybuilder/clauses/SolutionModifierTest.java
- jena-permissions/src/test/java/org/apache/jena/permissions/MockSecurityEvaluator.java
- jena-permissions/src/test/java/org/apache/jena/permissions/ModelBasedSecurityEvaluator.java
- jena-permissions/src/test/java/org/apache/jena/permissions/StaticSecurityEvaluator.java
- jena-permissions/src/test/java/org/apache/jena/permissions/model/SecuredContainerTest.java
- jena-shacl/src/main/java/org/apache/jena/shacl/compact/ShaclCompactParser.java
- jena-tdb/src/main/java/org/apache/jena/tdb/store/nodetable/NodecSSE.java
... in favour of TokenizerText builder. 
Remove unused imports noticed while checking TokenizerFactory wasn't being used.
> JENA-1931: Deprecate/remove TokenizerFactory 

- jena-arq/src/main/java/org/apache/jena/riot/RDFLanguages.java
- jena-arq/src/main/java/org/apache/jena/riot/thrift/StreamRDF2Thrift.java
- jena-arq/src/main/java/org/apache/jena/riot/thrift/TRDF.java
- jena-arq/src/main/java/org/apache/jena/riot/thrift/WriterDatasetThrift.java
- jena-arq/src/main/java/org/apache/jena/riot/thrift/WriterGraphThrift.java
- jena-arq/src/test/java/org/apache/jena/riot/thrift/TestThriftSetup.java
- jena-rdfconnection/src/main/java/org/apache/jena/rdfconnection/RDFConnectionRemoteBuilder.java
More clean-up for JENA-1933 and also triggered by user@ investigation of RDF Thrift usage.
No functional changes.
> JENA-1933: Prefer const RDFLanguages.RDFTHRIFT to .THRIFT

- jena-jdbc/jena-jdbc-core/src/main/java/org/apache/jena/jdbc/statements/JenaStatement.java
The method JenaStatement.getUpdateCount() returns 0. But java.sql.Statement documentation says:
Returns: the current result as an update count; -1 if the current result is a ResultSet object or there are no more results
Returning correct value is important because a single statement may have multiple result sets and cause mutiple updates (not only multiple updated records, but multiple sets of updated records).
Applications (e.g. SQL-DK) iterate over these multiple results and need to know when finish. The getMoreResults() documentation says:
There are no more results when the following is true: ((stmt.getMoreResults() == false) && (stmt.getUpdateCount() == -1))
But if 0 is returned, the application enters infinite loop.
> JENA-1939: fix getUpdateCount() in the JDBC driver

- jena-fuseki2/jena-fuseki-docker/Dockerfile
- jena-fuseki2/jena-fuseki-docker/README.md
- jena-fuseki2/jena-fuseki-docker/assembly-docker.xml
- jena-fuseki2/jena-fuseki-docker/dist/LICENSE
- jena-fuseki2/jena-fuseki-docker/dist/NOTICE
- jena-fuseki2/jena-fuseki-docker/docker-compose.yaml
- jena-fuseki2/jena-fuseki-docker/download.sh
- jena-fuseki2/jena-fuseki-docker/entrypoint.sh
- jena-fuseki2/jena-fuseki-docker/log4j2.properties
- jena-fuseki2/jena-fuseki-docker/pom.xml
This creates a zip that would be part of a Jena release.
The zip file has the Dockerfile/docker-compose.yml and documentation to build locally.
The container is based on alpine.
The build creates a trimmed down Java11 runtime.
The Fuseki container is about 82 Mb.
> JENA-1949: Docker tools for Fuseki

- jena-arq/src-examples/arq/examples/riot/Ex_WriteJsonLD.java
- jena-arq/src/main/java/org/apache/jena/riot/JsonLDReadContext.java
- jena-arq/src/main/java/org/apache/jena/riot/JsonLDWriteContext.java
- jena-arq/src/main/java/org/apache/jena/riot/RIOT.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/JsonLDReader.java
- jena-arq/src/main/java/org/apache/jena/riot/writer/JsonLDWriter.java
- jena-arq/src/test/java/org/apache/jena/riot/TestJsonLDReader.java
- pom.xml
Fixes https://issues.apache.org/jira/browse/JENA-1959
- Adds the analogous to `JsonLdWriteContext` when converting JSON to RDF (toRdf on the JSON-LD high level API)
- Updates Json-LD Java from 0.12.5 to 0.13.0
> JENA-1959 Added JsonLdReadContext

- jena-arq/pom.xml
To support custom SPARQL functions written in JavaScript, ARQ can interchangeably use Nashorn or Graal.js scripting engines (the former will be removed in JDK 15).
On JDK  versions prior to JDK 15 ARQ can be compiled and used without any Graal-related dependencies.
On JDK 15 onward using JavaScript would require having org.graalvm.js:js and org.graalvm.js-scriptengine on the class path. 
However, as Java Scripting API uses a SPI-based mechanism, they don't have to be included as compile-time dependencies. 
They still need to be included as test dependencies to make it possible to compile ARQ on JDK 15+.
See also the discussion in https://github.com/apache/jena/pull/787
> JENA-1950: Make GraalVM a test dependency

- jena-arq/src-examples/arq/examples/riot/Ex_WriteJsonLD.java
- jena-arq/src/main/java/org/apache/jena/riot/JsonLDWriteContext.java
- jena-arq/src/test/java/org/apache/jena/riot/TestJsonLDReader.java
- jena-arq/src/test/java/org/apache/jena/riot/writer/TestJsonLDWriter.java
- pom.xml
JsonLD Java version 0.13.1 [fixed support for remote context Uris](https://github.com/jsonld-java/jsonld-java/issues/289) and 0.13.2 fixes some minor issues with the returned context.
I have updated also the `Ex_WriteJsonLD` example to clarify the different options dealing with context when converting from Rdf back to JSON-LD.
I'm not sure if Jena has some docs where it talks about all of that besides this example file in the repo, but probably they could be reviewed. Can someone point me to them?
> JENA-1967: Bumped JsonLD Java dependency; fixed tests

- jena-fuseki2/jena-fuseki-webapp/src/main/webapp/dataset.html
Jena already work with N-Quads and Trig serialization. This is also useful for dataset page on Fuseki Webpage.
> [JENA-1985] Adding TriG and N-Quads content-type in Fuseki2.

- jena-arq/Grammar/arq.jj
- jena-arq/Grammar/main.jj
- jena-arq/Grammar/sparql_11.jj
- jena-arq/src/main/java/org/apache/jena/riot/WebContent.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/E_Cast.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/NodeValue.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/nodevalue/XSDFuncOp.java
- jena-arq/src/main/java/org/apache/jena/sparql/function/CastXSD.java
- jena-arq/src/main/java/org/apache/jena/sparql/function/FunctionCastXSD.java
- jena-arq/src/main/java/org/apache/jena/sparql/function/StandardFunctions.java
- jena-arq/src/main/java/org/apache/jena/sparql/lang/ParserBase.java
- jena-arq/src/main/java/org/apache/jena/sparql/lang/arq/ARQParser.java
- jena-arq/src/main/java/org/apache/jena/sparql/lang/sparql_11/SPARQLParser11.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/TestCastXSD.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/TestXSDFuncOp.java
- jena-arq/testing/ARQ/Syntax/Syntax-ARQ/manifest.ttl
- jena-arq/testing/ARQ/Syntax/Syntax-ARQ/syntax-agg-expr-bad-01.arq
- jena-arq/testing/ARQ/Syntax/Syntax-ARQ/syntax-agg-expr-bad-02.arq
- jena-arq/testing/ARQ/Syntax/Syntax-ARQ/syntax-agg-expr-bad-03.arq
- jena-arq/testing/ARQ/Syntax/syn-arq.sh
- jena-arq/testing/ARQ/Syntax/syn-reification.sh
There is a new set of tests in the CG [w3c/rdf-tests](https://github.com/w3c/rdf-tests/) to cover XSD casting as defined in F&O 3.1.
JENA-1984 fixes problems encountered.
This PR includes 
JENA-1986: Error for nested aggregates
which was reported offline
> JENA-1984: Fixed to XSD casting

- jena-base/src/main/java/org/apache/jena/atlas/logging/LogCtlLog4j2.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/system/FusekiLogging.java
- jena-fuseki2/jena-fuseki-webapp/pom.xml
- jena-fuseki2/jena-fuseki-webapp/src/main/java/org/apache/jena/fuseki/webapp/FusekiServerEnvironmentInit.java
- jena-fuseki2/jena-fuseki-webapp/src/main/webapp/WEB-INF/web.xml
- jena-fuseki2/jena-fuseki-webapp/src/main/webapp/log4j2.properties
Use web.xml setup when running from a WAR file.
See [JENA-1989](https://issues.apache.org/jira/browse/JENA-1989) for more - external configuration of systemd is necessary as well because it will route stdout to an different place for Tomcat9 than for Tomcat8.
> JENA-1898: Log output for webapp

- jena-arq/src/main/java/org/apache/jena/riot/RDFDataMgr.java
- jena-arq/src/main/java/org/apache/jena/riot/RDFLanguages.java
- jena-arq/src/main/java/org/apache/jena/riot/system/stream/LocatorFile.java
- jena-base/src/main/java/org/apache/jena/atlas/io/IO.java
- jena-base/src/main/java/org/apache/jena/atlas/lib/IRILib.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/system/Upload.java
This fixes the problems with "file:".
Before passing to the OS, this has always been stripped and converted to an OS file name. There are other uses of filename handling code from Apache Commons IO, one of which `RDFLangauages.filenameToLang`, which takes a resource name (URI of filename) and uses the extension to guess the RDF syntax. It is used for file names and also URIs when there isn't content negotiation.
The fix, in IO.java, around line 100  (the rest of the PR is naming and cosmetic changes), is to extract the code from Apache Commons IO , remove the check for ":" as a trailing component of the filename ([NTFS ADS](https://en.wikipedia.org/wiki/NTFS#Alternate_data_streams_(ADS))) - windows uses ":" in two places, drive and ADS. This clashes with the use of URI scheme name, which …
> JENA-2003: Handle file URIs with URI scheme name

- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/CardinalityConstraint.java
- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/ClosedConstraint.java
- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/ConstraintComponentSPARQL.java
- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/ConstraintOp1.java
- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/ConstraintOpN.java
- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/ConstraintPairwise.java
- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/HasValueConstraint.java
- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/InConstraint.java
- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/JLogConstraint.java
- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/JViolationConstraint.java
- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/NodeKindConstraint.java
- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/PatternConstraint.java
- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/QualifiedValueShape.java
- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/SparqlConstraint.java
- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/StrMaxLengthConstraint.java
- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/StrMinLengthConstraint.java
- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/UniqueLangConstraint.java
- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/ValueRangeConstraint.java
As documented in https://issues.apache.org/jira/browse/JENA-2002, this commit adds public getters for accessing internal data in SHACL constraints.
> Add public getters to SHACL constraint implementations

- jena-arq/Grammar/arq.jj
- jena-arq/Grammar/main.jj
- jena-arq/Grammar/sparql_11.jj
- jena-arq/src/main/java/org/apache/jena/sparql/lang/ParserBase.java
- jena-arq/src/main/java/org/apache/jena/sparql/lang/arq/ARQParser.java
- jena-arq/src/main/java/org/apache/jena/sparql/lang/sparql_11/SPARQLParser11.java
- jena-arq/src/test/java/org/apache/jena/arq/junit/runners/AbstractRunnerOfTests.java
- jena-base/src/main/java/org/apache/jena/atlas/io/InStreamUTF8.java
- jena-cmds/src/main/java/riotcmd/utf8.java
Add `checkString` into the parsing process that makes sure a high-surrogate is followed by a low-surrogate.
> JENA-2012: Test for UTF-16 high-low surrogates pairs

- apache-jena/bin/tdbloader2index
The `$WORK` path is not surrounded by quotes. This leads to problems, if the path contains spaces.
Example:
```bash
tdbloader2 --loc="$HOME/a path that contains spaces/my-target-dir" "$HOME/Downloads/example.nt"
```
This leads to the following error:
```
/Users/niclasvaneyk/Code/apache-jena-3.17.0/bin/tdbloader2index: line 363: $WORK: ambiguous redirect
19:27:26 ERROR Failed during data phase
```
After applying the proposed changes everything works as expected.
> Fix unquoted path

- jena-core/pom.xml
- jena-elephas/jena-elephas-mapreduce/pom.xml
- jena-elephas/jena-elephas-mapreduce/src/test/java/org/apache/jena/hadoop/rdf/mapreduce/AbstractMapReduceTests.java
- jena-elephas/jena-elephas-mapreduce/src/test/java/org/apache/jena/hadoop/rdf/mapreduce/AbstractMapperTests.java
- jena-elephas/pom.xml
- jena-extras/jena-querybuilder/pom.xml
- jena-permissions/pom.xml
- pom.xml
Not an automatic dependabot upgrade. 
The artifact name has changed from `mockito-all` (stuck on v1) to `mockito-core` (v2, v3).
mockito-all seems to now have problem when used on Java16 (https://ci-builds.apache.org/job/Jena/job/Jena_JDK16/org.apache.jena$jena-core/18/testReport/ 03-Jan-2021 13:38:33)
This change seems to work (java8, java11) so hoping it works for Java16 as well.
> Update mockito(testing) to 3.6.28

- jena-text/src/main/java/org/apache/jena/query/text/analyzer/ConfigurableAnalyzer.java
This resolves the issue w/ StandardFilter when upgrading to Lucene 8.8.0. There were no test with dependencies on StandardFilter
> resolve JENA-2037 remove StandardFilter ref

- jena-arq/src/main/java/org/apache/jena/query/ARQ.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/jetty/JettyHttps.java
Other that his one change, which also works on 9.4.36, Fuseki runs with Jetty10.
> JENA-2053: Use SslContextFactory.Server 

- jena-core/src/main/java/org/apache/jena/irix/IRIProviderJDK.java
- jena-core/src/main/java/org/apache/jena/irix/IRIProviderJenaIRI.java
- jena-core/src/main/java/org/apache/jena/irix/IRIx.java
- jena-core/src/test/java/org/apache/jena/irix/AbstractTestIRIx.java
- jena-core/src/test/java/org/apache/jena/irix/JenaIRI.java
- jena-core/src/test/java/org/apache/jena/irix/TS_IRIx.java
- jena-core/src/test/java/org/apache/jena/irix/TestIRIx.java
- jena-core/src/test/java/org/apache/jena/irix/TestNormalize.java
- jena-core/src/test/java/org/apache/jena/irix/TestRFC3986.java
- jena-core/src/test/java/org/apache/jena/irix/TestRelative.java
- jena-core/src/test/java/org/apache/jena/irix/TestResolve.java
- jena-core/src/test/java/org/apache/jena/test/TestPackage.java
- jena-iri/src/main/java/org/apache/jena/iri/ViolationCodes.java
This PR adds a test suite for IRIx rather than relying on the provider to be correct.
It pins down the contract for IRIs in Jena.
> JENA-2031: More tests for IRIx

- .github/workflows/maven.yml
The  [commit](https://github.com/apache/jena/pull/928/commits/669ffcabc11ca85501e69cce383ded733b0d7d95)   contains [the last run](https://github.com/OyvindLGjesdal/jena/actions/runs/579527299) where the action behaves like I would expect, returning success for ubuntu, and failures (different failing tests) for macos and windows. There's a commit, removing branch `jena-2052` from branches, to only run the job on `main`.
> Jena-2052 run github action maven.yml also for windows server and macos

- .github/workflows/maven.yml
- jena-arq/src/test/java/org/apache/jena/sparql/api/TestQueryExecutionTimeout1.java
- jena-arq/src/test/java/org/apache/jena/sparql/api/TestQueryExecutionTimeout2.java
- jena-base/src/test/java/org/apache/jena/atlas/lib/TestAlarmClock.java
- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/sys/DatabaseOps.java
- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/sys/IOX.java
- jena-db/jena-tdb2/src/test/java/org/apache/jena/tdb2/sys/TestDatabaseOps.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/build/FusekiConfig.java
- jena-fuseki2/jena-fuseki-webapp/src/test/java/org/apache/jena/fuseki/TestAdmin.java
And some information gathering code for `TestDatabaseOps.compact_prefixes_3` (which only fails with an intermittent NPE in deterministic code).
> JENA-2060: Improve test robustness

- jena-arq/src/test/java/org/apache/jena/sparql/engine/http/TestService.java
This addresses an intermittent error that can occur on OS X and is likely in part linked to the usage of corporate VPN software.
The affected tests are updated to allow for a 3rd error that can occur on OS X.
> Fix tests that throw a different error under OS X

- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/FusekiServer.java
`FusekiServer::getPort()` returns actual port, if it was randomly selected from the free ports. However, this does not guarantee to return the HTTPS port as described in the Java Doc.
> JENA-2042 FusekiServer::getPort() returns actual port

- .github/workflows/maven_macos.yml
- .github/workflows/maven_windows.yml
- jena-arq/src/test/java/org/apache/jena/sparql/api/TestQueryExecutionTimeout2.java
Tweaking the GH workflows.
This PR is the current best I have managed to achieve.
The MacOS workflow does sometimes pass at quiet times without a test change but only sometimes and only quiet times (e.g before work, European time).
There is a test change - the MacOS environment seems to be heavily loaded and as a result some tests expecting timeouts are unstable. It seems that pauses of the test VM with no thread scheduled can be many seconds due to load.
Windows and MacOS workflows set to manual trigger (`workflow_dispatch`).
> JENA-2070: Split into separate github workflows

- jena-core/src/main/java/org/apache/jena/rdf/model/impl/AltImpl.java
- jena-core/src/main/java/org/apache/jena/rdf/model/impl/ContainerImpl.java
- jena-core/src/main/java/org/apache/jena/rdf/model/impl/SeqImpl.java
Changes are in AltImpl.setDefault(), ContainerImpl.add(),
ContainerImpl.contains(), SeqImpl.add(), and SeqImpl.indexOf()
This should fix JENA-2075 for ver 4.
> JENA-2075: Changed String.valueOf() to getModel().createTypeLiteral()

- jena-fuseki2/jena-fuseki-webapp/src/main/java/org/apache/jena/fuseki/authz/LocalhostFilter.java
Chrome browser appears to resolve localhost as IpV6 in the form [::1] which does not work as part of the `LocalhostFilter` and we get 403 forbidden
OS: Ubuntu 20.04.2 LTS
Browser: Chrome 89.0.4389.90
> Handle shortened IpV6 as resolved by chrome

- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/ctl/ActionCompact.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/server/FusekiVocab.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/FusekiServer.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/cmds/FusekiMain.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/cmds/ServerConfig.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestConfigFile.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestEmbeddedFuseki.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestFusekiMainCmd.java
- jena-fuseki2/jena-fuseki-main/testing/Config/server-tdb2.ttl
- jena-fuseki2/jena-fuseki-main/testing/FusekiEmbedded/tdb2-config.ttl
- jena-fuseki2/jena-fuseki-webapp/src/main/webapp/WEB-INF/web.xml
Compaction can be a very important feature. But, if you're using something like rdf-delta to run your fuseki server, you don't have any way to run compaction while the server is still running. This PR moves the `/$/compact/*` endpoint from the webapp into main so that it can be supplied even when the non-full version of Fuseki is being used.
> JENA-2081: add /$/compact/* endpoint to fuseki main

- jena-arq/src/main/java/org/apache/jena/riot/system/ParserProfileStd.java
- jena-core/src/test/java/org/apache/jena/irix/AbstractTestIRIx.java
PR #986 fixed the problem reported but it broke some test that run in "strict" mode ("strict" mode validates the IRIProvider, not the way Jena uses it). 
This PR runs the TS_IRIx tests in strict mode.
> JENA-2094: Run tests in strict environment

- jena-arq/src/main/java/org/apache/jena/rdfs/assembler/VocabRDFS.java
- jena-arq/src/main/java/org/apache/jena/riot/RDFParser.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/CollectorStreamRDF.java
- jena-arq/src/main/java/org/apache/jena/riot/system/Checker.java
- jena-arq/src/main/java/org/apache/jena/riot/system/ErrorHandlerFactory.java
- jena-arq/src/main/java/org/apache/jena/riot/system/ParserProfileStd.java
- jena-arq/src/test/java/org/apache/jena/arq/junit/manifest/Manifest.java
- jena-arq/src/test/java/org/apache/jena/arq/junit/riot/RiotSyntaxTest.java
- jena-arq/src/test/java/org/apache/jena/riot/lang/TestLangNTriples.java
- jena-arq/src/test/java/org/apache/jena/riot/lang/TestLangTurtle.java
- jena-arq/src/test/java/org/apache/jena/riot/system/CatchParserOutput.java
- jena-arq/src/test/java/org/apache/jena/riot/system/TestChecker.java
- jena-arq/src/test/java/org/apache/jena/riot/system/TestIRIxRIOT.java
- jena-base/src/main/java/org/apache/jena/atlas/lib/EscapeStr.java
- jena-base/src/main/java/org/apache/jena/atlas/lib/StrUtils.java
- jena-base/src/test/java/org/apache/jena/atlas/lib/TestStrUtils.java
- jena-core/src/main/java/org/apache/jena/irix/IRIProviderJenaIRI.java
- jena-core/src/main/java/org/apache/jena/irix/IRIs.java
- jena-core/src/main/java/org/apache/jena/irix/IRIxResolver.java
- jena-core/src/main/java/org/apache/jena/irix/RelativeIRIException.java
- jena-core/src/main/java/org/apache/jena/irix/SetupJenaIRI.java
- jena-core/src/test/java/org/apache/jena/irix/TestIRIx.java
- jena-core/src/test/java/org/apache/jena/irix/TestResolve.java
- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/sys/DatabaseOps.java
- jena-db/jena-tdb2/src/test/java/org/apache/jena/tdb2/sys/TestDatabaseOps.java
- jena-fuseki2/jena-fuseki-webapp/src/test/resources/log4j2.properties
JENA-2097 shows two things:
1. checking urn:uuid was broken (4.0.0 adds checking of UUIDs).
1. IRI problems should be warnings (parsing does not stop).
Only IRI syntax that is broken to the point where `<>` can't be matched or impossible characters (e.g. space) are used should be a parse-stop error as it was in jena 3.17.0, especially for N-Triples.
To this end, add a test suite `TestIRIxRIOT` that has test cases for all the situations, checking the numbers of errors and warning produced for the new IRIx abstraction use in RIOT parsing.
Relative IRIs are now a special case with their own exception `RelativeIRIException`. Some formats (N-Triples when not strict) accept them. Turtle always resolves them (and there is always a base) unless specific low-level setup is done when it can be a …
>  JENA-2097: Bad URIs are parser warnings

- jena-cmds/src/main/java/tdb2/tdbcompact.java
- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/DatabaseMgr.java
- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/sys/DatabaseOps.java
- jena-db/jena-tdb2/src/test/java/org/apache/jena/tdb2/sys/TestDatabaseOps.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/ctl/ActionCompact.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestConfigFile.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestFusekiMainCmd.java
- jena-fuseki2/jena-fuseki-main/testing/Config/server-tdb2_compact0.ttl
- jena-fuseki2/jena-fuseki-main/testing/Config/server-tdb2_compact1.ttl
Adds two things:
1. adds `--delete` option to `tdbcompact`
2. adds `deleteOld` parameter to `/$/compact` endpoint.
These options enable the deletion of the previous DB after compaction has successfully completed. The default behavior remains the same as it was previous to this PR (I.E. deletion does not take place).
> [JENA-2096] Added ability to delete old DB after compaction has completed successfully

- jena-arq/src/main/java/org/apache/jena/riot/system/RiotLib.java
- jena-arq/src/test/java/org/apache/jena/riot/system/TS_RiotSystem.java
- jena-arq/src/test/java/org/apache/jena/riot/system/TestRiotLib.java
With [Jena-1262](https://issues.apache.org/jira/browse/JENA-1262) the Turtle serialization is improved.
In this PR I've implemented the first section of the ticket, which requires the prefixes to be sorted and aligned.
Also, I've removed unused code and reformated the RiotLib.java file
The second part needs refinement, I will start a discussion within the ticket.
> JENA-1262: Sorting of prefixes in Turtle serializer

- jena-arq/src/main/java/org/apache/jena/sparql/engine/Rename.java
- jena-arq/src/test/java/org/apache/jena/sparql/algebra/optimize/TestVarRename.java
Fix for [JENA-2132](https://issues.apache.org/jira/browse/JENA-2132)
The NodeTransformers now check for NodeTriple arguments and apply themselves recursively in that case.
> JENA-2132 - Added RDFStar/NodeTriple handling to Rename.java

- jena-core/src/main/java/org/apache/jena/datatypes/DatatypeFormatException.java
This PR changes the class `DatatypeFormatException` in the following way:
* add constructors with cause parameter (I have a use case this would be helpful for)
* improve JavaDoc
All changes should be API and binary compatible.
> JENA-2142: Extend DatatypeFormatException

- jena-arq/pom.xml
- jena-arq/src/main/java/org/apache/jena/riot/Lang.java
- jena-arq/src/main/java/org/apache/jena/riot/RDFLanguages.java
- jena-arq/src/main/java/org/apache/jena/riot/RDFParserRegistry.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/LangJSONLD11.java
- jena-cmds/pom.xml
- jena-fuseki2/jena-fuseki-geosparql/pom.xml
- pom.xml
This PR contains a JSON-LD reader based on Titanium. Treat as experimental.
The linkage is minimal - it parses the JSON-LD 1.1 document, prints quads to bytes and reads the N-Quads bytes.
Better would be direct translation from the Titanium RDF abstraction to Jena - contributions welcome!
To use:
```
RDFparser.create.forceLang(Lang.JSONLD11)...
```
Unfortunately, the JSON-Processing API, jakarta.json-api, is licensed under EPL-2.0 (even just the API, let alone an implementation) so needs careful handling.
For now, add to the application dependencies:
```
<dependency>
<groupId>com.apicatalog</groupId>
<artifactId>titanium-json-ld</artifactId>
<version>1.1.0</version>
</dependency>
<dependency>
<groupId>org.glassfish</groupId>
<artifactId>jakarta.json</artifactId>
<version>2.0.0</version> …
```
> JENA-1948: Limited JSON-LD 1.1 Reader

- jena-shacl/src/main/java/org/apache/jena/shacl/compact/reader/ShaclcParseException.java
- jena-shacl/src/main/java/org/apache/jena/shacl/compact/writer/CompactOut.java
- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/NodeKindConstraint.java
- jena-shacl/src/test/files/local/shaclc-syntax/nodeParam-bad-01.shc
- jena-shacl/src/test/files/local/shaclc-syntax/nodeParams.shc
- jena-shacl/src/test/files/local/shaclc-syntax/propertyParams.shc
- jena-shacl/src/test/java/org/apache/jena/shacl/compact/TS_Compact.java
- jena-shacl/src/test/java/org/apache/jena/shacl/compact/TestCompactSyntax.java
This fixes JENA-2144 by always printing `nodeKind` in full form89 _i.e._ `nodeKind=sh:IRI`. The full form is legal in both property and node parameters.
> JENA-2144: Print nodeKind in long form

- apache-jena/dist/LICENSE
- jena-arq/pom.xml
- jena-fuseki2/apache-jena-fuseki/dist/LICENSE
- pom.xml
The is PR removes `<scope>provided</scope>` on `jakarta.json:jakarta.json-api` and `org.glassfish:jakarka.json`.
Both these are licensed as binaries under EPL 2.0 which is "category B" (may include in convenient binaries).
These are then in the `apache-jena` and `apache-jena-fuseki` convenient binaries.
Included LICENSE file in each has been updated.
> JENA-1948: Include Titanium and dependencies

- jena-arq/src/main/java/org/apache/jena/query/QueryExecution.java
- jena-arq/src/main/java/org/apache/jena/query/QueryExecutionBuilder.java
- jena-arq/src/main/java/org/apache/jena/query/QueryExecutionFactory.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/SPARQLQueryProcessor.java
[JENA-2125](https://issues.apache.org/jira/browse/JENA-2125) provides QueryExec for DatasetGraph level operation and QueryExecution for Dataset/Model level.
The current `QueryExecutionBuilder` works with `DatasetGraph` so it is misnamed and in the way of a proper builder for QueryExecution [JENA-2128](https://issues.apache.org/jira/browse/JENA-2128).
See also PR https://github.com/apache/jena/pull/1030.
> JENA-2125: Preparation to move misnamed QueryExecutionBuilder

- jena-core/src/main/java/org/apache/jena/vocabulary/ACL.java
- jena-core/src/main/java/org/apache/jena/vocabulary/WAC.java
https://www.w3.org/wiki/WebAccessControl
> JENA-2155: Add Web Access Control Ontology

- apache-jena-osgi/jena-osgi/pom.xml
The titanium JSON-LD project makes installing Jena in an OSGi runtime difficult. Since titanium does not seem to support OSGi deployment, this marks that dependency as optional
> Fix OSGi import for titanium dependency

- jena-arq/src/main/java/org/apache/jena/riot/tokens/TokenizerText.java
Checked with 
```
grep -E '(error|warning|fatal).*[+]' "$(find . -name TokenizerText.java)"
```
which finds only correct messages containing "U+"
> JENA-2188: Fix use of format in tokenizer messages

- jena-arq/src/main/java/org/apache/jena/sparql/expr/NodeValue.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/nodevalue/NodeValueDateTime.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/TestNodeValue.java
facet = collapse, which for the datatypes with value support, that means remove leading and trailing whitespace (there is no legal internal whitespace so the internal collapse does not apply).
> JENA-2197: Whitespace facet on XSD literals

- pom.xml
@afs :wave: 
After syncing the code today, and trying `mvn clean install -Pdev` it failed with
```bash
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13:09 min
[INFO] Finished at: 2021-11-22T18:13:57+13:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jena-examples: Could not resolve dependencies for project org.apache.jena:jena-examples:jar:4.3.0-SNAPSHOT: Could not find artifact org.apache.jena:jena-querybuilder:jar:4.3.0-SNAPSHOT in repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, …
```
> Fix running mvn with the dev profile

- jena-arq/src/main/java/org/apache/jena/http/HttpEnv.java
- jena-examples/src/main/java/arq/examples/auth/ExAuth01_RDFConnectionPW.java
- jena-examples/src/main/java/arq/examples/auth/ExAuth03_UpdateExecutionPW.java
[JENA-2203](https://issues.apache.org/jira/browse/JENA-2203) - Jena currently does not follow https -> http redirect (see Java `HttpClient.Redirect.NORMAL`). 
`purl.org` adds a https to http redirect.
See also [JENA-1263](https://issues.apache.org/jira/browse/JENA-1263). From that change, Jena, using Apache HttpClient, has been following all 303's including https to http.
> JENA-2203: Set default redirect to ALWAYS

- apache-jena/bin/tdb2.xloader
Fix for JENA_CP when it contains "*"
> JENA-2196: Script fix

- apache-jena/bin/tdb2.xloader
Hi, and thanks for the new version!
I'm looking forward to try out the new xloader, and noticed that I was unable to follow the url in the help text.
> fix documentation link for tdb-xloader documentation in cli-info

- jena-fuseki2/jena-fuseki-geosparql/pom.xml
- jena-geosparql/pom.xml
- pom.xml
This is "draft" initially.
It fixes the issue to make sure there is a fix available now.
It might be better to manage dependencies at the top level, partially or fully, or keep them specific to geosparql. Investigation needed.
> JENA-2222: Update of dependencies used in geosparql

- jena-jdbc/jena-jdbc-core/src/test/java/org/apache/jena/jdbc/connections/AbstractJenaConnectionTests.java
- jena-jdbc/jena-jdbc-core/src/test/java/org/apache/jena/jdbc/utils/TestJdbcUtils.java
- jena-jdbc/jena-jdbc-driver-remote/pom.xml
- jena-jdbc/jena-jdbc-driver-remote/src/main/java/org/apache/jena/jdbc/remote/http/HttpCaptureResponse.java
- jena-jdbc/jena-jdbc-driver-remote/src/main/java/org/apache/jena/jdbc/remote/http/HttpOp1.java
- jena-jdbc/jena-jdbc-driver-remote/src/main/java/org/apache/jena/jdbc/remote/http/HttpQuery.java
- jena-jdbc/jena-jdbc-driver-remote/src/main/java/org/apache/jena/jdbc/remote/http/HttpRequestTransformer.java
- jena-jdbc/jena-jdbc-driver-remote/src/main/java/org/apache/jena/jdbc/remote/http/HttpResponseHandler.java
- jena-jdbc/jena-jdbc-driver-remote/src/main/java/org/apache/jena/jdbc/remote/http/HttpResponseLib.java
- jena-jdbc/jena-jdbc-driver-remote/src/main/java/org/apache/jena/jdbc/remote/http/QueryEngineHTTP.java
- jena-jdbc/jena-jdbc-driver-remote/src/main/java/org/apache/jena/jdbc/remote/http/Service_AHC.java
- jena-jdbc/jena-jdbc-driver-remote/src/main/java/org/apache/jena/jdbc/remote/http/UpdateProcessRemote.java
- jena-jdbc/jena-jdbc-driver-remote/src/main/java/org/apache/jena/jdbc/remote/http/UpdateProcessRemoteBase.java
- jena-jdbc/jena-jdbc-driver-remote/src/main/java/org/apache/jena/jdbc/remote/statements/RemoteEndpointPreparedStatement.java
- jena-jdbc/jena-jdbc-driver-remote/src/main/java/org/apache/jena/jdbc/remote/statements/RemoteEndpointStatement.java
- jena-jdbc/jena-jdbc-driver-remote/src/test/java/org/apache/jena/jdbc/remote/FusekiJdbcTestServer.java
- jena-jdbc/jena-jdbc-driver-remote/src/test/java/org/apache/jena/jdbc/remote/connections/TestRemoteEndpointConnection.java
- jena-jdbc/jena-jdbc-driver-remote/src/test/java/org/apache/jena/jdbc/remote/connections/TestRemoteEndpointConnectionWithAuth.java
- jena-jdbc/jena-jdbc-driver-remote/src/test/java/org/apache/jena/jdbc/remote/connections/TestRemoteEndpointConnectionWithGraphUris.java
- jena-jdbc/jena-jdbc-driver-remote/src/test/java/org/apache/jena/jdbc/remote/connections/TestRemoteEndpointConnectionWithResultSetTypes.java
- jena-jdbc/jena-jdbc-driver-remote/src/test/java/org/apache/jena/jdbc/remote/results/AbstractRemoteEndpointResultSetTests.java
- jena-jdbc/jena-jdbc-driver-remote/src/test/java/org/apache/jena/jdbc/remote/results/TestRemoteEndpointResults.java
- jena-jdbc/jena-jdbc-driver-remote/src/test/java/org/apache/jena/jdbc/remote/results/TestRemoteEndpointResultsWithAuth.java
- jena-jdbc/jena-jdbc-driver-remote/src/test/java/org/apache/jena/jdbc/remote/results/TestRemoteEndpointResultsWithGraphUris.java
- jena-jdbc/jena-jdbc-driver-remote/src/test/java/org/apache/jena/jdbc/remote/results/TestRemoteEndpointResultsWithResultSetTypes.java
- jena-jdbc/jena-jdbc-driver-remote/src/test/java/org/apache/jena/jdbc/remote/utils/TestJdbcRemoteUtils.java
- pom.xml
This is part 1 of a 2 change. This PR copies the Apache HttpClient code used by jen-jdbc into that subsystem and puts in a compile-time dependency on Apache HttpClient into jena-jdbc-driver-remote.
The second part removes the legacy classes from jena-arq. See [JENA-2221](https://issues.apache.org/jira/browse/JENA-2221) and #1134.
> JENA-2220: Isolate Apache HTTP Client usage in jena-jdbc

- jena-arq/src/main/java/org/apache/jena/system/RDFStar.java
As a reader, I was briefly unsure whether this no-longer-hypothetical function `RDStar.encodeRDFStar` encoded RDF-star (as RDF) or encoded RDF as RDF-star.
This (crappy 'cause i've not looked for tests) PR changes the names to `RDFStar.encodeAsRDF` and `RDFStar.decodeFromRDF`.
> JENA-2237: s/encodeRDFStar/encodeAsRDF/

- jena-base/src/main/java/org/apache/jena/atlas/logging/LogCtlJUL.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/InitGeoSPARQL.java
Leaving the default setup of JUL leaves the JUL console as a handler of the root logger. 
The effect is getting two log message direct, from JUL and via SLF4J->Log4j2, for each logger call.
> JENA-2231: Fix - remove root logger (console)

- jena-arq/src/main/java/org/apache/jena/riot/RDFWriterRegistry.java
... so it executes after static fields are initialized
Since this not easy to test without starting a new JVM, a simple program demonstrates the problem:
```
import org.apache.jena.riot.RDFFormat;
import org.apache.jena.riot.RDFWriterRegistry;
import org.apache.jena.riot.WriterGraphRIOTFactory;
public class TestRDFWriterRegistry {
public static void main(String[] args) {
RDFWriterRegistry.register((RDFFormat) null, (WriterGraphRIOTFactory) null);
System.out.println("done");
}
}
```
Running the program will result in this exception:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
at TestRDFWriterRegistry.main(TestRDFWriterRegistry.java:27)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.put(Object, Object)" because …
```
> JENA-2243: Move RDFWriterRegistry static initialization block.

- pom.xml
Addresses [CVE-2021-22569](https://nvd.nist.gov/vuln/detail/CVE-2021-22569)
> JENA-2249: Update protobuf

- pom.xml
Of note:
Lucene: 8.10.1 -> 8.11.1
```
<requireMavenVersion>
<version>3.2.5</version>
</requireMavenVersion>
```
This was noted by the maven-version-plugin. It is just making explicit the minimum maven version. Maven version 3.2.5 was released 2017-10-18. Current maven is 3.8.4.
> JENA-2256: Upgrades

- pom.xml
The changes to generating the javadoc under java11 don't work.
This PR removes the fixup.
> JENA-2232: Undo the javadoc11 fixup for modules

- jena-core/src/main/java/org/apache/jena/graph/impl/LiteralLabelImpl.java
`LiteralLabelImpl`: forward `Throwable` instead of only the message to preserve causes.
> JENA-2258 LiteralLabelImpl: forward Throwabl, not only the message

- jena-fuseki2/jena-fuseki-ui/pom.xml
Would be better to go to v2.x (called Berry), but I couldn't figure out how to tell the Maven plug-in to use the 2.x version yet. 1.x is still maintained, so we should be fine.
Also adds `--frozen-lockfile`. It won't update `yarn.lock` anymore, and will fail in case the lock file gets updated/out of sync. Hopefully that should improve the UI build.
Tested with `mvn clean test install -Pdev`, no changes to `yarn.lock`, build passed OK.
> JENA-2260: Upgrade yarn from 0.16.x to 1.22.x

- jena-fuseki2/jena-fuseki-ui/src/services/fuseki.service.js
- jena-fuseki2/jena-fuseki-ui/tests/unit/services/fuseki.service.spec.js
Mea culpa. At least now we are able to add unit tests, so in theory this bug should not happen again (:crossed_fingers: ).
Bruno
> JENA-2271: Do not remove slashes from graph name (with tests)

- jena-fuseki2/jena-fuseki-ui/package.json
- jena-fuseki2/jena-fuseki-ui/yarn.lock
This PR puts the version numbers of into the "resolutions" section of package.json. This then satisfies the github security dependabot which does not seem to see that the versions actually used are via a different dependency route and are later (and fixed).
Downside: because the PR explicitly puts in the versions based checking node_modules/{ajv,nanoid}/package.json files, we are fixed to these even if the transitive dependencies move on.
An alternative course of action is that we instead simply mark the security alerts as not relevant - this then means we are not limited in the future by the named package.json/"resolutions" settings. Downside: all cloned repos get security alerts.
Which is best?
> Explicit choice of versions (ajv, nanoid)

- jena-fuseki2/jena-fuseki-ui/package.json
- jena-fuseki2/jena-fuseki-ui/yarn.lock
This PR fixes the build but we're back to needing to deal with a "moderate" security alert for ajv.
It is not clear the Fuseki UI is even affected by the issue in the indirect dependency.
```
├─┬ istanbul-instrumenter-loader@3.0.1
│ └─┬ schema-utils@0.3.0
│   └── ajv@5.5.2
```
Other uses of ajv are 6.12.6 or ajv 8.10.0.
> Don't control ajv version

- jena-arq/Grammar/Turtle/turtle.jj
- jena-arq/src/main/java/org/apache/jena/riot/RDFParser.java
- jena-arq/src/main/java/org/apache/jena/riot/RDFParserBuilder.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/extra/LangParserBase.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/extra/javacc/TurtleJavacc.java
- jena-arq/src/test/java/org/apache/jena/riot/TS_RiotGeneral.java
- jena-arq/src/test/java/org/apache/jena/riot/TestRDFParser.java
- jena-base/src/main/java/org/apache/jena/atlas/io/IOX.java
- jena-shacl/shaclc/shaclc.jj
- jena-shacl/src/main/java/org/apache/jena/shacl/compact/reader/parser/ShaclCompactParserJJ.java
Rename of `fixupPrefix` -- a different "fixup" is a feature of SPARQL parsing to get displayable queries when prefixes not provided (as is all too common on StackOverflow).
The rename means that several grammars needed rebuilding.
> JENA-2313: Initial prefix map - support for parsing Turtle/TriG fragments

- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/server/FusekiInfo.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/cmds/FusekiMain.java
- jena-fuseki2/jena-fuseki-webapp/src/main/java/org/apache/jena/fuseki/cmd/FusekiCmd.java
Resolves #1228.
The `--update` flag is not handled for `--file` datasets, which stil default to read-only.
Updates do not cause the file to be updated, only the in-memory database that the file was read into.
If you want persisted update, please use a TDB database.
> GH-1228: Process update flag for file datasets

- jena-geosparql/src/main/java/org/apache/jena/geosparql/implementation/index/GeometryLiteralIndex.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/implementation/index/GeometryTransformIndex.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/implementation/index/QueryRewriteIndex.java
Modification to use of concurrent maps to fetch and check result, or compute if absent, to remove potential race condition as highlighted in [JENA-2310](https://issues.apache.org/jira/browse/JENA-2310).
> [JENA-2310] NPE with geospatial property function due to query rewrite index issue

- jena-geosparql/src/main/java/org/apache/jena/geosparql/assembler/GeoAssembler.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/configuration/GeoSPARQLConfig.java
Fixes a bug where the precomputed geospatial index isn't loaded from file and thus not being registered to the dataset context.
> JENA-2289: fix to setup the precomputed geospatial index properly

- jena-text/src/main/java/org/apache/jena/query/text/TextIndexLucene.java
- jena-text/src/test/java/org/apache/jena/query/text/TestDatasetConcurrencyWithConfigurableAnalyzer.java
Text query parsing when using a ConfigurableAnalyzer is not
thread safe. Underlying issue may be with Lucene analyzers since
ConfigurableAnalyzer itself looks clean.
Proposed fix is just a brute force synchronization, since without a
clearer chracterisation it is hard detect all possibly unsafe
analyzer configurations
> Test case and proposed fix for jena-2319

- .github/workflows/maven.yml
- .github/workflows/maven_macos.yml
- .github/workflows/maven_windows.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>
> Set permissions for GitHub actions

- jena-cmds/src/main/java/shex/shex_parse.java
- jena-cmds/src/main/java/shex/shex_validate.java
Closes #1257 
Had a look at the shex validate code, and looks like that one is throwing `CmdException`'s, but not shex parse. Adapted the code to have the parse code similar to the validate code.
That should blow the exception up, and cause the command to exit with a code different than `0`.
> GH-1257: Throw a CmdException in shex commands

- jena-fuseki2/jena-fuseki-ui/package.json
- jena-fuseki2/jena-fuseki-ui/yarn.lock
- pom.xml
Apache POM to v26
In jena-fuseki-ui:
fortawesome/fontawesome-svg-core to ^6.1.1
fortawesome/free-solid-svg-icons to ^6.1.1
fortawesome/vue-fontawesome to ^2.0.6
triply/yasqe to ^4.2.23
triply/yasr to ^4.2.23
axios to ^0.26.1
> Updates (Apache POM , UI components)

- jena-arq/src/test/java/org/apache/jena/system/TS_System.java
- jena-arq/src/test/java/org/apache/jena/system/TestReadXML.java
- jena-arq/testing/xml/rdfxml-dtd-file.rdf
- jena-arq/testing/xml/rdfxml-dtd-http.rdf
- jena-arq/testing/xml/srx-dtd-file.srx
- jena-arq/testing/xml/srx-dtd-http.srx
- jena-arq/testing/xml/trix-dtd-file.trix
- jena-arq/testing/xml/trix-dtd-http.trix
- jena-cmds/testing/cmd/sg-test-config.rdf
- jena-core/src/main/java/org/apache/jena/util/JenaXMLInput.java
- jena-core/src/main/resources/ont-policy.rdf
- jena-core/src/test/resources/ont-policy-test.rdf
- jena-core/src/test/resources/ontology/list0.rdf
- jena-core/src/test/resources/ontology/list1.rdf
- jena-core/src/test/resources/ontology/list2.rdf
- jena-core/src/test/resources/ontology/list3.rdf
- jena-core/src/test/resources/ontology/list4.rdf
- jena-core/src/test/resources/ontology/list5.rdf
- jena-core/testing/ontology/list0.rdf
- jena-core/testing/ontology/list1.rdf
- jena-core/testing/ontology/list2.rdf
- jena-core/testing/ontology/list3.rdf
- jena-core/testing/ontology/list4.rdf
- jena-core/testing/ontology/list5.rdf
- jena-core/testing/ontology/relativenames.rdf
- jena-core/testing/ontology/testImport5/ont-policy.rdf
RDF/XML does not use them (SAX).
SPARQL XML Results don't use them (StAX) and inline entities are unknown.
> Ignore external DTDs

- jena-arq/src/main/java/org/apache/jena/riot/RDFFormat.java
- jena-arq/src/main/java/org/apache/jena/riot/RDFParserRegistry.java
- jena-arq/src/main/java/org/apache/jena/riot/RDFWriterRegistry.java
- jena-arq/src/main/java/org/apache/jena/riot/SysRIOT.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/extra/TurtleJCC.java
- jena-arq/src/main/java/org/apache/jena/riot/writer/JenaRDF2JSONLD10.java
- jena-arq/src/main/java/org/apache/jena/riot/writer/JsonLD10Writer.java
- jena-arq/src/main/java/org/apache/jena/riot/writer/JsonLD11Writer.java
- jena-arq/src/test/java/org/apache/jena/rdf_star/TestTurtleStarParse.java
- jena-arq/src/test/java/org/apache/jena/riot/TS_RiotGeneral.java
- jena-arq/src/test/java/org/apache/jena/riot/TestJsonLDReader.java
- jena-arq/src/test/java/org/apache/jena/riot/system/TestJsonLDReadWrite.java
- jena-arq/src/test/java/org/apache/jena/riot/writer/TestJsonLD10Writer.java
- jena-arq/src/test/java/org/apache/jena/riot/writer/TestRiotWriterGraph.java
- jena-examples/src/main/java/arq/examples/riot/Ex_WriteJsonLD.java
This is preparation for Jena to default to JSON-LD 1.1.
* Add a JSON-LD 1.1 (slightly) pretty writer.
* Refactor to make switching between JSON-LD 1.0 and JSON-LD 1.1 just a matter of change constants (separate contents for reading and writing).
> JENA-2153: Write pretty JSON-LD 1.1

- jena-core/src/main/java/org/apache/jena/reasoner/rulesys/Rule.java
- jena-core/src/test/java/org/apache/jena/reasoner/rulesys/test/TestRuleLoader.java
- jena-core/testing/reasoners/bugs/custom-builtins.rules
- jena-core/testing/reasoners/rules/include-test-not-found.rules
- jena-core/testing/reasoners/rules/ruleset1.rules
- jena-core/testing/reasoners/rules/ruleset2.rules
`Rule.rulesFromURL(String, BuiltinRegistry)` does not pass the `BuiltinRegistry` argument to `Rule.rulesParserFromReader()`. This means that a user-specified builtin registry cannot be used with rules that are loaded using `rulesFromURL()`. This seems like a bug, so I can create a corresponding GitHub or JIRA issue, but wanted to first present this pull request. This is a simple one-line fix to pass `registry` into `rulesParserFromReader()`, along with some additional unit tests and a minor reorganization for some of the `.rules` files.
If you checkout just the `TestRuleLoader.java` unit test file from this PR, you can see that the `load_from_file_with_custom_builtins()` test fails. After adding the change to `Rule.java`, the test passes.
> fix for custom builtins not being used when parsing rules

- jena-cmds/src/main/java/riotcmd/CmdLangParse.java
Command line riot was treating URLs as file names.
Restore previous behaviour.
> JENA-2241: Fix for reading URLs

- jena-arq/src/test/java/org/apache/jena/system/TestReadXML.java
Another java19 change emerging.
This PR makes a test cope with both current (Java11, Java17) behaviour and Java19 behaviour (we're still on19-EA so it could change back but it does look reasonable).
> Allow both forms of property access return value

- jena-examples/src/main/java/arq/examples/service/CustomServiceExecutor.java
Basic examples for custom service executors; adding them here with the intent of linking to them from jena-site.
> Examples for setting up custom service executors

- apache-jena/bin/jena
- apache-jena/bin/xload-data
- apache-jena/bin/xload-index
In #1185 the option to set the used java installation was added to most commands. For some commands this is still missing. Therefore we have added the missing ones.
> Add alternative java to more commands

- jena-arq/src/main/java/org/apache/jena/riot/system/AsyncParser.java
- jena-base/src/main/java/org/apache/jena/base/module/SubsystemRegistryServiceLoader.java
When researching some problems, I came across a couple of bits of logging code that seemed to want to log a stack trace, but put the exception in the string format var-args and the exception was then ignored.
> fix a few logging typos

- jena-arq/src/main/java/org/apache/jena/http/HttpLib.java
- jena-arq/src/main/java/org/apache/jena/http/auth/AuthChallenge.java
- jena-arq/src/main/java/org/apache/jena/http/auth/AuthCredentials.java
- jena-arq/src/main/java/org/apache/jena/http/auth/AuthDomain.java
- jena-arq/src/main/java/org/apache/jena/http/auth/AuthEnv.java
- jena-arq/src/main/java/org/apache/jena/http/auth/AuthException.java
- jena-arq/src/main/java/org/apache/jena/http/auth/AuthHeader.java
- jena-arq/src/main/java/org/apache/jena/http/auth/AuthLib.java
- jena-arq/src/main/java/org/apache/jena/http/auth/DigestLib.java
- jena-arq/src/main/java/org/apache/jena/http/auth/PasswordRecord.java
- jena-arq/src/test/java/org/apache/jena/http/auth/TestAuthHeaderParser.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/ActionExecLib.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/FusekiServer.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/auth/AuthBearerFilter.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/cmds/FusekiMain.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/sys/HttpLoggerFilter.java
- jena-integration-tests/src/test/java/org/apache/jena/http/AbstractTestAuthRemote.java
- jena-integration-tests/src/test/java/org/apache/jena/http/AuthBearerTestLib.java
- jena-integration-tests/src/test/java/org/apache/jena/http/TS_JenaHttp.java
- jena-integration-tests/src/test/java/org/apache/jena/http/TestAuthBasicRemote.java
- jena-integration-tests/src/test/java/org/apache/jena/http/TestAuthBearerRemote.java
- jena-integration-tests/src/test/java/org/apache/jena/test/conn/EnvTest.java
- jena-rdfconnection/src/main/java/org/apache/jena/rdfconnection/LibSec.java
This resolves GH-1292.
The PR covers mainly client-side with a thin interface for responding to bearer auth 401 challenges. The application must a function to provide the token. There is little a standard library can do. The server side has some preparation work but again there has to be custom code somewhere to validate tokens in the deployment environment. This is probaly better done with a Fuseki module - cusomt code for Fuseki main as released.
> GH-1292: Support for bearer auth

- jena-arq/src/main/java/org/apache/jena/sparql/service/ServiceExecutorRegistry.java
This PR adds a copy() method to ServiceExecutorRegistry in order to ease setting up local copies.
The copy method is mentioned in the jena-site PR https://github.com/apache/jena-site/pull/103
> Added copy() method to ServiceExecutorRegistry

- jena-arq/src/main/java/org/apache/jena/http/HttpLib.java
- jena-arq/src/main/java/org/apache/jena/http/auth/AuthEnv.java
- jena-arq/src/main/java/org/apache/jena/http/auth/AuthHeader.java
- jena-arq/src/main/java/org/apache/jena/http/auth/AuthLib.java
- jena-core/src/main/java/org/apache/jena/util/OneToManyMap.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/FusekiServer.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/auth/AuthBearerFilter.java
- jena-integration-tests/src/test/files/Fuseki/config-bearer.ttl
- jena-integration-tests/src/test/java/org/apache/jena/http/AuthBearerTestLib.java
- jena-integration-tests/src/test/java/org/apache/jena/http/TS_JenaHttp.java
- jena-integration-tests/src/test/java/org/apache/jena/http/TestAuthBearerRemote.java
- jena-integration-tests/src/test/java/org/apache/jena/http/TestAuthBearerServer.java
A mixture of fixes for problems encountered.
The servlet filter `AuthBearerFilter` is now improved from its previous state of being more for testing usage.
It is not a complete solution to support in Fuseki for bearer authentication. It is slanted towards support for machine-machine interactions. Token validation still has to be provided by the deployment. A Fuseki module could do this.
For example, for OpenID, there is a better solution which is to use the standard Jetty security handler.
> GH-1292: Improve server-side support for auth bearer tokens

- jena-arq/src/main/java/org/apache/jena/http/auth/AuthEnv.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestAuthQuery_JDK.java
- jena-fuseki2/jena-fuseki-webapp/src/test/java/org/apache/jena/fuseki/TestWebappAuthQuery_JDK.java
Unregistering password does not account for authModifiers that were created due to a prefix match for the password registration.
> Fix for auth test: clear auth env

- pom.xml
Appears to be left over from jena-osgi.
> GH-1357: Remove maven-bundle-plugin

- jena-base/src/main/java/org/apache/jena/atlas/io/IO.java
We just noticed missing data after loading a bzip2 file and realized that the flag was not set which caused the file to only be read partially.
> Enabled 'decompressConcatenated' for bzip2 to prevent partial reads of input

- pom.xml
Small `pom.xml` change to add some default goals to Maven. Every time I sync the code I run `mvn clean test install -Pdev`, but sometimes I mess up part of the command… so with this `mvn -Pdev` is enough. WDYT?
Thanks
----
----
> Add maven default goal to build

- jena-arq/src/main/java/org/apache/jena/sparql/algebra/optimize/TransformPropertyFunction.java
- jena-arq/src/test/java/org/apache/jena/sparql/pfunction/library/TS_PFunction.java
- jena-arq/src/test/java/org/apache/jena/sparql/pfunction/library/TestCustomPropertyFunction.java
GitHub issue resolved: #1381
Make the property function transformation on by default.
----
> GH-1381: Default to property function transform being enabled

- jena-arq/src/main/java/org/apache/jena/sparql/exec/QueryExecutionCompat.java
- jena-arq/src/test/java/org/apache/jena/sparql/exec/TestExecEnvironment.java
GitHub issue resolved #1393
Fixes an NPE by calling QueryExecutionAdapter.adapt; the underlying QueryExecutionCompat.get() now calls `execute()` to initialize its QueryExec instance.
> gh-1393 fix for QueryExecutionAdapter.adapt returning null

- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/FusekiServer.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/sys/FusekiModule.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/sys/FusekiModuleStep.java
Pass the FusekiServer builder into `FusekiModule.configured()`.
It was an oversight not to pass it in.
`configured` is called after the DataAccessPoint registry is built and before the server is built.
> JENA-2182: Pass builder into FusekiModule.configured()

- jena-arq/src/main/java/org/apache/jena/sparql/algebra/AlgebraGenerator.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/QueryCompare.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementExists.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementNotExists.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/ElementTransformCleanGroupsOfOne.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/QueryTransformOps.java
- jena-arq/src/test/java/org/apache/jena/sparql/algebra/TestOpAsQuery.java
Further investigation around GH-1397.
* Covers `{ OPTIONAL {  } }`.
* Fix for (ARQ extension) EXIST as graph pattern.
* More tests.
> GH-1397: Fixes and more coverage for OpAsQuery

- jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetGraphMap.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/AbstractDatasetGraphTests.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/DatasetGraphSimpleMem.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/TS_Core.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/TestDatasetGraphMap.java
GitHub issue resolved #1419 
- fix `DatasetGraphMap#clear`
- fix `DatasetGraphSimpleMem` (from tests): methods clear, def-graph#find
- add tests
----
----
> GH-1419: fix DatasetGraphMap#clear 

- jena-arq/src/main/java/org/apache/jena/sparql/engine/QueryIterator.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/main/OpExecutor.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/main/iterator/QueryIterService.java
- jena-arq/src/main/java/org/apache/jena/sparql/service/ServiceExecution.java
- jena-arq/src/main/java/org/apache/jena/sparql/service/ServiceExecutorRegistry.java
- jena-arq/src/main/java/org/apache/jena/sparql/service/bulk/ChainingServiceExecutorBulk.java
- jena-arq/src/main/java/org/apache/jena/sparql/service/bulk/ServiceExecutorBulk.java
- jena-arq/src/main/java/org/apache/jena/sparql/service/bulk/ServiceExecutorBulkOverRegistry.java
- jena-arq/src/main/java/org/apache/jena/sparql/service/bulk/ServiceExecutorBulkToSingle.java
- jena-arq/src/main/java/org/apache/jena/sparql/service/single/ChainingServiceExecutor.java
- jena-arq/src/main/java/org/apache/jena/sparql/service/single/ChainingServiceExecutorWrapper.java
- jena-arq/src/main/java/org/apache/jena/sparql/service/single/ServiceExecutor.java
- jena-arq/src/main/java/org/apache/jena/sparql/service/single/ServiceExecutorDecorator.java
- jena-arq/src/main/java/org/apache/jena/sparql/service/single/ServiceExecutorHttp.java
- jena-arq/src/main/java/org/apache/jena/sparql/service/single/ServiceExecutorOverRegistry.java
- jena-examples/src/main/java/arq/examples/service/CustomServiceExecutor.java
- jena-integration-tests/src/test/java/org/apache/jena/sparql/exec/http/TestService.java
- jena-integration-tests/src/test/java/org/apache/jena/test/service/TestCustomServiceExecutor.java
- jena-integration-tests/src/test/java/org/apache/jena/test/service/TestServiceExec.java
GitHub issue resolved #1387.
This fixes #1399.
Pull request Description: This PR adds the following changes to the custom service executor plugin system:
Improvements:
* **chaining** There is now `ChainingServiceExecutor` which allows for transparently forwarding a request to the next `ChainingServiceExecutor` instance in the registry. This way a custom service executor can modify the request and have it processed by the remainder of the chain.
* **bulk processing** The plugin system introduced with jena 4.5.0 only supports lookups with individual bindings. This PR adds support for plugins that want to process bindings in bulk. The main difference in the APIs is whether the `createExecution` method accepts a single `Binding` or a `QueryIterator`. There is now a …
> GH-1387 Improved custom service executor extension system

- jena-arq/src/main/java/org/apache/jena/sparql/function/FunctionRegistry.java
- jena-arq/src/main/java/org/apache/jena/sparql/pfunction/PropertyFunctionRegistry.java
- jena-arq/src/main/java/org/apache/jena/sparql/service/ServiceExecutorRegistry.java
- jena-arq/src/main/java/org/apache/jena/sparql/util/ContextUtils.java
- jena-arq/src/test/java/org/apache/jena/sparql/util/TS_Util.java
- jena-arq/src/test/java/org/apache/jena/sparql/util/TestContextUtils.java
Feature request: a convenient way to execute a query against graph in a dedicated context.
If we want to execute a query in isolated context with unique set of independent functions and p-functions, 
we will encounter some difficulties:
- the method `org.apache.jena.sparql.util.Context#copy` performs only shallow copying, not deep
- there is no straightforward way to pass the context while constructing `org.apache.jena.query.QueryExecution`
So we have to spend some time to find the proper way.
I think this can be simplified by adding two new helper-methods:
- `Context#copyWithFunctionRegistries(Context)` - the method to create a copy of `Context` with copied function and p-function registries
- `QueryExecutionFactory#create(Query, Graph, Context)` - the method to create `QueryExceution` …
> GH-1374: add copyWithRegisties Context helper method

- jena-arq/src/main/java/org/apache/jena/sparql/exec/http/GSP.java
- jena-base/src/main/java/org/apache/jena/atlas/io/IOX.java
- jena-base/src/main/java/org/apache/jena/atlas/logging/LogCtl.java
- jena-integration-tests/pom.xml
- jena-integration-tests/src/test/java/org/apache/jena/test/TC_Integration.java
- jena-integration-tests/src/test/java/org/apache/jena/test/integration/TestDatasetPrefixes.java
- jena-integration-tests/src/test/java/org/apache/jena/test/rdflink/TS_RDFLinkIntegration.java
- jena-integration-tests/src/test/java/org/apache/jena/test/rdflink/TestRDFLinkFuseki.java
- jena-integration-tests/src/test/java/org/apache/jena/test/rdflink/TestRDFLinkFusekiBinary.java
- jena-integration-tests/src/test/java/org/apache/jena/test/rdflink/TestRDFLinkHTTP.java
- jena-integration-tests/src/test/java/org/apache/jena/test/rdflink/TestRDFLinkLocalTDB.java
- jena-integration-tests/src/test/java/org/apache/jena/test/rdflink/TestRDFLinkLocalTDB2.java
- jena-integration-tests/src/test/java/org/apache/jena/test/text/TestTextTDB2Compact.java
- jena-integration-tests/testing/TextIndex/D1.ttl
- jena-integration-tests/testing/TextIndex/D2.ttl
- jena-integration-tests/testing/TextIndex/conf-tdb2-text.ttl
- jena-text/src/main/java/org/apache/jena/query/text/DatasetGraphText.java
- jena-text/src/main/java/org/apache/jena/query/text/TextDocProducerTriples.java
- jena-text/src/main/java/org/apache/jena/query/text/TextIndexDB.java
- jena-text/src/test/java/org/apache/jena/query/text/TestLuceneWithMultipleThreads.java
GitHub issue resolved #1432
jena-text integrates with TDB2 by adding a `TransactionalComponent` and becoming part of the TDB/DBOW transaction system.
The bug is that the added `TransactionalComponent` is in the storage database, not the switchable database. The storage database is rewritten and rebuilt by a compaction and the added component gets lost.
----
- [N/A] Documentation change and updates are provided for the [Apache Jena website](https://github.com/apache/jena-site/)
---- …
> GH-1432: Fix for adding text data after TDB2 compaction

- jena-integration-tests/src/test/java/org/apache/jena/sparql/exec/http/TestService.java
- jena-integration-tests/src/test/java/org/apache/jena/test/service/TestServiceExec.java
- jena-integration-tests/src/test/resources/log4j2.properties
Make the integration tests run without warning outputs.
The Release Manager does not detailed knowledge of each and every component in jena,. Expected logging should be suppressed so that a correct test run has no output.
----
> Silence integration tests

- jena-db/jena-dboe-trans-data/src/test/java/org/apache/jena/dboe/trans/recovery/TestRecovery.java
- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/TransactionalFactory.java
- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/ComponentGroup.java
- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/ComponentId.java
- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/TransactionCoordinator.java
- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/TransactionalComponentExternal.java
- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/TransactionalComponentLifecycle.java
- jena-db/jena-dboe-transaction/src/test/java/org/apache/jena/dboe/transaction/TestThreadingTransactions.java
- jena-db/jena-dboe-transaction/src/test/java/org/apache/jena/dboe/transaction/TestTransactionCoordinatorControl.java
- jena-db/jena-dboe-transaction/src/test/java/org/apache/jena/dboe/transaction/TestTxnLib2.java
- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/DatabaseMgr.java
- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/sys/DatabaseOps.java
- jena-db/jena-tdb2/src/test/java/org/apache/jena/tdb2/sys/TestDatabaseOps.java
- jena-integration-tests/src/test/java/org/apache/jena/test/text/TestTextTDB2Compact.java
- jena-text/src/main/java/org/apache/jena/query/text/DatasetGraphText.java
- jena-text/src/main/java/org/apache/jena/query/text/TextIndexDB.java
- jena-text/src/main/java/org/apache/jena/query/text/TextQueryPF.java
This is work mentioned in https://github.com/apache/jena/pull/1438#issuecomment-1183087146
The DBOE transaction system allows for transactional components from other sub-systems. An example of this is jena-text, where text index updates are coordinated with the RDF database updates when the database is TDB2.
The previous approach was specific to jena-text. This improves on that by making it a proper feature.
----
> Improve handling of external transactional components

- jena-fuseki2/examples/config-1-mem.ttl
- jena-fuseki2/jena-fuseki-webapp/src/main/java/org/apache/jena/fuseki/cmd/FusekiCmd.java
- jena-fuseki2/jena-fuseki-webapp/src/main/java/org/apache/jena/fuseki/cmd/WebappDSGSetup.java
- jena-fuseki2/jena-fuseki-webapp/src/main/java/org/apache/jena/fuseki/mgt/Template.java
- jena-fuseki2/jena-fuseki-webapp/src/main/java/org/apache/jena/fuseki/webapp/FusekiWebapp.java
- jena-fuseki2/jena-fuseki-webapp/src/main/resources/org/apache/jena/fuseki/webapp/templates/config-mem
- jena-fuseki2/jena-fuseki-webapp/src/main/resources/org/apache/jena/fuseki/webapp/templates/config-mem-readonly
- jena-fuseki2/jena-fuseki-webapp/src/main/resources/org/apache/jena/fuseki/webapp/templates/config-tdb
- jena-fuseki2/jena-fuseki-webapp/src/main/resources/org/apache/jena/fuseki/webapp/templates/config-tdb-dir
- jena-fuseki2/jena-fuseki-webapp/src/main/resources/org/apache/jena/fuseki/webapp/templates/config-tdb-dir-readonly
- jena-fuseki2/jena-fuseki-webapp/src/main/resources/org/apache/jena/fuseki/webapp/templates/config-tdb-mem-readonly
- jena-fuseki2/jena-fuseki-webapp/src/main/resources/org/apache/jena/fuseki/webapp/templates/config-tdb-readonly
- jena-fuseki2/jena-fuseki-webapp/src/main/resources/org/apache/jena/fuseki/webapp/templates/config-tdb2
- jena-fuseki2/jena-fuseki-webapp/src/main/resources/org/apache/jena/fuseki/webapp/templates/config-tdb2-dir
- jena-fuseki2/jena-fuseki-webapp/src/main/resources/org/apache/jena/fuseki/webapp/templates/config-tdb2-dir-readonly
- jena-fuseki2/jena-fuseki-webapp/src/main/resources/org/apache/jena/fuseki/webapp/templates/config-tdb2-mem-readonly
- jena-fuseki2/jena-fuseki-webapp/src/main/resources/org/apache/jena/fuseki/webapp/templates/config-tdb2-readonly
GitHub issue resolved #1440.
* Fix for #1440 
Read-only access when publishing a dataset.
* Convert creations template to new style endpoint descriptions. 
* Generalize template processing : existing templates still work.
* Review command line argument processing and organise logically.
----
> GH-1440: Fuseki/webapp. Command line argument processing.

- jena-arq/Grammar/arq.jj
- jena-arq/Grammar/main.jj
- jena-arq/Grammar/sparql_11.jj
- jena-arq/src/main/java/org/apache/jena/sparql/expr/E_BNode.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/E_Random.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/E_UUID.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/ExprLib.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/Unstable.java
- jena-arq/src/main/java/org/apache/jena/sparql/lang/QueryParserBase.java
- jena-arq/src/main/java/org/apache/jena/sparql/lang/arq/ARQParser.java
- jena-arq/src/main/java/org/apache/jena/sparql/lang/sparql_11/SPARQLParser11.java
- jena-arq/src/main/java/org/apache/jena/sparql/sse/builders/BuilderExpr.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/ExprFactory.java
- jena-extras/jena-querybuilder/src/test/java/org/apache/jena/arq/querybuilder/ExprFactoryTest.java
This resolves #1446.
This resolves #1447.
Improvement to the implementation of some SPARQL functions.
This touches the SPARQL parsers.
> Improvement of some SPARQL functions.

- jena-fuseki2/jena-fuseki-ui/package.json
- jena-fuseki2/jena-fuseki-ui/yarn.lock
Covers PR #1454.
Changes after running `yarn update` in jena-fuseki-ui, having removed explicit resolutions from package.json. These seem to be no longer necessary; later versions are installed.
----
----
> Update javascript dependencies

- jena-arq/src/main/java/org/apache/jena/sparql/core/mem/DatasetGraphInMemory.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/mem/TS_DatasetTxnMem.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/mem/TestDatasetGraphInMemoryPromote.java
- jena-arq/src/test/java/org/apache/jena/sparql/transaction/AbstractTestTransPromote.java
- jena-arq/src/test/java/org/apache/jena/sparql/transaction/AbstractTestTransactionLifecycle.java
- jena-base/src/main/java/org/apache/jena/atlas/lib/ThreadLib.java
- jena-db/jena-dboe-storage/src/main/java/org/apache/jena/dboe/storage/system/DatasetGraphTxnCtl.java
- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/Transaction.java
- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/TransactionCoordinator.java
- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/TransactionalBase.java
- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/TransactionalSystemControl.java
- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/store/DatasetGraphSwitchable.java
- jena-db/jena-tdb2/src/main/java/org/apache/jena/tdb2/sys/DatabaseOps.java
GitHub issue resolved #1252.
This fixes #1457.
This is a fix for  #1252 by having writers wait on a lock in the switchable container. Previous, they waited in the transaction coordinator, which is per storage, and changes during compaction. The issue #1252 is a bug when a write starts while compaction is going on. It was blocked (held on a lock) but inside the transaction coordinator for the storage about to be compacted.
#1457 found when some tests were restored.
----
---- …
> GH-1252: Hold up all possible write transactions while compacting.

- jena-geosparql/src/main/java/org/apache/jena/geosparql/geo/topological/GenericPropertyFunction.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/implementation/index/GeometryLiteralIndex.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/implementation/index/GeometryTransformIndex.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/implementation/index/QueryRewriteIndex.java
Replaced string concatenation for map key with test against separate string values to address issues highlighted in [JENA-2311](https://issues.apache.org/jira/browse/JENA-2311).
> [JENA-2311] query rewrite index does too expensive caching on geo literals

- pom.xml
GitHub issue resolved #1468
Exclude org.slf4j from jsonld-java and lib-thrift.
Exclude org.slf4j from libthrift.
Tested using another project where the dependency resolution via apache-jena-libs causes enforcer plugin alerts when using rule `<dependencyConvergence/>`.
----
----
> GH-1468: Improve exclusions due to overlapping dependencies

- jena-arq/src/main/java/org/apache/jena/sparql/algebra/OpVars.java
- jena-arq/src/main/java/org/apache/jena/sparql/algebra/OpWalker.java
- jena-arq/src/main/java/org/apache/jena/sparql/algebra/optimize/TransformFilterImplicitJoin.java
- jena-arq/src/main/java/org/apache/jena/sparql/algebra/optimize/TransformImplicitLeftJoin.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/VarExprList.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/ExprAggregator.java
- jena-arq/src/test/java/org/apache/jena/sparql/algebra/TestOpVars.java
Fix for JENA-2342: Processing groups was not considering that a group hides the variables of the inner pattern unless they are grouping variables and also that grouping can introduce variables via aggregation.
----
- [NA] Documentation change and updates are provided for the [Apache Jena website](https://github.com/apache/jena-site/)
> JENA-2342: Only consider group variables

- jena-extras/jena-serviceenhancer/src/main/java/org/apache/jena/sparql/service/enhancer/impl/ChainingServiceExecutorBulkServiceEnhancer.java
GitHub issue resolved #1484
A one liner fix for correctly passing on the effective cache mode.
> gh-1484: Fix for bulk requests using cache by default

- jena-core/src/main/java/org/apache/jena/rdfxml/xmlinput/JenaReader.java
- jena-core/src/test/java/org/apache/jena/rdf/model/test/TestReaders.java
A test that used to work, has started failing. Same code (same commit!) as a few days ago.
The RDF/XML reader code for "read URL" is not following redirects : either this is a java change or W3C change.
This PR:
1. Changes the test URL to "https".
2. Implement following redirects (because they code got written as part of diagnosing the problem).
> Follow redirect (jena-core legacy)

- jena-arq/src/main/java/org/apache/jena/atlas/json/io/parserjavacc/javacc/JavaCharStream.java
- jena-arq/src/main/java/org/apache/jena/sparql/lang/sparql_11/JavaCharStream.java
- jena-core/src/main/java/org/apache/jena/ttl/turtle/parser/JavaCharStream.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/UpdateBuilder.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/clauses/WhereClause.java
- pom.xml
Follow on from #1486  (Javadoc cleaning to get the build working for Java11, not cross-compiled)
This PR has fixes and settings so the javadoc:javadoc goal can be source=11.
Otherwise, we have an implicit restriction that the source code must be Java8 syntax. The case that bit me was private methods interfaces.
doclint is still set to "none" but with Java17 running maven, the setting "<doclint>syntax,html,reference" work.
There are still some warnings like:
```
[WARNING] javadoc: warning - The code being documented uses packages in the unnamed module, but the packages defined in https://jena.apache.org/documentation/javadoc/rdfconnection/ are in named modules.
```
but they don't stop the build and seem to bee Java17 to make them go away.
----
By submitting this …
> Javadoc : source=11

- jena-db/jena-dboe-storage/src/main/java/org/apache/jena/dboe/storage/system/DatasetGraphTxnCtl.java
GitHub issue resolved #1499
Exit non-exclusive mode properly. (Non-exclusive mode is normal mode for transactions, exclusive mode is used during compaction to switch storage databases.)
----
> GH-1499: Release non-exclusive mode at the end of transaction.

- jena-db/jena-dboe-index-test/src/main/java/org/apache/jena/dboe/index/test/TS_Index.java
- jena-db/jena-dboe-index-test/src/main/java/org/apache/jena/dboe/index/test/TestIndexMem.java
- jena-db/jena-dboe-index-test/src/main/java/org/apache/jena/dboe/index/testlib/AbstractTestIndex.java
- jena-db/jena-dboe-index-test/src/main/java/org/apache/jena/dboe/index/testlib/AbstractTestRangeIndex.java
- jena-db/jena-dboe-index-test/src/main/java/org/apache/jena/dboe/index/testlib/IndexMaker.java
- jena-db/jena-dboe-index-test/src/main/java/org/apache/jena/dboe/index/testlib/IndexTestGenerator.java
- jena-db/jena-dboe-index-test/src/main/java/org/apache/jena/dboe/index/testlib/IndexTestLib.java
- jena-db/jena-dboe-index-test/src/main/java/org/apache/jena/dboe/index/testlib/RangeIndexMaker.java
- jena-db/jena-dboe-trans-data/src/test/java/org/apache/jena/dboe/trans/bplustree/BPlusTreeMaker.java
- jena-db/jena-dboe-trans-data/src/test/java/org/apache/jena/dboe/trans/bplustree/TestBPlusTreeIndexNonTxn.java
- jena-db/jena-dboe-trans-data/src/test/java/org/apache/jena/dboe/trans/bplustree/TestBPlusTreeNonTxn.java
- jena-db/jena-dboe-trans-data/src/test/java/org/apache/jena/dboe/trans/bplustree/TestBPlusTreeTxn.java
- jena-db/jena-dboe-trans-data/src/test/java/org/apache/jena/dboe/trans/data/TestTransIndexMem.java
- jena-integration-tests/src/test/java/dboe/CmdTestBPlusTree.java
This PR fixes a package overlap issue in jena-dboe-index-test (the framework for testing indexes) that impacts javadoc production in the release build.
Why it has only just shown up is a mystery to me! There has been no changes here for quite some time.
----
> Rename package in jena-dboe-index-test

- jena-extras/jena-querybuilder/pom.xml
Javadoc in jena-querybuilder triggers issues with modules in some builds cases.
----
> Require source=8 for jena-querybuilder

- jena-db/jena-dboe-index-test/pom.xml
This fixes the javadoc production problem by skipping javadoc in `jena-dboe-index-test`.
The problem is that the javadoc tool fails with the error below, for Java11, not java17.
```
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.hamcrest.Matcher not found
```
----
> Skip javadoc production locally

- jena-fuseki2/jena-fuseki-webapp/src/main/webapp/WEB-INF/web.xml
GitHub issue resolved #1516 
disable chainPreflight in CrossOriginFilter. With chainPreflight disabled, the CORS Filter will create a fake reply to OPTIONS requests and cancel the filter chain, thus bypassing shiro and allowing authenticated CORS to succeed
----
----
> GH-1516: let CrossOriginFilter handle OPTIONS request

- jena-base/src/main/java/org/apache/jena/atlas/lib/Registry.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/Fuseki.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/server/FusekiCoreInfo.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/server/PlatformInfo.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/FusekiMainInfo.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/FusekiServer.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/cmds/FusekiMain.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/cmds/ServerConfig.java
- jena-fuseki2/jena-fuseki-webapp/src/main/java/org/apache/jena/fuseki/cmd/JettyFusekiWebapp.java
- jena-fuseki2/jena-fuseki-webapp/src/main/java/org/apache/jena/fuseki/webapp/FusekiServerListener.java
This is a small step to disentangling the Fuseki Main and Fuseki webapp java code.
The logging code used to print the server details used at the start of running a Fuseki server is now split into functions an application using Fuseki in embedded mode can use.
There are logging functions in library classes :
* PlatformInfo -- OS and Java details.
* FusekiCoreInfo -- dataset registry, common command line information
* FusekiMainInfo -- FusekiServer setup.
* FusekiServerListener (used by the webapp file packaging).
----
> Rework Fuseki configuration information logging

- jena-arq/src/main/java/org/apache/jena/riot/system/AsyncParser.java
- jena-arq/src/main/java/org/apache/jena/riot/system/AsyncParserBuilder.java
- jena-arq/src/main/java/org/apache/jena/riot/system/EltStreamRDF.java
- jena-arq/src/main/java/org/apache/jena/riot/system/EltStreamRDFType.java
- jena-arq/src/test/java/org/apache/jena/riot/system/TestAsyncParser.java
- jena-base/src/main/java/org/apache/jena/atlas/iterator/IteratorFlatMap.java
GitHub issue resolved #1477
The API changes to AsyncParser are intended to be completely backwards-compatible.
I added a couple of additional tests that check the count of JVM threads and consumed bytes.
Overall the PR is ready for feedback such as whether the proposed changes are acceptable in the first place.
I also tested the integrating of this PR into our Spark setup to do the final real-world testing and and all is green.
I'll do a bit more experiments because it's just too easy to overlook some corner cases when fiddling with async + cancellation, but overall it looks good to me.
An example for a non-trivial setup now looks like:
```java
public class MyHadoopRecordReader {
//  (Various logic)
public Stream<Triple> parse(InputStream in) {
return AsyncParser.of(in, lang, baseIri) …
```
> GH-1477: Improved AsyncParser

- jena-core/src/main/java/org/apache/jena/graph/impl/GraphBase.java
GitHub issue resolved #1548 
Defined GraphBase.isEmpty() in terms of !find().hasNext();
----
----
> GH-1548: GraphBase.isEmpty() no longer iterates all data.

- jena-arq/src/main/java/org/apache/jena/riot/tokens/TokenizerText.java
- jena-arq/src/test/java/org/apache/jena/riot/tokens/TestTokenizer.java
GitHub issue resolved #1551
After signalling an error because of a tab character, execute break not, "return null".
----
> GH-1551: IRI with tab - don't return null after error

- jena-arq/src/main/java/org/apache/jena/sparql/core/Prologue.java
GitHub issue resolved #1498 
Pull request Description: Removed a few lines of seemingly redundant logic from Prologue that implementations of PrefixMapping will handle anyway.
> GH-1498 Prologue.setPrefix now simply delegates to PrefixMapping

- jena-tdb2/src/main/java/org/apache/jena/tdb2/params/StoreParamsCodec.java
This is a fix to commit #db23fbed 
The changes meant 4.6.1 and before could not read a 4.7.0 created database (i.e create-new, read-old failed).
> Don't write StoreParams label (for previous versions)

- jena-fuseki2/jena-fuseki-ui/package.json
- jena-fuseki2/jena-fuseki-ui/yarn.lock
This PR updates webpack loader-utils to v1.4.1 for the fix 
https://github.com/webpack/loader-utils/pull/220
in response to
https://github.com/github/advisory-database/pull/805
This PR is instead of PR#1609 which updates the generated yarn.lock file. This PR updates package.json and then regerates yarn.lock with `yarn install`. It includes various incremental updates that rerunning `yarn install` decided to do.
----
> Fixes prototype pollution issue in webpack loader-utils

- jena-arq/src/main/java/org/apache/jena/sparql/function/CastXSD.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/TestCastXSD.java
GitHub discussion: #1617
When casting xsd:boolean to a derived type of xsd:integer (xsd:int etc), the cast was returning a xsd:integer, not downcasting to  the derived type.
----
----
> GH-1617: Cast boolean to derived type of integer

- jena-fuseki2/jena-fuseki-ui/package.json
- jena-fuseki2/jena-fuseki-ui/yarn.lock
This resolves #1621.
Replaces #1621 from dependabot.
* Update loader-utils override in package.json to `"^1.4.2".
* Pick up several incremental version updates by rebuilding yarn.lock.
----
> Bump loader-utils from 1.4.1 to 1.4.2. Rebuild yarn.lock

- jena-rdfconnection/src/main/java/org/apache/jena/rdflink/RDFLinkHTTP.java
GitHub issue resolved #1626
Minor correction.
Both Accept and Content-type are being set when only one is needed.
----
> GH-1626: Only set input or output headers as necessary

- jena-arq/src/main/java/org/apache/jena/query/ARQ.java
- jena-arq/src/main/java/org/apache/jena/sparql/algebra/optimize/OptimizerStd.java
- jena-arq/src/main/java/org/apache/jena/sparql/algebra/optimize/TransformMergeBGPs.java
- jena-arq/src/main/java/org/apache/jena/sparql/algebra/optimize/TransformPathFlattenAlgebra.java
- jena-arq/src/main/java/org/apache/jena/sparql/path/PathCompiler.java
- jena-arq/src/test/java/org/apache/jena/sparql/algebra/optimize/TestTransformPathFlatten.java
Intended as a less invasive first step related to #1616
Adds a new ARQ symbol `optPathFlattenExtended` that allows enabling more comprehensive path flattened transform via existing code `TransformPathFlatternStd`.  When enabled this is used in preference to the existing simpler path flattening transform.
This remains disabled by default as it can generate algebra structures that are less performant for the general case.  However users might have use cases that benefit from this so this now allows opting into it without needing deeper modification of ARQs optimiser.
----
By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's …
> Allow toggling extended path flattening on

- jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIter.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIterExtendByVar.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIterRepeatApply.java
- jena-arq/src/main/java/org/apache/jena/sparql/path/PathLib.java
- jena-arq/src/main/java/org/apache/jena/sparql/util/graph/GraphUtils.java
Issue improved: GH-1614
- the GraphUtils.allNodes used in the worst case determineUngroundedStartingSet was previously computing the contents of the whole data set. this has two drawbacks, (1) not lazy (2) not easy to abort, i.e queryTimeout was not respected
changed it to Iter.distinct (unfortunately that means in worst case it will still require to load everything into memory)
- the `PathLib.execUngroundedPath` and `execUngroundedPathSameVar` were both consuming the iterator fully while creating new QueryIterConcats. Drawbacks are the same as above, additionally LIMIT could not be pushed down. Changed it to be lazy instead
co-authored with @LorenzBuehmann
----
By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms …
> calculate ungrounded path starting set lazily

- jena-fuseki2/jena-fuseki-ui/package.json
- jena-fuseki2/jena-fuseki-ui/pom.xml
- jena-fuseki2/jena-fuseki-ui/src/services/mock/json-server.js
- jena-fuseki2/jena-fuseki-ui/vue.config.js
GitHub issue resolved #1622 
The `PORT` env var is used by Vue dev server. I only defined a new env var `FUSEKI_PORT`. The default values are the same, `8080` and `3030`.
In `pom.xml` for the Jena Fuseki UI module a Maven plug-in is used to allocate two network ports (it will search two free) and define Maven properties. In the Maven Frontend plug-in, these environment variables are then used to define `PORT` and `FUSEKI_PORT`.
I tested by starting `python3 -m http.server 3030` in one terminal, `watch -n 2 netstat -tlnp` in another, and then running `mvn test` in the Jena Fuseki UI module folder.
----
By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the …
> [GH-1622] Make the Jena Fuseki UI and Vue ports dynamic for the e2e tests

- jena-arq/src/main/java/org/apache/jena/sparql/algebra/optimize/TransformPathFlattenAlgebra.java
- jena-arq/src/main/java/org/apache/jena/sparql/path/PathCompiler.java
- jena-arq/src/test/java/org/apache/jena/sparql/algebra/optimize/TestTransformPathFlatten.java
Expands the path flattening test coverage so that all tests cover both the default and the algebra based transforms.  Also makes some additional fixes to both transforms for parity in a couple of areas:
- Sequence transforms place the grounded portion of the path first in the sequence
- Default transform now explicitly errors on invalid `:p{N,M}` forms (e.g. `:p{4,2}`) instead of generating the wrong algebra
Provides more testing around the path transformation aspect of #1629
----
---- …
> Further path flattening test coverage

- jena-core/src/main/java/org/apache/jena/ontology/OntClass.java
- jena-core/src/main/java/org/apache/jena/ontology/OntProperty.java
- jena-core/src/main/java/org/apache/jena/ontology/impl/OntPropertyImpl.java
GitHub issue resolved #1661
I was adding a new `../`, replacing `how-tos` by `notes`... when I found in another place javadocs being linked with the `/path/to/file.html` link.
Applied that to the places the user reported in the mailing list, then did a quick search with Eclipse and replaced the other ones I could find :+1: 
----
----
> [GH-1661] Fix javadocs links

- jena-arq/src/main/java/org/apache/jena/riot/RDFParserRegistry.java
- jena-arq/src/main/java/org/apache/jena/riot/resultset/ResultSetReaderRegistry.java
GitHub issue resolved #1676
New registry methods that return registered triple/quad/result set languages.
----
----
> GH-1676: Helper methods for registered language retrieval

- jena-extras/jena-serviceenhancer/src/test/java/org/apache/jena/sparql/service/enhancer/assembler/TestServiceEnhancerDatasetAssembler.java
GH-1686: fix recursive delete on macos for service enhancer TestServiceEnhancerDatasetAssembler test
Signed-off-by: Phillip Ross <phillip.w.g.ross@gmail.com>
GitHub issue resolved #1686 
Pull request Description: Modifies post-test cleanup with recursive temp dir delete using standard Java NIO2 code.
----
----
> GH-1686: fix recursive delete on macos for service enhancer TestServiceEnhancerDatasetAssembler test

- jena-extras/jena-serviceenhancer/src/main/java/org/apache/jena/sparql/service/enhancer/impl/OpServiceInfo.java
- jena-extras/jena-serviceenhancer/src/main/java/org/apache/jena/sparql/service/enhancer/impl/QueryIterServiceBulk.java
- jena-extras/jena-serviceenhancer/src/main/java/org/apache/jena/sparql/service/enhancer/impl/RequestExecutor.java
- jena-extras/jena-serviceenhancer/src/main/java/org/apache/jena/sparql/service/enhancer/impl/util/VarScopeUtils.java
- jena-extras/jena-serviceenhancer/src/test/java/org/apache/jena/sparql/service/enhancer/impl/TestServiceEnhancerMisc.java
GitHub issue resolved #1688
Pull request Description: Fixes registration of an empty iterator in case a cache hit reveals an empty result set.
----
- ~~[ ] Documentation change and updates are provided for the [Apache Jena website](https://github.com/apache/jena-site/)~~
----
> GH-1688 Fix possible incomplete results with service enhaner caching + bulk

- jena-fuseki2/jena-fuseki-core/pom.xml
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/FusekiFilter.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/UploadRDF.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/system/DataUploader.java
- jena-fuseki2/jena-fuseki-webapp/src/main/webapp/META-INF/context.xml
- pom.xml
GitHub issue resolved #1643
See #1643
Tested for Jetty 10.
It uses Servlet API 3.0 which Tomcat has supported since version 7.
This PR removes the `commons-fileupload` dependency which is no longer used. 
https://issues.apache.org/jira/browse/FILEUPLOAD-309
----
> GH-1643: Replace commons-fileload

- jena-fuseki2/jena-fuseki-ui/src/views/dataset/Query.vue
- jena-fuseki2/jena-fuseki-ui/tests/e2e/specs/query.cy.js
GitHub issue resolved #1693
a tiny Quality of Live improvement, enable resizeable in the fusekiUI Query editor. That way you can (maybe you still should not!) also view larger queries
test written by @kinow
----
----
> GH-1693: Resizeable query editor

- jena-fuseki2/jena-fuseki-ui/package.json
- jena-fuseki2/jena-fuseki-ui/yarn.lock
This should replace PR #1712.
This PR adds an explicit dependency on `json5` ... the change in `package.json`.
Recreating `yarn.lock` has picked up many other dependencies - all minor or incremental version updates.
----
> Update json5 from 1.0.1 to 1.0.2

- jena-arq/src/main/java/org/apache/jena/sparql/expr/nodevalue/XSDDuration.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/nodevalue/XSDFuncOp.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/TestFunctions.java
- jena-arq/src/test/java/org/apache/jena/sparql/function/library/TestFnFunctionsDateTimeDuration.java
Another use of the JVM default timezone. This time in `TestFnFunctionsDateTimeDuration`.
----
> GH-1713: Use ARQ timezone for adjust

- pom.xml
There are 1 security vulnerabilities found in org.apache.shiro:shiro-web 1.10.1
- [CVE-2023-22602](https://www.oscs1024.com/hd/CVE-2023-22602)
Upgrade org.apache.shiro:shiro-web from 1.10.1 to 1.11.0 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
> fix(sec): upgrade org.apache.shiro:shiro-web to 1.11.0

- jena-core/src/main/java/org/apache/jena/graph/compose/Delta.java
GitHub issue resolved #1751
Delta Graphs: Fixed performance issue due to creating a set of all deleted triples in `graphBasedFind(Triple t)` by directly checking membership of the triple in the deletions graph.
----
----
> GH-1751: Performance improvement for deltas with many deletions

- jena-fuseki2/jena-fuseki-ui/src/utils/query.js
- jena-fuseki2/jena-fuseki-ui/src/views/dataset/Query.vue
- jena-fuseki2/jena-fuseki-ui/tests/unit/components/serverstatus.vue.spec.js
- jena-fuseki2/jena-fuseki-ui/tests/unit/utils/query.spec.js
GitHub issue resolved #1745
Pull request Description: 
Fix sharing of query string containing `+` with the fuseki yasqe UI
@kinow maybe you can write a test for this?
to test it manually:
- put `+++++` in a query
- click on the share button inside the query editor
- paste that link in a new browser window
- with the bug, the query editor only contains `     ` instead of `+++++`
----
----
> GH-1745: fix plus sharing

- jena-fuseki2/jena-fuseki-ui/pom.xml
Temporary fix so the build overall does not fail is the e2e test fail.
e2e tests fail on CI with no X server. The failure is very noticeably logged.
----
> Log test failure in test:e2e but not fail whole build

- jena-core/src/main/java/org/apache/jena/ontology/impl/OntResourceImpl.java
- jena-core/src/main/java/org/apache/jena/rdf/model/impl/ResourceImpl.java
GitHub issue resolved #1768
`ResourceImpl.inModel` was not considering all the kinds of RDF term under Resource. It was blank nodes and URIs, now it include statements (for RDF-star quoted triples).
There were a few other places where the introduction of a new term type under `Resource` wasn't being handled either.
----
> GH-1768: Include statement-as-resource cases

- jena-db/jena-dboe-trans-data/src/main/java/org/apache/jena/dboe/trans/bplustree/BPTreeDistinctKeyPrefixIterator.java
- jena-db/jena-dboe-trans-data/src/main/java/org/apache/jena/dboe/trans/bplustree/BPlusTree.java
- jena-db/jena-dboe-trans-data/src/test/java/org/apache/jena/dboe/trans/bplustree/TestBPTreeDistinctKeys.java
- jena-db/jena-dboe-trans-data/src/test/java/org/apache/jena/dboe/trans/bplustree/TestBPTreeModes.java
- jena-tdb1/src/main/java/org/apache/jena/tdb/store/DatasetGraphTDB.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/solver/SolverLibTDB.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/store/DatasetGraphTDB.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/store/tupletable/TupleTable.java
- jena-tdb2/src/test/java/org/apache/jena/tdb2/store/tupletable/TestTupleTable.java
Adds a new `BPTreeDistinctKeyPrefixIterator` that allows iterating only records which are considered distinct based on a portion of their key.  It is effectively a skip scan based iterator that can avoid reading portions of the B+Tree where all records share the same key prefix.  This is used to improve performance of `DatasetGraphTDB.listGraphNodes()` and `SolverLibTDB.graphNames()`, in some cases dramatically so.
Used a couple of different test scenarios with calling `listGraphNodes()`:
- 100k named graphs comprising a total of 125 million quads
- On 4.6.1 this takes an average of 21,480 milliseconds
- With this patch this is reduced to 18,235 milliseconds
- 10 named graphs comprising a total of 177 million quads
- On 4.6.1 this takes an average of 27,856 milliseconds 
- With the …
> Use a skip scan based iterator for listing graph names in TDB2 (GH-1639)

- jena-examples/src/main/java/arq/examples/riot/ExRIOT_RDFXML_WriteProperties.java
The license header of `ExRIOT_RDFXML_WriteProperties.java` was broken.
> Fix broken header

- jena-base/src/main/java/org/apache/jena/atlas/lib/ByteBufferLib.java
CPU profiling of a brand new installation of jena-fuseki shows that ~75% of the time spent by `s-put` (when ingesting Turtle tuples via SPARQL) relates to the execution of `ByteBufferLib.bbcopy2()` -- often as part of B+tree operations such as `BPTreeNode.internalDelete()`.
`bbcopy2()` and `bbcopy1()` perform data copy from a source ByteBuffer to a destination ByteBuffer by reading/writing one byte at a time, which is not very efficient. In addition, `bbcopy1()` makes a poor use of data cache prefetches, as it iterates the ByteBuffers in reverse order.
This commit replaces the implementation of these two functions by one that reads the input data in bulk mode into a dynamically allocated byte array and then writes its contents to the destination buffer using a bulk `put()` operation. The …
> ByteBufferLib, RecordBuffer: use bulk get/put APIs

- jena-fuseki2/jena-fuseki-ui/cypress.config.js
- jena-fuseki2/jena-fuseki-ui/package.json
- jena-fuseki2/jena-fuseki-ui/src/services/fuseki.service.js
- jena-fuseki2/jena-fuseki-ui/src/services/mock/json-server.js
- jena-fuseki2/jena-fuseki-ui/src/views/dataset/Edit.vue
- jena-fuseki2/jena-fuseki-ui/tests/e2e/specs/datasets.cy.js
- jena-fuseki2/jena-fuseki-ui/tests/e2e/specs/query.cy.js
- jena-fuseki2/jena-fuseki-ui/tests/unit/services/fuseki.service.spec.js
- jena-fuseki2/jena-fuseki-ui/vite.config.js
GitHub issue resolved #1679
I found that the "edit" tab of Fuseki-UI would not allow me to edit my dataset when there is only e.g.
```
fuseki:endpoint [ fuseki:name "data" ; fuseki:operation fuseki:gsp-rw ; ]  ;
```
this patch seems to fix it
----
----
> edit not working on non root gsp-rw endpoint

- jena-base/src/main/java/org/apache/jena/atlas/lib/ByteBufferLib.java
- jena-tdb1/src/test/java/org/apache/jena/tdb/store/nodetable/TestNodec.java
This PR keeps the code (unused) for byte buffer copying that was replaces by #1800.
The original code was originally (a significant number of years ago) faster. Now it isn't, at least on the conventional architectures used for timing #1800. The JVM improves, hardware changes. 
* Add comments in ByteBufferLib
* Rename ByteBufferLib.duplicate as ByteBufferLib.copyOf
----
> GH-1803: Keep the old code for byte buffer copy

- jena-base/src/main/java/org/apache/jena/atlas/logging/LogCtl.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/system/FusekiLogging.java
Commit daa64b1a81 (2023-03-29) in PR #1818 broke the Fuseki logging setup. The test suite has started printing logging where it used not to. The problem would probably show up for users using embedded Fuseki if this is not fixed.
This PR fixes the problem, and makes the behaviour the same as 4.7.0.
----
> Fix conflict between library and Fuseki logging setup

- jena-arq/src/main/java/org/apache/jena/sparql/function/scripting/ScriptFunction.java
Suggestion to automatically enable EcmaScript 6 when using Nashorn JS Engine (e.g. for Licence reasons)
Note: Graal enables ES12 already by default
----
----
> Automatically enable Javascript ES6 with Nashorn

- .github/workflows/maven.yml
- .github/workflows/maven_macos.yml
- .github/workflows/maven_windows.yml
- jena-fuseki2/jena-fuseki-geosparql/src/test/java/org/apache/jena/fuseki/geosparql/MainTest.java
- jena-fuseki2/jena-fuseki-geosparql/src/test/java/org/apache/jena/fuseki/geosparql/TDB2Test.java
- jena-fuseki2/jena-fuseki-geosparql/src/test/java/org/apache/jena/fuseki/geosparql/TDBTest.java
- jena-fuseki2/jena-fuseki-webapp/src/test/java/org/apache/jena/fuseki/TestAdminAPI.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/InitGeoSPARQL.java
- jena-tdb1/src/main/java/org/apache/jena/tdb/sys/ProcessUtils.java
- jena-tdb1/src/main/java/org/apache/jena/tdb/sys/SystemTDB.java
- jena-tdb1/src/test/java/org/apache/jena/tdb/ConfigTest.java
The key revert:
[Revert "Use Sys.isWindows"](https://github.com/apache/jena/commit/c0cdb5a51f2a2883e511649837de5ba4db797007) 
Update works to use Java 17 (compiling for java11); also do a local install, not just verify
[Workflows to use Java17](https://github.com/apache/jena/commit/e877fa2c95ba9f01fc9d7f89114377ea8d6f8ac8)
jena-fuseki-geosparql test fix.:
[Test tear down to ignore server shutdown exceptions](https://github.com/apache/jena/commit/5a4e0a0bd5645038a6f8c8d3c0ebeb89df9e3163)
Code tidy - done as part of getting geoSPARQL sorted (wasn't necessary but done now):
[Static init() function](https://github.com/apache/jena/commit/1481936f05595ae6422e5c0160d6e52e63dd81b0)
----
By submitting this pull request, I acknowledge that I am making a contribution to the …
> Fixes for running tests

- jena-fuseki2/jena-fuseki-ui/cypress.config.js
- jena-fuseki2/jena-fuseki-ui/src/router/index.js
- jena-fuseki2/jena-fuseki-ui/tests/e2e/support/index.js
- jena-fuseki2/jena-fuseki-ui/tests/e2e/support/vite-preprocessor.js
- jena-fuseki2/jena-fuseki-ui/vite.config.js
GitHub issue resolved #1749
The [vue docs for layz loading routes](https://router.vuejs.org/guide/advanced/lazy-loading.html) shows an example of webpack and vite for dynamic lazy imports of routes.
We had webpack before moving to Vite, but we did not update this part. This shouldn't be breaking anything, but could be related to #1749.
It will be marked as a draft until we can figure out if this fixes #1749 or not, or otherwise add another commit with the fix for that issue here.
----
---- …
> GH-1749: Replacing webpack chunks by Vite rollup

- jena-arq/src/main/java/org/apache/jena/sparql/function/scripting/NV.java
- jena-arq/src/test/java/org/apache/jena/sparql/function/scripting/TestNV.java
Pull request Description: Script Function would crash with number exception when trying to return a big integer from javascript (like 100000000000000000000000000)
as far as I can tell it was also trying to use the wrong variable (x instead of d)
----
----
> incorrect integer cast in scripting.NV

- jena-fuseki2/jena-fuseki-docker/download.sh
No associated issue. Quick typo and tabs/spaces fix. I am doing some tests with Jena and Docker, and looking at the `jena-fuseki-docker` scripts noticed the typo and the tabs vs. spaces :+1:
> Fix typo, replace tabs by spaces

- apache-jena/template.bin
This allows users of command-line tools to easily modify the the classpath to include locations of user-defined classes.
GitHub issue resolved: none
Modifies the classpath passed to Java to be the Jena classpath, followed by whatever the CLASSPATH environment variable is set to.
----
----
> Prepend Jena classpath to existing CLASSPATH

- jena-arq/src/main/java/org/apache/jena/riot/system/StreamRDFWriter.java
- jena-arq/src/main/java/org/apache/jena/riot/system/StreamTriplesOnly.java
- jena-cmds/src/main/java/arq/cmdline/ModLangOutput.java
- jena-cmds/src/main/java/arq/cmdline/ModLangParse.java
- jena-cmds/src/main/java/riotcmd/CmdLangParse.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/handlers/WhereHandler.java
GitHub issue resolved #1873
Changes to the command line:
* warn if inputs include quads but output is triple only.
* warn if inputs generate quads but output is triple only (stream default graph only)
* error if inputs generate quads but formatted (i.e. buffered) output is triple only
----
----
> Errors and warnings when quads in, triples out

- jena-fuseki2/jena-fuseki-docker/README.md
No associated issue, just had to confirm something in the doc while testing the image with Skosmos and noticed this type :+1:  :runner:
> One typo in Docker readme

- jena-fuseki2/jena-fuseki-docker/Dockerfile
GitHub issue resolved #1889
Moves `adduser` to final layer only (we were creating and then copying `/etc/passwd`). Runs `addgroup` before, and uses a fixed uid/gid for user and group.
Create base directory, changes ownership, and then switches to the Jena user in Docker. That creates everything else with the correct uid/gid/ownership.
----
----
> [GH-1889] Use arguments for uid and gid, add group and user, re-work order of commands to make dirs and change ownership

- jena-fuseki2/jena-fuseki-ui/package.json
- jena-fuseki2/jena-fuseki-ui/yarn.lock
This is an alternative to PR #1900 
This PR updates `vite` to 4.0.5, then recreates yarn.lock from scratch.
----
> Update vite to 4.0.5; recreate yarn.lock

- jena-arq/src/main/java/org/apache/jena/http/HttpLib.java
- jena-arq/src/main/java/org/apache/jena/riot/other/G.java
- jena-arq/src/main/java/org/apache/jena/sparql/SystemARQ.java
- jena-arq/src/main/java/org/apache/jena/sparql/exec/http/QueryExecHTTP.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/NodeValueCmp.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/nodevalue/XSDFuncOp.java
- jena-cmds/src/main/java/arq/qexpr.java
* Fixes #1902
* Fixes a report that missing content-type causes NPE.
* Call the switchable compare for xsd:dateTime (F&O vs XSD definitions of compare)
----
> GH-1902: Handle null body for an error response.

- jena-arq/src/main/java/org/apache/jena/riot/RDFFormat.java
- jena-arq/src/main/java/org/apache/jena/riot/RDFWriterRegistry.java
- jena-arq/src/main/java/org/apache/jena/riot/RIOT.java
- jena-arq/src/main/java/org/apache/jena/riot/writer/IndentStyle.java
- jena-arq/src/main/java/org/apache/jena/riot/writer/TriGWriterLong.java
- jena-arq/src/main/java/org/apache/jena/riot/writer/TurtleShell.java
- jena-arq/src/main/java/org/apache/jena/riot/writer/TurtleWriterLong.java
- jena-arq/src/main/java/org/apache/jena/riot/writer/WriterLib.java
- jena-arq/src/test/java/org/apache/jena/riot/TestTurtleWriter.java
- jena-arq/src/test/java/org/apache/jena/riot/TestTurtleWriterPretty.java
- jena-arq/src/test/java/org/apache/jena/riot/writer/TestRiotWriterGraph.java
- jena-arq/src/test/java/org/apache/jena/riot/writer/TestTurtleWriter.java
GitHub issue resolved #1924  
Adds a "long” Turtle/TriG format variant is based on rdflib's "longturtle" format. It uses a fixed indentation width (2) and linebreaks after each sequence element.
----
----
> GH-1924: Add a "long" Turtle/TriG format variant

- jena-core/src/main/java/org/apache/jena/graph/GraphMemFactory.java
This PR adds function to create GraphMem2 graphs.
There is no change to the system default in-memory non-transactional graph which is `GraphMem`.
---
> GH-1912: GraphMemFactory functions for GraphMem2

- apache-jena/dist/LICENSE
- apache-jena/dist/NOTICE
- jena-fuseki2/apache-jena-fuseki/dist/LICENSE
- jena-fuseki2/apache-jena-fuseki/dist/NOTICE
GitHub issue resolved #1943
Linking to licenses rather than text inclusions is acceptable nowadays.
----
> GH-1943: Link to Dexx LICENSE. Put Dexx NOTICE in NOTICE files

- pom.xml
graalvm 23 requires Java17.
Despite graalvm not being something the project ships, it is used in the build.
This PR reverts to a Java11 compatible verison.
This reverts commit 027956c2d9a58cccaeedaf7f7b63ca9042b18991.
> Revert "Bump ver.graalvm from 22.3.2 to 23.0.0"

- jena-arq/src/main/java/org/apache/jena/sparql/graph/GraphTxn.java
- jena-arq/src/main/java/org/apache/jena/system/Txn.java
GitHub issue resolved #1961
Provide `GraphTxn.find()` that transparently runs inside a transaction to ensure consistency.
This is like "autocommit" for SQL databases. It has all the consequences of that as well. It has more overhead, and does give application change consistency (e.g. a read-modify-write) is two transactions and other transactions/thread may change or view the database between the "read" and the "write").
----
> GH-1961: Thread-safe and consistent GraphTxn.find

- pom.xml
This replaces #1977 and #1980.
If the Caffeine is updates (#1980) then a maven convergence error occurs on `org.checkerframework:checker-qual` and `org.checkerframework:checker-qual`.
This is resolved in this PR by taking the Caffeine choice.
----
> Bump Caffeine 3.1.6 to 3.1.7, Guava 32.1.1 to 32.1.2. Fix convergence.

- jena-arq/src/main/java/org/apache/jena/sparql/graph/GraphReadOnly.java
- jena-arq/src/main/java/org/apache/jena/sparql/graph/PrefixMappingReadOnly.java
- jena-arq/src/main/java/org/apache/jena/sparql/graph/UnmodifiableGraph.java
- jena-arq/src/test/java/org/apache/jena/sparql/graph/TS_Graph.java
- jena-arq/src/test/java/org/apache/jena/sparql/graph/TestGraphReadOnly.java
GitHub issue resolved #1990
----
> GH-1990: Fix GraphReadOnly; deprecate UnmodifiableGraph

- jena-arq/src/main/java/org/apache/jena/riot/lang/LangTurtleBase.java
- jena-arq/src/main/java/org/apache/jena/riot/system/PrintingStreamRDF.java
- jena-arq/src/main/java/org/apache/jena/riot/system/RiotLib.java
- jena-arq/src/main/java/org/apache/jena/riot/system/StreamRDFLib.java
- jena-base/src/main/java/org/apache/jena/atlas/io/IndentedLineBuffer.java
- jena-base/src/main/java/org/apache/jena/atlas/io/IndentedWriter.java
- jena-base/src/main/java/org/apache/jena/atlas/io/Writer2.java
- jena-core/src/main/java/org/apache/jena/rdfxml/xmlinput/ARPErrorNumbers.java
- jena-core/src/main/java/org/apache/jena/rdfxml/xmlinput/impl/ARPLocation.java
- jena-core/src/main/java/org/apache/jena/rdfxml/xmlinput/impl/ElementLexer.java
- jena-core/src/main/java/org/apache/jena/rdfxml/xmlinput/impl/ParserSupport.java
- jena-core/src/main/java/org/apache/jena/rdfxml/xmlinput/states/Frame.java
- jena-core/src/main/java/org/apache/jena/util/JenaXMLInput.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/sys/DatabaseOps.java
This PR is tidy-up and small improvements to internal classes gathered while working on RDF/XML.
----
> Preparation work for RIOT RDF/XML parsers

- pom.xml
Update libthrift from 0.18.1 to 0.19.0.
Update the exclusions for libthrift due to it switching to http client5 and jakarta.
----
> Bump libthrift from 0.18.1 to 0.19.0

- pom.xml
GraalVM v23 bumps the requirement to Java17.
Stick with v22 for Jena4.
(Surprising how many of our builds are Java17 under the covers - this only broke in one place)
> Switch to GraalVM v22 for Java11

- jena-cmds/src/main/java/arq/query.java
- jena-cmds/src/test/java/org/apache/jena/cmds/TestCmdExt.java
- jena-extras/jena-commonsrdf/pom.xml
- jena-geosparql/src/test/java/org/apache/jena/geosparql/implementation/SRSInfoTest.java
- jena-geosparql/src/test/java/org/apache/jena/geosparql/spatial/SearchEnvelopeTest.java
- pom.xml
Dependency upgrades and adjustments needed due to these upgrades.
org.mockito:mockito-core : 5.5.0 -> 5.6.0
org.eclipse.jetty : 10.0.15 -> 10.0.17
com.fasterxml.jackson : 2.15.2 -> 2.15.3
com.google.guava:guava : 32.1.2-jre -> 32.1.3-jre
commons-io:commons-io: 2.11.0 -> 2.14.0
commons-codec:commons-codec: 1.15.0 -> 1.16.0
org.apache.commons:commons-lang3: 3.12.0 -> 3.13.0 
org.apache.sis.core:sis-referencing : 1.1 -> 1.4
orq.apache.lucene : 9.5.0 -> 9.7.0
This is not an upgrade to the current Lucene version 9.8.0. With Java21, I was getting test setup errors about NoSuchMethod (java.lang.foreign.Arena.ofShared), which is a Java21 "preview feature". 
---
By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and …
> Upgrade of Java dependencies

- jena-arq/src/main/java/org/apache/jena/sparql/engine/QueryEngineRegistry.java
- jena-arq/src/main/java/org/apache/jena/sparql/modify/UpdateEngineRegistry.java
Fix the following exception observed in production:
```
java.util.ConcurrentModificationException: null
at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
at org.apache.jena.sparql.engine.QueryEngineRegistry.find(QueryEngineRegistry.java:94)
at org.apache.jena.query.QueryExecutionBuilder.build(QueryExecutionBuilder.java:98)
at org.apache.jena.query.QueryExecutionFactory.make(QueryExecutionFactory.java:622)
at org.apache.jena.query.QueryExecutionFactory.make(QueryExecutionFactory.java:602)
at org.apache.jena.query.QueryExecutionFactory.create(QueryExecutionFactory.java:146)
at org.apache.jena.query.QueryExecutionFactory.create(QueryExecutionFactory.java:158)
...
```
The …
> JENA-2356: Fix race in QueryEngineRegistry, UpdateEngineRegistry init

- jena-arq/src/main/java/org/apache/jena/sparql/graph/GraphFactory.java
- jena-arq/src/main/java/org/apache/jena/sparql/graph/GraphTxn.java
- jena-core/src/main/java/org/apache/jena/graph/Graph.java
- jena-core/src/main/java/org/apache/jena/graph/GraphMemFactory.java
- jena-core/src/main/java/org/apache/jena/mem/GraphMem.java
- jena-core/src/main/java/org/apache/jena/rdf/model/Model.java
…rentModificationException (see #1992, #1961)
----
----
> jena-core: add more javadocs about Graph-mem thread-safety and ConcurrentModificationException

- pom.xml
This removes the automatic generation of SPDX from the build cycle until things become clearer.
Discussion on dev@
https://lists.apache.org/thread/ws6kvlk90p65f0cx74bn707kkf68cxvx
> GH-2019: Don't produce SPDX; leave setup placeholder

- jena-core/src/main/java/org/apache/jena/ext/xerces/util/URI.java
- jena-core/src/main/java/org/apache/jena/irix/IRIx.java
- jena-core/src/main/java/org/apache/jena/rdfxml/xmlinput0/impl/XMLBaselessContext.java
- jena-core/src/main/java/org/apache/jena/rdfxml/xmlinput0/impl/XMLHandler.java
- jena-core/src/main/java/org/apache/jena/rdfxml/xmlinput1/impl/XMLBaselessContext.java
- jena-core/src/main/java/org/apache/jena/rdfxml/xmlinput1/impl/XMLHandler.java
- jena-core/src/test/java/org/apache/jena/irix/TestIRIx.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/sys/FusekiErrorHandler.java
- jena-iri/src/main/java/org/apache/jena/iri/impl/AbsIRIImpl.java
- pom.xml
GitHub issue resolved #2060
This closes #2060
Various fixes in in ARP show that the change works. Several "isAbsolute" needed to be "!isRelative".
----
> Fix for jena-iri IRI.isAbsolute

- pom.xml
Planned permanent change:
https://bugs.openjdk.org/browse/JDK-8306819
with notes/warnings in Java 22
https://bugs.openjdk.org/browse/JDK-8310061
and backported to Java21:
https://bugs.openjdk.org/browse/JDK-8311073
This PR is a build-related cleanup for Java21, which is compatible with Java17. 
In Java21, there were build warnings from javac about "annotation processing"
---
> Disable annotation processing (and avoid build warnings)

- jena-arq/src/test/java/org/apache/jena/riot/system/TestIRIxRIOT.java
- jena-core/src/main/java/org/apache/jena/irix/IRIProviderAny.java
- jena-core/src/main/java/org/apache/jena/irix/IRIProviderJDK.java
- jena-core/src/main/java/org/apache/jena/irix/IRIProviderJenaIRI.java
- jena-core/src/main/java/org/apache/jena/irix/IRIs.java
- jena-core/src/main/java/org/apache/jena/irix/IRIx.java
- jena-core/src/test/java/org/apache/jena/irix/TS_IRIx.java
- jena-core/src/test/java/org/apache/jena/irix/TestIRIxOps.java
- jena-core/src/test/java/org/apache/jena/irix/TestIRIxSyntax.java
- jena-core/src/test/java/org/apache/jena/irix/TestParseIRIx.java
- jena-core/src/test/java/org/apache/jena/irix/TestRFC3986.java
GitHub issue resolved #2062
Make IRI handling follow [RFC 8141](https://datatracker.ietf.org/doc/html/rfc8141) which retrospectively changes the URN namespace definition of [urn:uuid: in RFC 4122](https://datatracker.ietf.org/doc/html/rfc4122).
Review the test coverage, add tests, and generally tidy up IRIx testing.
This closes #2062
----
> GH-2062: urn:uuid:  handling to follow RFC 8141.

- jena-arq/src/main/java/org/apache/jena/riot/RDFParser.java
- jena-arq/src/test/java/org/apache/jena/rdf_star/TestNQuadsStarParse.java
- jena-arq/src/test/java/org/apache/jena/rdf_star/TestNTriplesStarParse.java
- jena-arq/src/test/java/org/apache/jena/rdf_star/TestTrigStarParse.java
- jena-arq/src/test/java/org/apache/jena/rdf_star/TestTurtleStarParse.java
- jena-arq/src/test/java/org/apache/jena/riot/TestJsonLDReader.java
- jena-arq/src/test/java/org/apache/jena/riot/TestRDFParser.java
- jena-arq/src/test/java/org/apache/jena/riot/lang/TestRDFXML_ReaderProperties.java
- jena-arq/src/test/java/org/apache/jena/riot/system/TestAsyncParser.java
- jena-arq/src/test/java/org/apache/jena/riot/writer/TestTurtleWriter.java
- jena-arq/src/test/java/org/apache/jena/sparql/path/TestPathQuery.java
- jena-core/src/main/java/org/apache/jena/irix/IRIProviderJenaIRI.java
- jena-core/src/test/java/org/apache/jena/irix/TestRFC3986.java
- jena-examples/src/main/java/arq/examples/ExModelStore01.java
- jena-examples/src/main/java/arq/examples/auth/ExAuth01_RDFConnectionPW.java
- jena-examples/src/main/java/arq/examples/auth/ExAuth04_ServicePW.java
- jena-fuseki2/jena-fuseki-webapp/src/main/java/org/apache/jena/fuseki/webapp/FusekiWebapp.java
GitHub issue resolved #2066
This PR adds the operation RDFParser.fromString(text, Lang) and deprecates the original RDFParser.fromString(text).
Tests using the now-deprecated function have been changed to the new function. These are all the "Test*" file in the PR.
----
> GH-2066: Add and prefer RDFParser.fromString(text, Lang)

- jena-core/src/main/java/org/apache/jena/mem/HashCommon.java
- jena-core/src/main/java/org/apache/jena/util/iterator/NiceIterator.java
- jena-core/src/test/java/org/apache/jena/rdf/model/test/AbstractTestPackage.java
- jena-core/src/test/java/org/apache/jena/test/TestPackage.java
- jena-core/src/test/java/org/apache/jena/test/jena4/TestRemoveBug.java
- jena-core/testing/reports/graph-mem-broken-iterator-delete-01.ttl
- pom.xml
GitHub issue: #2076
This is the `jena4` branch fix for #2076.
It includes a test case.
It also has a fix in the build because javadoc links to the website and there is no jena-jdbc javadoc any more.
Quite a lot of white space fixs in HashCommon, showing how long ago it was last touched!
---
> [Jena4] GH-2076: Fix for Iterator.remove in GraphMem

- jena-core/src/main/java/org/apache/jena/mem/HashCommon.java
- jena-core/src/main/java/org/apache/jena/util/iterator/NiceIterator.java
GitHub issue resolved #2076
This is the jena5 branch fix for #2076 for legacy GraphMem.
There is no test. We don't have an example of the bug for Jena5. The bug is both hash-dependent and sensitive to the order of insertion of triples.
There is a test case for the jena4 in PR #2080
Changes to `Node` mean the example for Jena4 no longer applies.
----
> [Jena5] GH-2076: Fix for Iterator.remove in GraphMem

- jena-fuseki2/jena-fuseki-ui/package.json
- jena-fuseki2/jena-fuseki-ui/pom.xml
- jena-fuseki2/jena-fuseki-ui/yarn.lock
This PR chooses versions to work with node 16, and hence earlier versions of libc (e.g. as found by default on Ubuntu 18.04).
While the build controls the version of node, it does not have control over the version of libc provided by the base OS.
See #2054 and #2055.
----
> Downgrade dependencies to work with node 16

- jena-arq/src/main/java/org/apache/jena/sparql/graph/GraphTxn.java
Fix inverted logic causing `GraphTxn` to incorrectly attempt a nested transaction, this was already fixed on `main` by https://github.com/apache/jena/commit/0baf13e3fba0cfd66299cdabcd57bc39382a4298
Backports a fixed inverted logic check that was already addressed on main onto the jena4 branch
GitHub issue resolved #2086
----
----
> Fixes GraphTxn find() for incorrect attempt to create a nested transaction

- jena-fuseki2/jena-fuseki-ui/package.json
- jena-fuseki2/jena-fuseki-ui/yarn.lock
Addresses CVE-2023-45857
Version 1.6.1 was being used anyway.
----
> Bump Axios from 1.5.1 to 1.6.1

- jena-arq/src/test/java/org/apache/jena/riot/system/AbstractTestPrefixMap.java
Problem noted in #2097
Fix around line 320 (new numbering)
https://github.com/apache/jena/pull/2098/files#diff-edd0d324be6aa5e217bca37e9f8949ca047c64990e80726b8dff7e08d0eadabdL328
Reformat old code.
---
> AbstractTestPrefixMap: Remove unstable assert

- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/AbstractQueryBuilder.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/AskBuilder.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/ConstructBuilder.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/Converters.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/DescribeBuilder.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/SelectBuilder.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/UpdateBuilder.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/WhereBuilder.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/clauses/WhereClause.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/handlers/WhereHandler.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/rewriters/AbstractRewriter.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/updatebuilder/WhereQuadHolder.java
- jena-extras/jena-querybuilder/src/test/java/org/apache/jena/arq/TestAbstractQueryBuilder.java
- jena-extras/jena-querybuilder/src/test/java/org/apache/jena/arq/querybuilder/AbstractQueryBuilderTest.java
- jena-extras/jena-querybuilder/src/test/java/org/apache/jena/arq/querybuilder/AskBuilderTest.java
- jena-extras/jena-querybuilder/src/test/java/org/apache/jena/arq/querybuilder/ConstructBuilderTest.java
- jena-extras/jena-querybuilder/src/test/java/org/apache/jena/arq/querybuilder/ConvertersTest.java
- jena-extras/jena-querybuilder/src/test/java/org/apache/jena/arq/querybuilder/SelectBuilderTest.java
- jena-extras/jena-querybuilder/src/test/java/org/apache/jena/arq/querybuilder/clauses/SolutionModifierTest.java
- jena-extras/jena-querybuilder/src/test/java/org/apache/jena/arq/querybuilder/clauses/WhereClauseTest.java
- jena-extras/jena-querybuilder/src/test/java/org/apache/jena/arq/querybuilder/handlers/SolutionModifierHandlerTest.java
- jena-extras/jena-querybuilder/src/test/java/org/apache/jena/arq/querybuilder/handlers/WhereHandlerTest.java
Pull request Description:  Adds the ability to use a Collection object as a node in the query builder.
`AddWhere( A, B, List.of( C, D ))` should yield the same as `SELECT * WHERE { A B (C D) }` 
----
----
> JENA-2357 Add Collection as a valid type for where clause node in query builder.

- jena-arq/src/test/java/org/apache/jena/query/TestParameterizedSparqlString.java
Tests like `org.apache.jena.query.TestParameterizedSparqlString#test_param_string_injection_10` makes more than one injections. `ParameterizedSparqlString.getVars()` is used to retrieve the order of injections, `getVars()` calls `this.params.keySet().iterator()` on the `ParameterizedSparqlString` object and the implementation of `params` of `ParameterizedSparqlString` is a `HashMap` which does not guarantee the order. So what is returned is not necessarily by the injection order.
https://github.com/apache/jena/blob/fc01d33e6c11eed68784f820bf2dd161868d1d37/jena-arq/src/main/java/org/apache/jena/query/ParameterizedSparqlString.java#L1138
https://github.com/apache/jena/blob/fc01d33e6c11eed68784f820bf2dd161868d1d37/jena-arq/src/main/java/org/apache/jena/query/Paramete …
> ParameterizedSparqlString: Fixed flaky tests due to HashMap

- jena-arq/src/main/java/org/apache/jena/sparql/lang/QueryParserBase.java
- jena-arq/src/test/java/org/apache/jena/sparql/syntax/TS_Syntax.java
- jena-arq/src/test/java/org/apache/jena/sparql/syntax/TestQueryParser.java
GitHub issue resolved #2102. This closes #2102.
This change causes the parser to accept, with a warning, the charcater `[` and `]`.
This makes it behave the same as RIOT data syntax parsing.
----
> GH-2102: Parse and accept [], with warning

- jena-arq/src/main/java/org/apache/jena/riot/writer/IndentStyle.java
- jena-arq/src/main/java/org/apache/jena/riot/writer/WriterStreamRDFBlocks.java
This closes #2093.
The output from WriterStreamRDFBlocks was incorrect if triples and quads are mixed. That can't happen parsing a single file because if it's quads, default graph triples come through as quads.
----
> GH-2093: Correct WriterStreamRDFBlocks on mixed triples/quads

- jena-arq/src/main/java/org/apache/jena/riot/out/NodeFmtLib.java
- jena-arq/src/main/java/org/apache/jena/riot/system/StreamRDFWrapper.java
- jena-arq/src/main/java/org/apache/jena/riot/system/StreamRDFWriter.java
- jena-arq/src/main/java/org/apache/jena/riot/system/StreamTriplesOnly.java
- jena-arq/src/main/java/org/apache/jena/riot/writer/WriterStreamRDFBase.java
- jena-cmds/src/main/java/riotcmd/CmdLangParse.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/AbstractQueryBuilder.java
- jena-extras/jena-serviceenhancer/src/test/java/org/apache/jena/sparql/service/enhancer/impl/TestServiceEnhancerMisc.java
GitHub issue resolved #2083
Put a default graph quads translation when writing quads to a triples syntax.
Allow different policies on what to do if an unacceptable quad is seen.
----
> Print default graph quads as triples if output is a triples syntax.

- jena-arq/src/main/java/org/apache/jena/query/QueryExecutionFactory.java
- jena-arq/src/main/java/org/apache/jena/sparql/graph/GraphUnionRead.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/SPARQLQueryProcessor.java
- jena-permissions/pom.xml
Format.
A build warning fix.
Internal refactor for initalBinding.
----
> Accumulated clean-up

- jena-core/src/main/java/org/apache/jena/graph/NodeFactory.java
The `@deprecated` message named the wrong method.
----
> Correct javadoc NodeFactory.createLiteral(String) deprecated message

- jena-arq/src/main/java/org/apache/jena/riot/system/stream/LocationMapper.java
- jena-cmds/src/main/java/shacl/shacl_validate.java
- jena-shacl/src/main/java/org/apache/jena/shacl/Imports.java
- jena-shacl/src/main/java/org/apache/jena/shacl/Shapes.java
- jena-shacl/src/main/java/org/apache/jena/shacl/engine/ValidationContext.java
- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/JLogConstraint.java
- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/SparqlValidation.java
- jena-shacl/src/main/java/org/apache/jena/shacl/parser/Constraints.java
- jena-shacl/src/main/java/org/apache/jena/shacl/parser/ShapesParser.java
- jena-shacl/src/main/java/org/apache/jena/shacl/sys/ShaclSystem.java
- jena-shacl/src/main/java/org/apache/jena/shacl/validation/VLib.java
- jena-shacl/src/main/java/org/apache/jena/shacl/validation/ValidationProc.java
- jena-shacl/src/main/java/org/apache/jena/shacl/vocabulary/SHACL.java
- jena-shacl/src/test/files/local/manifest.ttl
- jena-shacl/src/test/files/local/other/sparql-vars-001-data.ttl
- jena-shacl/src/test/files/local/other/sparql-vars-001-results.ttl
- jena-shacl/src/test/files/local/other/sparql-vars-001-shape.ttl
- jena-shacl/src/test/files/std/sparql/pre-binding/manifest.ttl
- jena-shacl/src/test/java/org/apache/jena/shacl/TC_SHACL.java
- jena-shacl/src/test/java/org/apache/jena/shacl/tests/jena_shacl/JenaShaclTestsByCode.java
This resolves #2157
This resolves #2158
Commit "Support ?currentShape and ?shapesGraph" helps with DASH. There are several different dash.ttl around.The datashape/dash on the web redefines spec-standard shapes leading to multiple validators for the same feature (e.g `sh:closed`).
A `StreamManager` for imports is provided to enable applications to use their own customized subsets of de-facto shared shapes libraries.
----
> SHACL improvements: always import on cmd validation ; support ?currentShape and ?shapesGraph

- jena-arq/src/main/java/org/apache/jena/sparql/algebra/AlgebraGenerator.java
- jena-arq/src/main/java/org/apache/jena/sparql/algebra/OpLib.java
- jena-arq/src/main/java/org/apache/jena/sparql/algebra/PropertyFunctionGenerator.java
- jena-arq/src/main/java/org/apache/jena/sparql/algebra/op/OpQuadBlock.java
- jena-arq/src/main/java/org/apache/jena/sparql/algebra/op/OpTable.java
- jena-arq/src/main/java/org/apache/jena/sparql/algebra/optimize/TransformFilterEquality.java
- jena-arq/src/main/java/org/apache/jena/sparql/algebra/optimize/TransformFilterImplicitJoin.java
- jena-arq/src/main/java/org/apache/jena/sparql/algebra/optimize/TransformFilterInequality.java
- jena-arq/src/main/java/org/apache/jena/sparql/algebra/optimize/TransformFilterPlacement.java
- jena-arq/src/main/java/org/apache/jena/sparql/algebra/optimize/TransformFilterPlacementConservative.java
- jena-arq/src/main/java/org/apache/jena/sparql/algebra/optimize/TransformPattern2Join.java
- jena-arq/src/main/java/org/apache/jena/sparql/algebra/optimize/TransformPromoteTableEmpty.java
- jena-arq/src/main/java/org/apache/jena/sparql/sse/builders/BuilderOp.java
- jena-arq/src/test/java/org/apache/jena/sparql/algebra/TestAlgebraTranslate.java
- jena-arq/src/test/java/org/apache/jena/sparql/algebra/optimize/TestOptimizer.java
- jena-arq/src/test/java/org/apache/jena/sparql/algebra/optimize/TestTransformPromoteTableEmpty.java
- jena-arq/src/test/java/org/apache/jena/sparql/sse/TestSSE_Builder.java
- jena-extras/jena-serviceenhancer/src/main/java/org/apache/jena/sparql/service/enhancer/impl/BatchQueryRewriter.java
Part of #2153
Handle the non-parser case of a `ElementFilter` in the query AST which is not within a `ElementGroup`.
----
> GH-2153: Compile Element when not it is in an ElementGroup

- jena-arq/src/main/java/org/apache/jena/riot/out/quoted/QuotedURI.java
- jena-arq/src/test/java/org/apache/jena/riot/out/TS_Out.java
- jena-arq/src/test/java/org/apache/jena/riot/out/TestOutputQuotedString.java
- jena-arq/src/test/java/org/apache/jena/riot/out/TestOutputQuotedURI.java
- jena-arq/src/test/java/org/apache/jena/riot/out/quoted/TestQuotedURIInternal.java
- jena-base/src/main/java/org/apache/jena/atlas/lib/EscapeStr.java
GitHub issue resolved #2167
This PR translates raw bad characters (see [IRIREF](https://www.w3.org/TR/rdf-turtle/#grammar-production-IRIREF) pattern ``[^#x00-#x20<>"{}|^`\]``) into `\u` escapes.
This does not "fix" the URI - that's not possible.
The PR also has internal implementations for the other choices listed in #2167 (print raw, which is Jena4 behaviour; percent encoding).
This code does not do an RFC 3986 parsing of the URI string nor does it provide punycode host names.
----
> GH-2167: Quoted URI output

- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/FusekiServer.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/cmds/FusekiMain.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestFusekiServerBuild.java
Make the tests a little easier to use for developers.
The "default port" tests might clash with other use of Fuseki on the same machine.
---
> Don't fail test on bind failure of the default port

- jena-core/src/main/java/org/apache/jena/rdf/model/Literal.java
GitHub issue resolved #2248 
----
----
> docs(Literal): adopt docstring to fit the behaviour of `getString()`

- jena-text/src/main/java/org/apache/jena/query/text/TextIndexLucene.java
- jena-text/src/test/java/org/apache/jena/query/text/TS_Text.java
- jena-text/src/test/java/org/apache/jena/query/text/TestTextMultipleProplistNotWorking.java
GitHub issue resolved #2094
* Add field grouping (parens) to composeQField method to fix #2094 
I see a similar fix with parens is also used in other paths in the code for example in line 765 and 771 of the same file.
```
qString = "(" + qString + ") AND " + (!lang.equals("none") ? langField+":"+lang : "-"+langField+":*");
log.trace("query$ ADDING LANG qString: {} ", qString) ;
}
```
```
if (graphURI != null) {
String escaped = QueryParserBase.escape(graphURI) ;
qString = "(" + qString + ") AND " + getDocDef().getGraphField() + ":" + escaped ;
}
```
*  Add a unique set to remove duplicate query clauses on propLists which is mentioned by @rvesse 
> It also looks like we generate duplicate query clauses when multiple properties map to the same Lucene field which …
> Debug text prop not working in some cases

- jena-geosparql/src/main/java/org/apache/jena/geosparql/implementation/jts/CustomCoordinateSequence.java
- jena-geosparql/src/test/java/org/apache/jena/geosparql/implementation/jts/CustomCoordinateSequenceTest.java
GitHub issue resolved #2219
Does fix an issue when Z axis isn't available.
----
----
> GH-2219 : Check for existence of Z axis and measure to avoid exception when neither is available

- pom.xml
Update the `<links>` section of the Javadoc configuration to point to TDB2.
Pointing to a non-existent URL cause the build to break if not explicitly set to "offline".
For Jena5, TDB2 is preferred.
> Update javadoc links to point to TDB2

- jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIterFilterExpr.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/ExprNode.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/nodevalue/NodeValueOps.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/TestNodeValueOps.java
- jena-arq/src/test/java/org/apache/jena/sparql/sse/TestSSE_Basic.java
- jena-fuseki2/jena-fuseki-server/src/main/resources/META-INF/NOTICE
- jena-rdfpatch/src/main/java/org/apache/jena/rdfpatch/system/PatchSystem.java
- jena-text/src/test/java/org/apache/jena/query/text/TestTextMultipleProplistNotWorking.java
GitHub issue resolved #2273 
* Implement XSD duration division #2273
* Updates jena-fuseki-server NOTICE because Jena5 does not depend on jsonld-java any more.
* Misc tidy up.
----
> GH-2273: XSD Duration division

- jena-fuseki2/jena-fuseki-core/pom.xml
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/system/DataUploader.java
- pom.xml
GitHub issue resolved #2281
Apache Commons fileupload2 has split into servlet5 and servlet6 artifacts.
----
> GH-2281: Update to commons-fileupload2-jakarta-servlet6

- jena-arq/src/main/java/org/apache/jena/http/sys/ExecHTTPBuilder.java
- jena-arq/src/main/java/org/apache/jena/sparql/exec/http/QueryExecHTTP.java
- jena-arq/src/main/java/org/apache/jena/sparql/exec/http/QueryExecHTTPBuilder.java
- jena-integration-tests/src/test/java/org/apache/jena/test/rdflink/TestRDFLinkHTTP.java
- jena-rdfconnection/src/main/java/org/apache/jena/rdfconnection/RDFConnectionRemoteBuilder.java
- jena-rdfconnection/src/main/java/org/apache/jena/rdflink/RDFLinkFuseki.java
- jena-rdfconnection/src/main/java/org/apache/jena/rdflink/RDFLinkHTTP.java
- jena-rdfconnection/src/main/java/org/apache/jena/rdflink/RDFLinkHTTPBuilder.java
- jena-rdfconnection/src/test/java/org/apache/jena/rdfconnection/TestRDFConnectionHTTP.java
GitHub issue resolved #2233 
GitHub issue resolved #2255 
Pull request Description: This PR proposes 
* opening up  ARQ's QueryExecHTTPBuilder for subclassing, such that RDFLinkHTTP can override the buildX() method to set the effective header according to configuration.
* making the send modes for queries and updates configurable on `RDFLinkHTTPBuilder`.
----
----
> GH-2233: Improved handling of specifically set HTTP headers in RDFLinkHTTP

- jena-core/src/main/java/org/apache/jena/datatypes/xsd/impl/XSDBaseStringType.java
- jena-core/src/main/java/org/apache/jena/graph/impl/LiteralLabel.java
- jena-core/src/test/java/org/apache/jena/datatypes/TestDatatypes.java
GitHub issue resolved #2270 
As illustrated in the sample code on the linked issue, when creating literal nodes of xsd:string type we are not converting the given objects to Strings but rather are leaving them as the original classes. Instead of UUIDs, the same effect can be made if passed Integers, Floats or any other object type. 
`
NodeFactory.createLiteralByValue(UUID.randomUUID(), XSDDatatype.XSDstring);
NodeFactory.createLiteralByValue(9, XSDDatatype.XSDstring);
NodeFactory.createLiteralByValue(9.99f, XSDDatatype.XSDstring);
`
What's interesting is that for numeric types, this isn't the case and if passing a (valid) string to numeric type everything works as expected.
`
NodeFactory.createLiteralByValue("9", XSDDatatype.XSDint); …
> GH-2270: Properly process objects passed in as xsd:string literals.

- jena-fuseki2/jena-fuseki-main/pom.xml
- jena-fuseki2/jena-fuseki-webapp/pom.xml
- jena-fuseki2/jena-fuseki-webapp/src/main/java/org/apache/jena/fuseki/webapp/ShiroEnvironmentLoader.java
- pom.xml
Update for Apache Shiro 2.0.0.
Use the Shiro BOM in top-level dependency management.
The combined jar shading (jena-fuseki-fulljar, jena-fuseki-server) looks better.
---
> Bump Apache Shiro from 1.13.0 to 2.0.0

- jena-cmds/src/main/java/org/apache/jena/cmd/CommandLineBase.java
- jena-fuseki2/jena-fuseki-core/pom.xml
- jena-fuseki2/jena-fuseki-core/src/test/java/org/apache/jena/fuseki/TS_FusekiCore.java
- jena-fuseki2/jena-fuseki-core/src/test/java/org/apache/jena/fuseki/servlets/TestCrossOriginFilter.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/FusekiServer.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/cmds/FusekiMain.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/cmds/ServerConfig.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TS_FusekiMain.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestFusekiMainCmd.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestFusekiMainCmdArguments.java
- jena-fuseki2/jena-fuseki-main/testing/Config/cors.properties
- jena-fuseki2/jena-fuseki-main/testing/Config/invalid.ttl
GitHub issue resolved #2297 
Enabling the potential passing of a configuration file containing the desired CORS configuration so that we have a greater choice than present - none or default. 
Also some tidying up of spellings, some better error checks and improved testing of the existing Cross Origin Filter class and all of the exceptional cases for Fuseki Main's command-line arg processing. 
----
----
> GH-2297: Add CORS configuration file as command line parameter to Fuseki Main

- jena-base/src/main/java/org/apache/jena/atlas/io/IO.java
- jena-base/src/main/java/org/apache/jena/atlas/logging/LogCtl.java
- jena-db/jena-dboe-base/src/main/java/org/apache/jena/dboe/sys/IO_DB.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/system/spot/SpotTDB2.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/TDB2.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/sys/DatabaseOps.java
- jena-tdb2/src/test/java/org/apache/jena/tdb2/setup/TestStoreParamsCreate.java
- jena-tdb2/src/test/java/org/apache/jena/tdb2/sys/TestDatabaseCompact.java
GitHub issue resolved #2254
Use a temporary directory for building the compacted storage.
Clear-up any stray temporary directories when creating the Java objects for the database.
----
----
> GH-2254: Compaction using a temporary directory and atomic move

- jena-cmds/src/main/java/tdb/tdbloader.java
- jena-cmds/src/main/java/tdb2/tdbloader.java
While JSON-LD can have multiple graphs in one file, it is commonly used for a single graph.
Don't reject JSON-LD data when loading in a single named graph (TDB1 and TDB2).
(if there is more than one named graph in the input a warning is printed during loading).
----
> Improve JSON-LD handling

- jena-base/src/main/java/org/apache/jena/atlas/iterator/Iter.java
- pom.xml
* incremental upgrade of commons-compress 1.26.0 to 1.26.1
* return result of `Stream.onClose` in accordance with the javadoc contract.
----
> Upgrade of commons-compress 1.26.0 to 1.26.1. Adjust Iter.asStream to follow javadoc.

- jena-cmds/src/main/java/tdb2/tdbloader.java
- jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/TransactionCoordinator.java
- jena-db/jena-dboe-transaction/src/test/java/org/apache/jena/dboe/transaction/TestTransactionCoordinatorControl.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/store/DatasetGraphSwitchable.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/store/PrefixMapSwitchable.java
GitHub issue resolved #2318
There isn't a direct test of the presented problem; its asynchronous and timing dependent.
`shutdown` with no contract so there is no contract of specific behaviour or consequences on active transactions. It is an operation that is _caveat emptor_.
This PR makes a NullPointerException become a TransactionException.
There is test coverage for the new and better way to get the coordinator lock for synchronous use.
----
> GH-2318: Protect against async shutdown

- jena-fuseki2/jena-fuseki-ui/README.md
- jena-fuseki2/jena-fuseki-ui/package.json
- jena-fuseki2/jena-fuseki-ui/src/components/dataset/Pagination.vue
- jena-fuseki2/jena-fuseki-ui/src/components/dataset/TableListing.vue
- jena-fuseki2/jena-fuseki-ui/src/views/dataset/Info.vue
- jena-fuseki2/jena-fuseki-ui/tests/unit/components/dataset/pagination.vue.spec.js
- jena-fuseki2/jena-fuseki-ui/vite.config.js
- jena-fuseki2/jena-fuseki-ui/yarn.lock
GitHub issue resolved #2267
@LorenzBuehmann first tentative to fix the issue. I was going to change the `Pagination` Vue component, so that it had an option like `maxItems` (or max displayed, etc). And set it to some value like `5` or `6` as that would fix in the screen, and show the first `2` or `3`, followed by `[…]` , and then the last `2` or `3`.
But I know sometimes users may want to know the page they are in, and also be able to jump from page 23 to page 4, which wouldn't be possible doing that.
Not the most beautiful, but maybe this simpler approach to just display everything visibly works OK for this page? Or should we keep it one line only, abbreviating the list? What do you think?
----
By submitting this pull request, I acknowledge that I am making a …
> GH-2267: Display all the pagination options

- jena-arq/src/main/java/org/apache/jena/system/G.java
- jena-arq/src/test/java/org/apache/jena/system/GTest.java
- jena-base/src/main/java/org/apache/jena/atlas/lib/Copyable.java
- jena-core/src/main/java/org/apache/jena/mem2/collection/FastHashBase.java
- jena-core/src/main/java/org/apache/jena/mem2/store/TripleStore.java
- jena-core/src/main/java/org/apache/jena/mem2/store/roaring/RoaringTripleStore.java
- jena-core/src/test/java/org/apache/jena/mem2/GraphMem2Test.java
Clean the codebase of compiler warnings, mainly about unnecessary casts.
This follows on from PR #2316 that improves in-memory graph copy performance.
----
> GH-2169: Remove compiler warnings around graph copy code

- jena-arq/pom.xml
- jena-base/pom.xml
- jena-benchmarks/jena-benchmarks-jmh/pom.xml
- jena-cmds/pom.xml
- jena-core/pom.xml
- jena-db/jena-dboe-index-test/pom.xml
- jena-db/jena-dboe-index-test/src/main/java/org/apache/jena/dboe/index/testlib/AbstractTestIndex.java
- jena-db/pom.xml
- jena-examples/pom.xml
- jena-extras/jena-commonsrdf/pom.xml
- jena-extras/jena-querybuilder/pom.xml
- jena-extras/jena-serviceenhancer/pom.xml
- jena-fuseki2/jena-fuseki-access/pom.xml
- jena-fuseki2/jena-fuseki-core/pom.xml
- jena-fuseki2/jena-fuseki-geosparql/pom.xml
- jena-fuseki2/jena-fuseki-main/pom.xml
- jena-fuseki2/jena-fuseki-webapp/pom.xml
- jena-geosparql/pom.xml
- jena-integration-tests/pom.xml
- jena-iri/pom.xml
- jena-permissions/pom.xml
- jena-rdfconnection/pom.xml
- jena-rdfpatch/pom.xml
- jena-shacl/pom.xml
- jena-shex/pom.xml
- jena-tdb1/pom.xml
- jena-tdb2/pom.xml
- jena-text/pom.xml
- pom.xml
GitHub issue resolved #2336
Switch to JUnit5 and use junit-vintage-engine (JUnit4, JUnit3 compatibility)
`jena-serviceenhancer` does not seem to use org.xenei contract tests - dependency removed.
`org.xenei junit-contracts` is used by `jena-core`, `jena-permissions` and `jena-querybuilder`.
The last release was in 2018. It depends on JUnit 4.2.
----
> Update dependencies to include JUnit5 and use junit-vintage-engine

- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/AskBuilder.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/ConstructBuilder.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/DescribeBuilder.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/SelectBuilder.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/UpdateBuilder.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/clauses/DatasetClause.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/handlers/DatasetHandler.java
- jena-extras/jena-querybuilder/src/test/java/org/apache/jena/arq/querybuilder/handlers/DatasetHandlerTest.java
GitHub issue resolved #2358
Changes QueryBuilder `from()` and `fromNamed()` methods to accept Objects.
No documentation change required.
----
----
> Gh 2358 from() and fromNamed() take object

- jena-fuseki2/jena-fuseki-ui/src/services/mock/json-server.js
- jena-fuseki2/jena-fuseki-ui/src/views/dataset/Upload.vue
- jena-fuseki2/jena-fuseki-ui/src/views/manage/ExistingDatasets.vue
- jena-fuseki2/jena-fuseki-ui/tests/e2e/specs/upload.cy.js
GitHub issue resolved #2107
Display the statuses of file uploads near the top / visible area, so users do not need to scroll the page to track the progress of their uploads.
----
----
> GH-2107: Use a progress bar to show the overall upload status

- .github/pull_request_template.md
- jena-arq/src/main/java/org/apache/jena/riot/RDFParser.java
- jena-arq/src/main/java/org/apache/jena/riot/RIOT.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/rdfxml/rrx/ParserRDFXML_SAX.java
- jena-arq/src/main/java/org/apache/jena/sparql/sse/writers/SSEWriteLib.java
- jena-arq/src/main/java/org/apache/jena/update/UpdateAction.java
- jena-base/src/main/java/org/apache/jena/atlas/io/AWriter.java
- jena-base/src/main/java/org/apache/jena/atlas/io/AWriterBase.java
- jena-base/src/main/java/org/apache/jena/atlas/io/IOX.java
- jena-base/src/main/java/org/apache/jena/atlas/io/IndentedWriter.java
- jena-base/src/main/java/org/apache/jena/atlas/io/Writer2.java
- jena-core/src/test/java/org/apache/jena/rdfxml/xmlinput0/StAX2ModelTest.java
- jena-core/src/test/java/org/apache/jena/rdfxml/xmlinput1/TestsStAX2Model.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestFusekiShaclValidation.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/access/AbstractTestServiceDatasetAuth.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/access/TestPasswdOnly.java
- jena-integration-tests/src/test/java/org/apache/jena/test/rdfconnection/TestRDFConnectionFuseki.java
- jena-integration-tests/src/test/java/org/apache/jena/test/rdfconnection/TestRDFConnectionRemote.java
- jena-integration-tests/src/test/java/org/apache/jena/test/rdflink/TestRDFLinkHTTP.java
- jena-text/src/main/java/org/apache/jena/query/text/assembler/TextIndexLuceneAssembler.java
Some clearing up.
The biggest change is to undo the chaining style of the `AWriter` abstraction (a simplifer writer-like interface) and also used in settter for `IndentedWriter`.
The chaining was to allow setters like `setLineNumbers` and output functions `print` to chain:
```
AWriter out = IndentedWriter.stdout.clone().setLineNumbers(true);
out.println("foo").println("bar");
```
But this causes a lot of IDE warnings. The result of a chain-able method is `this` but the IDE does not know that fact. 
It looks to the IDE like a fresh AutoClosable resource and it suggests try-with-resource. Only the outer resource needs that.
Fortunately, this is a primarily internal class, the chaining was added recently at 5.0.0, and chaining has not been retro-applied much in the code base.
---
By …
> Miscellaneous cleaning up

- jena-fuseki2/jena-fuseki-ui/src/views/dataset/Upload.vue
GitHub issue resolved #2371  
Adds tooltips in case you have very long list and the text is not visible in the progress bars.
Here's a preview of the tooltip (dark tooltip, over one of the progress bars, mouse pointer not displayed).
----
----
> GH-2371: Add tooltip to progress bars (via title attr)

- jena-arq/src/main/java/org/apache/jena/sparql/expr/NodeValue.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/TestNodeValue.java
jena-arq NodeValue.makeNodeFloat(String) is supposed to construct a NodeValue with datatype XSDFloat. 
Instead, it currently constructs a NodeValue with datatype XSDDouble.
Updates NodeValue.makeNodeFloat(String) to construct a NodeValue with datatype XSDFloat.
Adds test TestNodeValue.float4() that confirms that makeNodeFloat(String) constructs a XSDFloat value.
----
> fix: NodeValue.makeNodeFloat(String) construct NodeValue with datatype XSDfloat

- jena-base/src/main/java/org/apache/jena/atlas/lib/StrUtils.java
- jena-base/src/test/java/org/apache/jena/atlas/lib/TestStrUtils.java
- jena-core/src/main/java/org/apache/jena/rdf/model/Resource.java
- jena-core/src/main/java/org/apache/jena/rdf/model/impl/Util.java
- jena-core/src/main/java/org/apache/jena/shared/impl/PrefixMappingImpl.java
- jena-core/src/main/java/org/apache/jena/util/SplitIRI.java
- jena-core/src/test/java/org/apache/jena/util/TestPackage_util.java
- jena-core/src/test/java/org/apache/jena/util/TestSplitIRI_Display.java
- jena-core/src/test/java/org/apache/jena/util/TestSplitIRI_TTL.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/handlers/DatasetHandler.java
- pom.xml
A number of clean up changes, accumulated recently such as from investigating user questions.
* jena-querybuilder - fix compiler warning (this time, in a way that is compatible with javadoc production)
* `SplitIRI` - move XML related code into `SplitIRI`, split up display split tests
* Use Junit5 BOM
* White space normalization
----
> Accumulated code clean up

- jena-arq/src/main/java/org/apache/jena/riot/system/StreamRDFLib.java
- jena-arq/src/main/java/org/apache/jena/sparql/graph/GraphUnionRead.java
- jena-arq/src/test/java/org/apache/jena/sparql/graph/TestGraphUnionRead.java
GitHub issue resolved #2383
Protect `GraphUnionRead` against unacceptable prefix mappings.
----
----
> GH-2383: Protect GraphUnionRead against unacceptable prefix mappings

- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/FusekiServer.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/access/AbstractTestFusekiSecurityAssembler.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/access/AbstractTestServiceDatasetAuth.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/access/TestServiceDataAuthBuild.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/access/TestServiceDataAuthConfig.java
This is a precursor for #2399 - an incremental Jetty update. That PR triggers a problem, caught by the Fuseki main test suite, with relative filenames for serving static content. Solution: resolve the filename. This works the previous Jetty as well. This work on windows - Jetty adapts to `c:` style file names.
This PR also changes the test suite for better stability on MS Windows by avoiding a Fuseki server shared between tests in the same suite (found via running the GH Windows build).
----
> Resolve the base directory for static content

- jena-fuseki2/jena-fuseki-ui/vite.config.js
GitHub issue resolved #2392
Use `./` for Vite.
----
----
> GH-2392: Use ./ as base for Vite

- jena-core/src/main/java/org/apache/jena/datatypes/xsd/XSDbase64Binary.java
- jena-core/src/main/java/org/apache/jena/reasoner/rulesys/builtins/MakeSkolem.java
- jena-integration-tests/src/test/java/org/apache/jena/http/AuthBearerTestLib.java
GitHub issue resolved # N/A
Updating repo to use the Util's Base 64 class (introduced in JDK 8) which has greater performance than Apache Commons Codec.
----
----
> Migrating Base 64 operations from Apache Commons Codec to Util package.

- jena-extras/jena-querybuilder/pom.xml
- jena-iri/pom.xml
- jena-permissions/pom.xml
- pom.xml
Update the project parent Apache POM from v31 to v32.
This requires fixes in jena-permissions and jena-querybuilder around the "attach-javadocs" step.
The fix is to switch from depending on apache-jena-libs:pom to jena-arq:jar. The "pom" part triggers an error:
```
...
apache-jena-libs-5.1.0-SNAPSHOT.pom' not allowed on the path, only outputDirectories and jars are accepted 
```
----
> Bump org.apache.apache parent POM from 31 to 32

- jena-base/src/main/java/org/apache/jena/atlas/logging/LogCtl.java
- jena-base/src/main/java/org/apache/jena/atlas/logging/LogCtlLog4j2.java
- jena-cmds/pom.xml
- jena-cmds/src/test/java/jena/Test_schemagen.java
No functionality changes.
This is tidying the log4j control code, mainly to be careful to use the log4j API/SPI and not touch internals.
It is not clear how to test this in a way that does not risk disturbing logging in all other testing.
The code is changing the global, shared log4j setup.
Use of Log4j2 with Jena, including Fuseki, is optional. Any org.slf4j provider should work.
log4j2 is used by jena-cmds.
----
> Clear-up LogCtlLog4j2

- jena-arq/src/main/java/org/apache/jena/riot/RDFParser.java
- jena-arq/src/test/java/org/apache/jena/riot/TestRDFParser.java
Calling `RDFParser.toDatasetGraph()` creates a fresh transactional `DatasetGraph` and then proceeds to using it without transactions meaning every triple/quad output is a separate auto-committed write transaction. This behaviour is changed to place the entire parsing process inside a write transaction to boost performance.
GitHub issue resolved #2400
This is a combination of proposed solution 2 and 3 from #2400. The code is changed to use the freshly minted `Dataset` or `DatasetGraph` inside of a transaction and the corresponding Javadoc on the `toDataset()` and `toDatasetGraph()` methods note that supplying your desired implementation of those interfaces to the relevant `parse()` method may be preferable.
With this chance performance across the test cases is improved:
Looks like there is …
> GH-2400: RDFParser.toDatasetGraph() transactions

- jena-arq/src/main/java/org/apache/jena/sparql/exec/QueryExecDataset.java
- jena-arq/src/main/java/org/apache/jena/sparql/exec/QueryExecutionCompat.java
- jena-arq/src/test/java/org/apache/jena/sparql/api/TestQueryExecutionCancel.java
GitHub issue resolved #2394
Pull request Description: Cancel signal is moved to class level and is set to true when abort is called.
----
----
> Fix for query exec when abort is called before exec

- jena-core/src/main/java/org/apache/jena/reasoner/rulesys/impl/LPBRuleEngine.java
The collection of active interpreters is removed from randomly - as each one completes. This results in random removals from the linked list, a O(n) operation.
As the number of active interpreters grows, so does this time. This happens within a synchronized block, which can stall the work of other threads when a model is shared across threads for reads.
GitHub issue resolved #2382 
----
----
> GH-2382 - Track engine instances in a Set rather than a List

- jena-arq/src/main/java/org/apache/jena/riot/RDFParser.java
- jena-arq/src/test/java/org/apache/jena/riot/TS_RiotGeneral.java
- jena-arq/src/test/java/org/apache/jena/riot/TestRDFParser.java
- jena-cmds/pom.xml
- jena-core/pom.xml
- jena-extras/jena-querybuilder/pom.xml
- jena-fuseki2/jena-fuseki-main/sparqler/pages/data-validator.html
- pom.xml
GitHub issue resolved #2433
and other POM tidying
+ TestRDFParser - avoid output tests; run test suite only once.
----
> Tidy dependencies

- jena-arq/src/main/java/org/apache/jena/query/QueryExecutionFactory.java
- jena-arq/src/main/java/org/apache/jena/sparql/modify/UpdateEngineWorker.java
- jena-arq/src/main/java/org/apache/jena/update/UpdateAction.java
Fix places where the "suppress warnings" has changed.
----
> GH-2435: Suppress both 'deprecation' and 'removal' warnings

- jena-fuseki2/jena-fuseki-core/pom.xml
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/CrossOriginFilter.java
- jena-fuseki2/jena-fuseki-main/pom.xml
- pom.xml
This resolves #2443
This resolves #2444
Copy `CrossOriginFilter` from the source of the Eclipse Jetty 12.0.8 release.
Also copy some util code that `CrossOriginFilter` uses.
`CrossOriginFilter` tests continue to pass unchanged.
Change the dependency of `jena-fuseki-core` to be on `jakara-servlet-api` so that Jetty is not a dependency of `jena-fuseki-core`
----
> Update CrossOriginFilter; remove dependency of jena-fuseki-core on Jetty artifacts.

- jena-fuseki2/jena-fuseki-ui/package.json
- jena-fuseki2/jena-fuseki-ui/yarn.lock
See #2456
Temporary fix by setting the version of vite-plugin-istanbul to 6.0.0 exactly.
----
> GH-2456: Revert to vite-plugin-istanbul 6.0.0

- jena-arq/src/main/java/org/apache/jena/riot/lang/rdfxml/RRX.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/rdfxml/rrx/ParserRDFXML_SAX.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/rdfxml/rrx/ReaderRDFXML_SAX.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/rdfxml/rrx_stax_ev/ParserRDFXML_StAX_EV.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/rdfxml/rrx_stax_ev/ReaderRDFXML_StAX_EV.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/rdfxml/rrx_stax_sr/ParserRDFXML_StAX_SR.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/rdfxml/rrx_stax_sr/ReaderRDFXML_StAX_SR.java
The RIOT RRX Readers are public - the parsers themselves should be package scoped. 
`ReaderRDFXML_SAX` is the RRX parser used for RDF/XML.
Also - fix some " internal" file extensions.
----
> Convert RRX parser classes to package visible

- jena-arq/src/main/java/org/apache/jena/http/HttpLib.java
- jena-fuseki2/jena-fuseki-core/src/test/java/org/apache/jena/fuseki/TS_FusekiCore.java
- jena-fuseki2/jena-fuseki-core/src/test/java/org/apache/jena/fuseki/servlets/TestCrossOriginFilterMock.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/FusekiServer.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TS_FusekiMain.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestCrossOriginFilter.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestFusekiMainCmd.java
Put in integration tests for the CORS filter in one place. The integration tests capture embedded use and default settings.
Keep the jena-fuseki-core mocked tests in place (renamed). 
Put back `FusekiServer.Builder. enableCors(boolean withCORS)`
----
> Integration tests for CORS

- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TS_FusekiMain.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestCrossOriginFilter.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestFusekiMainCmdArguments.java
This is a build fix.
There was a hidden problem with some tests (failing to release an allocated server on a fixed port) that 3cdc8cf9487b triggers.
This PR corrects the tests failing to clearup completely and also makes the tests that found this issue robust.
----
> Ensure tests stop any FusekiServer

- jena-cmds/pom.xml
- jena-integration-tests/pom.xml
GitHub issue resolved #2465
Fixes a problem introduced in a5638d2371
* jena-cmds to produce a sources jar (for the download)
* jena-intregation-tests does not use jena-cmds:test  - remove from dependencies
----
> GH-2465: Produce jena-cmds source jar. Correct dependencies

- .github/dependabot.yml
GitHub issue resolved #2475
Assuming naming the day means "run very early morning":
Monday: maven
Tuesday: github actions
Wednesday: npm
----
> GH-2475: Specify the day for weekly schedules

- jena-arq/src/main/java/org/apache/jena/sparql/core/Transactional.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/server/DataService.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/server/OperationRegistry.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/GSP_RW.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/HttpAction.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/PatchApply.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/SPARQL_Update.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/UploadRDF.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestFusekiCustomOperation.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestFusekiMainCmdArguments.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestFusekiStdSetup.java
- jena-rdfpatch/src/main/java/org/apache/jena/rdfpatch/system/DatasetGraphChanges.java
GitHub issue resolved #2506
To keep the server stable and running, implementations of Fuseki operations must follow the HttpAction lifecycle for transactions.
This PR fixes one problem (found in code review, not as a live bug), and puts in consistency checking.
The consistency checks did show some incorrect use of the  HttpAction lifecycle.
There are also changes to remove other, unrelated logging messages output during Fuseki tests.
The function to apply a patch is moved to the Fuseki servlet package.
----
> Improve HttpAction lifecycle

- jena-arq/pom.xml
- jena-arq/src/main/java/org/apache/jena/riot/RDFLanguages.java
- jena-arq/src/main/java/org/apache/jena/riot/RDFWriterRegistry.java
- jena-arq/src/main/java/org/apache/jena/riot/resultset/ResultSetLang.java
- jena-arq/src/main/java/org/apache/jena/riot/resultset/ResultSetReaderRegistry.java
- jena-arq/src/main/java/org/apache/jena/riot/resultset/ResultSetWriterRegistry.java
- jena-arq/src/test/java/org/apache/jena/riot/resultset/TS_ResultSetRIOT.java
- jena-arq/src/test/java/org/apache/jena/riot/resultset/TestResultSetLang.java
Adds registry functionality to ResultSetLang
----
> Registry for ResultSetLang

- jena-cmds/src/test/java/jena/Test_schemagen.java
This stops calls of the compiler printing
```
Note: Annotation processing is enabled because one or more processors were found
on the class path. A future release of javac may disable annotation processing
unless at least one processor is specified by name (-processor), or a search
path is specified (--processor-path, --processor-module-path), or annotation
processing is enabled explicitly (-proc:only, -proc:full).
Use -Xlint:-options to suppress this message.
Use -proc:none to disable annotation processing.
```
numerous time in the jena-cmds tests when using Java21 as the build compiler.
`Test_schemagen` invokes the java compiler to check output is correct Java
----
By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the …
> Add -proc:none to call of Java compiler (Test_schemagen)

- jena-ontapi/src/main/java/org/apache/jena/ontapi/OntJenaException.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/OntGraphModelImpl.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/factories/OWL2ObjectFactories.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/factories/OntClasses.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/objects/OntClassImpl.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/objects/OntIndividualImpl.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/objects/OntSimpleClassImpl.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/model/OntClass.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/model/OntIndividual.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/model/OntObjectProperty.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/model/OntRelationalProperty.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/OntModelOWL2QLSpecTest.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/OntModelOWL2RLSpecTest.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/StreamsTest.java
- add `OntClass#canAsSubClass`, `OntClass#canAsSuperClass`, `OntClass#canAsAssertionClass`, `OntClass#canAsDisjointClass`, `OntClass#canAsEquivalentClass`
- make `OntClass#as*Class` throw exception if corresponding `OntClass#canAs*Class` returns false
- fix few mistakes related to RL/QL profiles
----
----
> GH-2487: add OntClass#canAs*Class methods + fix some mistakes

- jena-base/src/main/java/org/apache/jena/atlas/lib/CacheFactory.java
- jena-base/src/main/java/org/apache/jena/atlas/lib/cache/CacheCaffeine.java
- jena-tdb1/src/main/java/org/apache/jena/tdb1/setup/DatasetBuilderStd.java
- jena-tdb1/src/main/java/org/apache/jena/tdb1/setup/StoreParams.java
- jena-tdb1/src/main/java/org/apache/jena/tdb1/setup/StoreParamsBuilder.java
- jena-tdb1/src/main/java/org/apache/jena/tdb1/setup/StoreParamsCodec.java
- jena-tdb1/src/main/java/org/apache/jena/tdb1/setup/StoreParamsConst.java
- jena-tdb1/src/main/java/org/apache/jena/tdb1/setup/StoreParamsDynamic.java
- jena-tdb1/src/main/java/org/apache/jena/tdb1/store/nodetable/NodeTableCache.java
- jena-tdb1/src/main/java/org/apache/jena/tdb1/sys/SystemTDB.java
- jena-tdb1/src/test/java/org/apache/jena/tdb1/setup/TestStoreParams.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/params/StoreParams.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/params/StoreParamsBuilder.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/params/StoreParamsCodec.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/params/StoreParamsConst.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/params/StoreParamsDynamic.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/store/TDB2StorageBuilder.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/store/nodetable/NodeTableCache.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/sys/SystemTDB.java
- jena-tdb2/src/test/java/org/apache/jena/tdb2/setup/TestStoreParams.java
Issue: https://issues.apache.org/jira/projects/JENA/issues/JENA-2354
With TDB 4.9.0, node caches change from Guava to Caffeine and are being assigned an initial capacity of 0.25 * their maximum size, increasing the memory footprint. This PR makes the initial capacity factor configurable via StoreParams.
----
----
> JENA-2354 Make initial size of node caches configurable via StoreParams

- apache-jena-libs/pom.xml
- apache-jena/pom.xml
- jena-bom/pom.xml
- jena-cmds/pom.xml
- jena-tdb1/src/main/java/org/apache/jena/tdb1/setup/StoreParamsDynamic.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/params/StoreParamsDynamic.java
Put `jena-ontapi` in the `apache-jena-libs` and `apache-jena` binary distributions. 
Include in `jena-bom`.
Fix a javadoc warning.
----
> GH-2160: Include jena-ontapi in distributions

- jena-ontapi/src/main/java/org/apache/jena/ontapi/utils/OntModels.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/OntModelsTest.java
add `OntModels#namedHierarchyRoots` - modified copy-paste from legacy `OntTools`
----
----
> GH-2487: add OntModels#namedHierarchyRoots

- jena-arq/pom.xml
- jena-arq/src/main/java/org/apache/jena/riot/rowset/RowSetReader.java
- jena-arq/src/main/java/org/apache/jena/riot/rowset/RowSetReaderRegistry.java
- jena-arq/src/test/java/org/apache/jena/riot/resultset/TS_ResultSetRIOT.java
- jena-arq/src/test/java/org/apache/jena/riot/rowset/TS_RowSetRIOT.java
- jena-arq/src/test/java/org/apache/jena/riot/rowset/rw/TestRowSetReader.java
- jena-core/src/main/java/org/apache/jena/graph/NodeFactory.java
- jena-core/src/test/java/org/apache/jena/graph/test/TestNodeEdgeCases.java
- jena-core/src/test/java/org/apache/jena/graph/test/TestPackage_graph.java
GitHub issue resolved #2555
----
> GH-2555: Allow ^^rdf:langString in result sets

- jena-arq/src/main/java/org/apache/jena/sparql/engine/main/JoinClassifier.java
- jena-arq/src/test/java/org/apache/jena/sparql/algebra/TestClassify.java
GitHub issue resolved #2535 
Pull request Description: Update to JoinClassifier such that joins between tables are not linearized.
The downside is, that this PR adds extra passes over the algebra tree to JoinClassifier in order to check for the operand types.
----
----
> GH-2535: Always use hash joins when joining VALUES blocks

- jena-fuseki2/jena-fuseki-ui/src/views/dataset/Query.vue
- jena-fuseki2/jena-fuseki-ui/tests/unit/views/dataset/query.vue.spec.js
GitHub issue resolved #1611 
The type is first set on change, due to being updated on the watch phase. Adding it to requestConfig sets it to turtle initially. contentTypeGraph variable was already set as the initial value for turtle, so reusing variable.
Have also changed to other serializations sucessfully.
----
> GH-1611: supply initial value for acceptHeaderGraph to requestConfig

- jena-fuseki2/jena-fuseki-fulljar/pom.xml
- jena-fuseki2/jena-fuseki-webapp/src/main/java/org/apache/jena/fuseki/cmd/FusekiCmd.java
The first release attempt for jena 5.1.0 failed in the checking.
The fuseki-server script (the combined jar) failed because the jar file had the wrong entry point name.
Some clean-up during 5.1.0 development wrongly renamed a class.
----
> Correct the entry point to run in the combined jar

- jena-arq/src/main/java/org/apache/jena/http/sys/ExecHTTPBuilder.java
- jena-arq/src/main/java/org/apache/jena/http/sys/ExecUpdateHTTPBuilder.java
- jena-arq/src/main/java/org/apache/jena/query/QueryExecutionBuilder.java
- jena-arq/src/main/java/org/apache/jena/query/QueryExecutionDatasetBuilder.java
- jena-arq/src/main/java/org/apache/jena/sparql/exec/QueryExecBuilder.java
- jena-arq/src/main/java/org/apache/jena/sparql/exec/QueryExecBuilderAdapter.java
- jena-arq/src/main/java/org/apache/jena/sparql/exec/QueryExecDatasetBuilder.java
- jena-arq/src/main/java/org/apache/jena/sparql/exec/QueryExecutionBuilderAdapter.java
- jena-arq/src/main/java/org/apache/jena/sparql/exec/UpdateExecBuilder.java
- jena-arq/src/main/java/org/apache/jena/sparql/exec/UpdateExecBuilderAdapter.java
- jena-arq/src/main/java/org/apache/jena/sparql/exec/UpdateExecDatasetBuilder.java
- jena-arq/src/main/java/org/apache/jena/sparql/exec/UpdateExecutionBuilderAdapter.java
- jena-arq/src/main/java/org/apache/jena/sparql/exec/http/UpdateExecHTTPBuilder.java
- jena-arq/src/main/java/org/apache/jena/sparql/exec/http/UpdateExecutionHTTPBuilder.java
- jena-arq/src/main/java/org/apache/jena/update/UpdateExecutionBuilder.java
- jena-arq/src/main/java/org/apache/jena/update/UpdateExecutionDatasetBuilder.java
- jena-integration-tests/src/test/java/org/apache/jena/test/rdfconnection/TestRDFConnectionRemote.java
- jena-rdfconnection/src/main/java/org/apache/jena/rdfconnection/RDFConnectionWrapper.java
- jena-rdfconnection/src/main/java/org/apache/jena/rdflink/RDFLinkHTTP.java
- jena-rdfconnection/src/main/java/org/apache/jena/rdflink/RDFLinkHTTPBuilder.java
- jena-rdfconnection/src/main/java/org/apache/jena/rdflink/RDFLinkModular.java
- jena-rdfconnection/src/test/java/org/apache/jena/rdfconnection/AbstractTestRDFConnection.java
GitHub issue resolved #2580 
Pull request Description: Added `parseCheck` flag to query and update exec builders in order to give users control over how to deal with strings passed to `QueryExecBuilder.query(String)` and `UpdateExecBuilder.update(String)`.
----
----
> GH-2580: Added parseCheck flag to query and update exec builders.

- jena-arq/src/main/java/org/apache/jena/riot/system/JenaTitanium.java
- jena-arq/src/test/java/org/apache/jena/system/TestJenaTitanium.java
GitHub issue resolved #2578
Pull request Description: This commit adds a `Quad.isTriple()` check when writing JSON-LD files, to cover the case where we have a "triple in quad". I've also added a test to check if this works. The test fails on the current main branch version of Jena.
----
----
> GH-2578: Fix Quad.isTriple() handling in JenaTitanium

- jena-arq/pom.xml
Explicitly declares the dependency as test scope to avoid it leaking into compile scope unneccesarily
GitHub issue resolved #2593
----
----
> GH-2593: Fix JUnit dependency leaking to compile scope

- jena-arq/src/main/java/org/apache/jena/riot/writer/TriGWriter.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetGraphMap.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetGraphTriplesQuads.java
- jena-arq/src/test/java/org/apache/jena/sparql/core/AbstractDatasetGraphTests.java
- jena-db/jena-dboe-storage/src/main/java/org/apache/jena/dboe/storage/system/DatasetGraphStorage.java
Adds to issue #2578
Fixes for:
* `TriGWriter` -- NPE when the graph name is null.
* `DatasetGraphMap` -- map null graph name to the default graph.
----
> GH-2578: Fix for null graph name in DatasetGraphMap and TriGWriter

- jena-fuseki2/jena-fuseki-ui/package.json
GitHub issue resolved #2611
Pull request Description: see #2611
----
> GH-2611: Add --pool=threads to vitest run

- jena-fuseki2/jena-fuseki-ui/package.json
GitHub issue resolved #2346
Hi,
My old old thinkpad finally started to have some issues, so I'm setting up a new laptop, and thought it'd be good to clean up some older UI issues like this one.
I installed Node LTS (20) with nvm, then enabled corepack (to get yarn), and did a yarn install. Very first project I am building on this new framework laptop. Did not get the yarn test:unit tests (I think someone updated vite and now the issue is gone :pray:).
The warning was fixed automatically by yarn install, so I just committed it.
It also fixed the spaces around the colon for the windows script command.
----
By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the …
> GH-2346: Fix warning during first yarn install

- jena-arq/src/test/java/org/apache/jena/riot/writer/TS_RiotWriter.java
- jena-arq/src/test/java/org/apache/jena/riot/writer/TestWriterRDFXML.java
- jena-arq/src/test/java/org/apache/jena/riot/writer/TestWriterRDFXML_Properties.java
- jena-core/src/main/java/org/apache/jena/rdfxml/xmloutput/impl/Unparser.java
GitHub issue resolved #2619
Pull request Description: see #2619.
This was a break at Jena4 -> Jena5.
----
> GH-2619: Fix writing invalid rdf:XMLLiterals

- jena-ontapi/src/main/java/org/apache/jena/ontapi/GraphRepository.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/repositories/DocumentGraphRepository.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/repositories/PersistentGraphRepository.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/DocumentGraphRepositoryTest.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/OntUnionGraphRepositoryTest.java
GitHub issue resolved #2628
Refactoring of `DocumentGraphRepository`; allow multiple mappings
----
----
> GH-2628: DocumentGraphRepository -- allow multiple mappings, + minor changes

- jena-ontapi/src/main/java/org/apache/jena/ontapi/GraphRepository.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/OntModelControls.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/OntModelFactory.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/OntSpecification.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/HierarchySupport.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/OntGraphModelImpl.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/objects/OntObjectImpl.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/model/OntClass.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/model/OntModel.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/model/OntProperty.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/model/OntResource.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/OntClassDeclaredPropertiesTest.java
GitHub issue resolved #2631
javadocs cleanup
----
----
> GH-2631: cleanup javadocs (remove references to legacy OntModel)

- jena-ontapi/src/main/java/org/apache/jena/ontapi/common/OntPersonalities.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/OntGraphModelImpl.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/factories/OWL2ObjectFactories.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/factories/OntDisjoints.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/objects/OntClassImpl.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/objects/OntDisjointImpl.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/model/OntClass.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/model/OntDisjoint.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/OntModelOWL2ELSpecTest.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/OntModelOWL2QLSpecTest.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/OntModelOWL2RLSpecTest.java
GitHub issue resolved #2657
- OntDisjoint.Classes should only contain subClassExpressions
- subject of hasKey axiom should be subClassExpression
----
----
> GH-2657: fix several defects in profiles support (RL, QL):

- jena-ontapi/src/main/java/org/apache/jena/ontapi/common/OntPersonalities.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/OntGraphModelImpl.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/factories/OWL1ObjectFactories.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/factories/OWL2ObjectFactories.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/factories/OntDisjoints.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/OntModelOWL2ELSpecTest.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/OntModelOWL2QLSpecTest.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/OntModelOWL2RLSpecTest.java
GitHub issue resolved #2673
Now OntDisjoints does not allow less than two members for EL, QL, RL profiles, DL profile unchanged
----
----
> GH-2673: [ontapi] OntDisjoints - require more than one member (for EL QL, RL)

- jena-arq/src/main/java/org/apache/jena/sparql/graph/GraphFactory.java
- jena-cmds/src/main/java/arq/rdfdiff.java
- jena-core/src/main/java/org/apache/jena/graph/GraphMemFactory.java
- jena-core/src/main/java/org/apache/jena/rdf/model/ModelFactory.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/system/GraphLoadUtils.java
Better handling of the same term/same value choices of graph. This not a change, it is cleaning up around the Jena5 changes to be clearer.
The Model API, via ModelFactory.createDefault Model, is same-value which gives the most legacy compatibility.
"same-term" is the default at the graph level including use in Fuseki .
`rdfdiff` is same-term, as is `Graph.isIsomorphic`.
----
----
> Clear-up same-term/same-value graphs for the Model API

- jena-arq/src/main/java/org/apache/jena/cdt/parser/JavaCharStream.java
- jena-arq/src/main/java/org/apache/jena/sparql/lang/sparql_12/JavaCharStream.java
- jena-cmds/src/main/java/jena/schemagen.java
- jena-core/src/main/java/org/apache/jena/ontology/impl/AllDifferentImpl.java
- jena-core/src/main/java/org/apache/jena/ontology/impl/OntResourceImpl.java
- jena-core/src/main/java/org/apache/jena/rdf/model/impl/RDFListImpl.java
- jena-core/src/main/java/org/apache/jena/rdfxml/xmloutput/impl/Unparser.java
- jena-core/src/main/java/org/apache/jena/reasoner/rulesys/impl/BBRuleContext.java
- jena-core/src/main/java/org/apache/jena/reasoner/rulesys/impl/BFRuleContext.java
- jena-core/src/main/java/org/apache/jena/reasoner/rulesys/impl/RETERuleContext.java
- jena-core/src/test/java/org/apache/jena/rdf/model/test/TestRDFNodes.java
- jena-iri/src/main/java/org/apache/jena/iri/impl/IRIFactoryImpl.java
Clean warnings due to:
- Eclipse warning detection has been imporved/fixed. The code has some unnecessary casts.
- Rebuilt JavaCharStream (from JavaCC) has some javadoc warnings in the maven build.
----
> Clean warnings

- jena-arq/src/main/java/org/apache/jena/riot/lang/LangJSONLD11.java
While investigating #2739, I found that errors from Titanium can be wrapped exceptions with where the cause is also a Titanium exception and more meaningful.
This PR adds unwrapping the cause in that case.
----
> Unwrap Titanium exceptions

- jena-base/src/main/java/org/apache/jena/atlas/lib/Cache.java
- jena-base/src/main/java/org/apache/jena/atlas/lib/CacheFactory.java
- jena-base/src/main/java/org/apache/jena/atlas/lib/cache/CacheSimple.java
- jena-base/src/test/java/org/apache/jena/atlas/lib/cache/TestCacheSimple.java
- jena-benchmarks/jena-benchmarks-jmh/pom.xml
- jena-benchmarks/jena-benchmarks-jmh/src/test/java/org/apache/jena/atlas/lib/cache/TestCaches.java
- jena-benchmarks/jena-benchmarks-shadedJena510/pom.xml
- jena-benchmarks/pom.xml
Slight performance improvements to org.apache.jena.atlas.lib.cache.CacheSimple:
- optimized bit-operations by using a cache size, that is always a power of 2
- removed already BiConsumer<K, V> dropHandler), which is used nowhere
- added more tests for CacheSimple
- fixed a small bug, where putting a key with the same hash as an existing one does not overridde the existing entry, when the values are equal.
- added new module jena-benchmarks-shadedJena510 to be able to perform regression tests againt the previous release
- added JHM test org.apache.jena.atlas.lib.cache.TestCaches in jena-benchmarks-jmh
- added more detailed javadoc comments to Cache interface
Benchmark results:
```
Benchmark                                           (param0_GraphUri)  (param1_Cache)  Mode  Cnt  Score …
```
> GH-2738: Slight performance improvements to CacheSimple

- jena-arq/src/main/java/org/apache/jena/riot/RDFParser.java
- jena-arq/src/main/java/org/apache/jena/riot/RDFParserBuilder.java
- jena-integration-tests/src/test/java/org/apache/jena/http/TestHttpRDFParserBuilder.java
GitHub issue resolved #2756
- made org.apache.jena.riot.RDFParserBuilder#httpHeader available again by uncommenting it
- moved initalization of httpClient  with HttpEnv.getDftHttpClient() from org.apache.jena.riot.RDFParserBuilder#build to org.apache.jena.riot.RDFParser#openTypedInputStream in the case when the RDFParserBuilder has not been initialized with a custom httpClient. That way, it HttpEnv is not necessarily initialized when reading files but only when needed.
- added org.apache.jena.http.TestHttpRDFParserBuilder in jena-integration-tests
----
- no documentation changes and updates for the [Apache Jena website](https://github.com/apache/jena-site/) are needed
By submitting this pull request, I acknowledge that I am making a contribution to the Apache …
> GH-2756: Lazy initialization of HttpClient in RDFParser - when no custom HttpClient is provided by RDFParserBuilder

- jena-arq/src/main/java/org/apache/jena/riot/lang/rdfxml/SysRRX.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/rdfxml/rrx/ParserRRX_SAX.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/rdfxml/rrx_stax_ev/ParserRRX_StAX_EV.java
- jena-arq/src/main/java/org/apache/jena/riot/lang/rdfxml/rrx_stax_sr/ParserRRX_StAX_SR.java
- jena-arq/src/main/java/org/apache/jena/riot/system/ParserProfile.java
- jena-arq/src/main/java/org/apache/jena/riot/system/ParserProfileStd.java
- jena-arq/src/main/java/org/apache/jena/riot/system/ParserProfileWrapper.java
- jena-arq/src/test/java/org/apache/jena/system/TestReadXML.java
- jena-benchmarks/jena-benchmarks-jmh/src/test/java/org/apache/jena/riot/lang/rdfxml/TestXMLParser.java
- jena-core/src/main/java/org/apache/jena/util/JenaXMLInput.java
Faster parsing of RDF/XML by avoiding duplicated resolving of IRIs and adding cache for IRIx in parsers
(Parsers: RRX.RDFXML_SAX, RRX.RDFXML_StAX_ev, RRX.RDFXML_StAX_sr )
GitHub issue resolved #2740
- added "public Node createURI(IRIx iriX, ...);" to the ParserProfile, which simply uses the given IRI instead of resolving it again.
- adding general IRIx caching (org.apache.jena.atlas.lib.cache.CacheSimple) in the parsers where the already cached org.apache.jena.riot.system.ParserProfileStd#resolver is not applicable
- removed unused code and variables from ParserRRX_StAX_SR and ParserRRX_StAX_EV
- added `org.apache.jena.riot.lang.rdfxml.TestXMLParser` in jena-benchmarks-jmh
Benchmark results:
```
Benchmark …
```
> GH-2740: Faster parsing of RDF/XML

- jena-arq/src/main/java/org/apache/jena/riot/tokens/TokenizerText.java
- jena-arq/src/test/java/org/apache/jena/riot/TestTurtleWriterPretty.java
- jena-arq/src/test/java/org/apache/jena/riot/tokens/TestTokenizerText.java
- jena-core/src/main/java/org/apache/jena/irix/Chars3986.java
GitHub issue resolved #2766
Due to Java bytes to string conversion using the JDK conversion, Jena can't tell the difference between multibyte characters translated to surrogates (legal) and surrogates actually in the in UTF-8 (illegal - UTF-8 does not allow surrogates).
The test changes are bug fixes. They are detecting warnings on the replacement character but that is explicitly handled, and allowed, controlled by a flag, further up.
A deep fix might be possible - but it involves our own UTF-8 decoder and will need careful assessment of the performance impact. 
----
By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the [Contributor's …
> GH-2766: Don't warn on surrogates in IRIs

- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/OntGraphModelImpl.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/factories/OWL2ObjectFactories.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/factories/OntDisjoints.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/OntModelMiscTest.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/OntModelOWL1SpecsTest.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/OntModelOWL2ELSpecTest.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/OntModelOWL2QLSpecTest.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/OntModelOWL2RLSpecTest.java
GitHub issue resolved #2783
do not allow `OntDisjoint`s with no items
----
----
> GH-2783: [ontapi] do not allow OntDisjoints with no items

- jena-core/src/main/java/org/apache/jena/datatypes/TypeMapper.java
GitHub issue resolved #2795
Fixed a race condition in user-defined datatype registration. This change only touches the user-friendly `getSafeTypeByName` and does not change anything from the user's perspective (other than fixing the race condition). The `registerDatatype` method is left as-is, to allow for overriding datatype registrations if someone really wants to.
I've added some notes to `registerDatatype` and `unregisterDatatype` that it they have good "shoot-yourself-in-the-foot-with-a-bazooka" potential.
----
----
See the …
> GH-2795: Fix race condition in datatype registration

- .github/workflows/maven.yml
- jena-text/pom.xml
GitHub issue resolved #2533
Add different build arguments based on the running JVM version to minimize lucene warnings during build
This is based on how tests are being run in Apache Lucene (in gradle) where they check for java version and add args if >=21
but translated-ish to maven.
https://github.com/apache/lucene/blob/1faf33a02afd610c90ffa8685b1675f9d1c24b0e/gradle/testing/defaults-tests.gradle#L131
----
----
> Warnings lucene

- jena-base/src/main/java/org/apache/jena/atlas/lib/cache/CacheSimple.java
- jena-base/src/test/java/org/apache/jena/atlas/lib/cache/TestCacheSimple.java
GitHub issue resolved #2802
Call `CacheSimple.remove` if the `put` value is null.
----
> GH-2802: Remove only if same key

- jena-core/src/main/java/org/apache/jena/datatypes/BaseDatatype.java
- jena-core/src/test/java/org/apache/jena/datatypes/TestDatatypes.java
GitHub issue resolved #2808
- Added implementations for `org.apache.jena.datatypes.BaseDatatype#equals` and `#hashCode` based on `RDFDatatype.getURI`, aligning with the principle: "Same URI, same datatype" for RDF datatypes.
-  Added corresponding tests in `org.apache.jena.datatypes.TestDatatypes` to verify equality and hash code behavior.
----
- no Documentation change and no updates are needed for the [Apache Jena website](https://github.com/apache/jena-site/)
---- …
> GH-2808: Implemented Object#equals and #hashCode in BaseDatatype

- jena-core/src/main/java/org/apache/jena/sys/JenaSystem.java
Use the lazy holder pattern to perform system initialization.
Set `JenaSystem.initialized" flag early to avoid deadlocks.
----
> GH-2787: Use lazy holder pattern for system initialization

- pom.xml
Add `jena-iri3986` to the `<modules>`
(got lost in a rebase preparing for the merge)
----
> GH-2800: Include jena-iri3986 in maven modules

- jena-arq/src/main/java/org/apache/jena/riot/tokens/TokenizerText.java
- jena-arq/src/test/java/org/apache/jena/riot/tokens/TestTokenizerText.java
- jena-base/src/main/java/org/apache/jena/atlas/lib/Chars.java
GitHub issue resolved #2826
----
> GH-2826: Disallow raw CR in single quoted string

- jena-fuseki2/jena-fuseki-ui/pom.xml
This adds a profile that skips the UI tests.
Currently, the build fails on ASF Jenkins because many AFS Jenkins host nodes are older LTS Ubuntu and don't have the necessary dependencies installed + some dependencies also need updated system libraries.
I haven't made progress on a containerized build. 
The advantage of the ASF builds is that that have all the Java versions. There are changes  in the java world where it would be good to have builds running on the latest (non-LTS) java.
A hopefully temporary profile that builds the UI but does not run the tests would help keeping the development snapshot current and give builds using latest Java.
----
By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and …
> Profile to skip UI tests

- jena-core/src/main/java/org/apache/jena/mem/SparseArraySpliterator.java
- jena-core/src/main/java/org/apache/jena/mem/SparseArraySubSpliterator.java
- jena-core/src/main/java/org/apache/jena/rdf/model/RDFList.java
- jena-core/src/main/java/org/apache/jena/rdf/model/impl/RDFListImpl.java
- jena-core/src/main/java/org/apache/jena/rdfxml/xmlinput0/NTriple.java
- jena-extras/jena-querybuilder/src/main/java/org/apache/jena/arq/querybuilder/UpdateBuilder.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/auth/Auth.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/build/FusekiConfig.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/ActionExecLib.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/ActionLib.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/ActionServicePlaceholder.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/HttpAction.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/SPARQL_QueryDataset.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/ServletOps.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/prefixes/ActionProcPrefixes.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/system/DataUploader.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/system/FusekiLogging.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/system/FusekiNetLib.java
- jena-iri3986/pom.xml
- jena-iri3986/src/main/java/module-info.java
- jena-iri3986/src/main/java/org/apache/jena/rfc3986/IRI3986.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/loader/LoaderFactory.java
- pom.xml
Based on the output of the java23 build on Jenkins, there are some errors in the javadoc which this PR fixes.
The change in jena-iri3986 about maven-jar-plugin is to have both `automatic.module.name` and a module-info.java file ...
and avoid a javadoc error about mixed aggregation javadoc!
----
> Javadoc fixes

- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/ActionPrefixesR.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/ActionPrefixesRW.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/HttpAction.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/SPARQLQueryProcessor.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/SPARQL_QueryGeneral.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/system/GraphLoadUtils.java
- jena-text/src/main/java/org/apache/jena/query/text/DatasetGraphText.java
- jena-text/src/main/java/org/apache/jena/query/text/changes/DatasetGraphTextMonitor.java
I've done a code review and testing for the report #2755. I haven't been able to reproduced the situation. 
In a code review, I did find one weak area of DatasetGraphText where it was not following the correct code pattern but I can't get it to reproduce the report. This is commit c7f61a3ef1 "DatasetGraphText call operations in correct order".
The other changes are rewrite for clarity and general clean-up because of reviewing many areas.
----
> GH-2755: DatasetGraphText call operations in correct order

- jena-tdb1/src/main/java/org/apache/jena/tdb1/assembler/DatasetAssemblerTDB1.java
- jena-tdb1/src/main/java/org/apache/jena/tdb1/assembler/VocabTDB1.java
- jena-tdb1/src/test/java/org/apache/jena/tdb1/assembler/TestTDBAssembler.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/assembler/VocabTDB2.java
- jena-tdb2/src/test/java/org/apache/jena/tdb2/assembler/TestTDBAssembler.java
GitHub issue resolved #2841
Pull request Description: 
Tidy up assembler constants in TDB1 and TDB2.
----
> GH-2841: Align naming of assembler constants for TDB1 and TDB2

- jena-cmds/pom.xml
- jena-cmds/src/main/java/arq/cmdline/ModAlgebra.java
- jena-cmds/src/main/java/arq/cmdline/ModItem.java
- jena-cmds/src/main/java/arq/cmdline/ModQueryIn.java
- jena-cmds/src/main/java/arq/qexpr.java
- jena-cmds/src/main/java/arq/rupdate.java
- jena-cmds/src/main/java/org/apache/jena/cmd/ArgModuleGeneral.java
- jena-cmds/src/main/java/org/apache/jena/cmd/Args.java
- jena-cmds/src/main/java/org/apache/jena/cmd/CmdArgModule.java
- jena-cmds/src/main/java/org/apache/jena/cmd/CmdGeneral.java
- jena-cmds/src/main/java/org/apache/jena/cmd/CmdLineArgs.java
- jena-cmds/src/main/java/org/apache/jena/cmd/Usage.java
- jena-cmds/src/main/java/shacl/shacl_parse.java
- jena-cmds/src/test/java/org/apache/jena/cmds/TestCmdLine.java
- jena-cmds/testing/cmd/args-bad-1
- jena-cmds/testing/cmd/args-good-1
- jena-cmds/testing/cmd/args-good-2
- jena-cmds/testing/cmd/args-good-3
- jena-core/src/main/java/org/apache/jena/irix/SystemIRIx.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/cmds/DSGSetup.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/sys/FusekiModules.java
GitHub issue resolved #2862
Added a form : `@file` that read arguments from a file.
A side effect is that the "read contents" (hidden feature) of a few commands, like `qparse`, becomes `^filename`. 
Because this style does not work with shell file completion, it's not a very useful feature. Using `--file filename` is better.
----
----
> GH-2862: Command line arguments from a file

- .asf.yaml
Per https://github.com/apache/infrastructure-asfyaml/blob/main/README.md#merge-buttons only enable the Rebase and Merge button so that PR merges affect the history in a predictable and consistent manner
(This way I can stop forgetting and clicking the wrong button)
> Configure Merge Button for GitHub

- jena-fuseki2/jena-fuseki-ui/package.json
- jena-fuseki2/jena-fuseki-ui/yarn.lock
Remove the forced versions of the "resolutions" section.
Bump the declared version of nanoid to 5.0.9 inline with #2891 (this is a security fix)
----
> Remove "resolutions" entries. Bump nanoid to 5.0.9 in package.json

- jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIterPeek.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIteratorCheck.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/main/StageGeneratorGeneric.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/main/iterator/QueryIterUnion.java
- jena-arq/src/test/java/org/apache/jena/sparql/api/TestQueryExecutionCancel.java
GitHub issue resolved #2881 
- Added a test case that should emit warnings without the fixes (the tests do not fail otherwise)
- Adds exception handling to OpUnion and StageGeneratorGeneric, mainly to cope with concurrent QueryCancelledException.
----
----
> GH-2881: Mitigate cases of open iterators when cancelling queries.

- jena-arq/src/main/java/org/apache/jena/sparql/algebra/OpAsQuery.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/ExprTransformApplyElementTransform.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/QueryTransformOps.java
- jena-arq/src/test/java/org/apache/jena/sparql/algebra/TestOpAsQuery.java
GitHub issue resolved #2883 
Pull request Description: Changed a line to pass on an ExprTransform rather than null.
Notes for possible further improvements outside the scope of this PR:
* It may be the case that `ElementTransformer` needs to create an identity ExprTransform rather than passing null into the machinery.
* `QueryTransformOps.transformVarExprList` in my IDE warns that the `changed` flag is not used. Perhaps this needlessly creates clones of queries w.r.t. identity transforms.
----
---- …
> GH-2883: Fix for an NPE in OpAsQuery.

- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/OntGraphModelImpl.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/UnionGraphImpl.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/objects/OntSimpleClassImpl.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/model/MutableModel.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/OntModelMiscTest.java
GitHub issue resolved #2868
- use only UnionGraph (not InfGraph) to hold graph-listeners
- minor fix in OntSimpleClassImpl
----
----
> GH-2868: [ontapi] change register\unregister ModelChangedListener functionality

- jena-arq/src/main/java/org/apache/jena/sparql/expr/nodevalue/NodeFunctions.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/nodevalue/XSDFuncOp.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/TestExpressions.java
GitHub issue resolved #2908
----
----
> GH-2908: Adjust for T24:00:00 in xsd:dateTime

- jena-base/src/main/java/org/apache/jena/atlas/lib/IRILib.java
- jena-base/src/main/java/org/apache/jena/atlas/lib/Lib.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/mod/shiro/FMod_Shiro.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/mod/shiro/FusekiShiroLib.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/mod/shiro/TestModShiro.java
- jena-fuseki2/jena-fuseki-main/testing/Shiro/shiro withSpaceInName.ini
- jena-tdb1/src/test/java/org/apache/jena/tdb1/store/TestNodeId.java
It turns out that Shiro handles resources in its own way. A file name is "`file:<unencoded path>`", not an encoded path as in `file:` RFC IRI.
This showed up on the ASF Jenkins build because we have jobs with spaces in their names and the name is used to create the directory for the build.
----
> GH-2902: Fix: Work with Shiro-style resource names

- jena-fuseki2/apache-jena-fuseki/assembly-dist.xml
- jena-fuseki2/apache-jena-fuseki/fuseki
- jena-fuseki2/apache-jena-fuseki/fuseki-server
- jena-fuseki2/apache-jena-fuseki/fuseki-server.bat
- jena-fuseki2/apache-jena-fuseki/pom.xml
This is the PR to switch `apache-jena-fuseki` to having `jena-fuseki-server` as `fuseki-servar.jar`
This PR of a single commit is the switchover in the apache-jena-fuseki download from the internally webapp-based Fuseki to "Fuseki server" - fuseki/main + all Fuseki modules to provide the Shiro security, admin and UI.
----
> GH-2902: Use jena-fuseki-server for fuseki-server.jar

- .github/workflows/pr-dependencies.yml
Run a build when dependabot submitts a PR
This is doing checking of dependencies so the matrix is minimal - one job, running with Java21 (the POM will target Java17) on Linux.
The trigger is "open pull request".
----
> GH-2928: Workflow for checking dependency updates

- jena-arq/src/main/java/org/apache/jena/riot/out/NodeFmtLib.java
- jena-arq/src/test/java/org/apache/jena/riot/out/TestNodeFmtLib.java
GitHub issue resolved #2932
* Fixes NodeFmtLib.strNT
* Also adds `strNT` and `strNQ` variants for formatting as N-Quads (and N-Triples). It seems that so far there were no reliable util methods to create a single valid NQ string - unless one goes through riot. None of the formatting methods in `NodeFmtLib` and `FmtUtils` seem to produce NQ.
----
----
> GH-2932: Fix for NodeFmtLib.strNT and added variants for Triple and Quad.

- jena-arq/src/main/java/org/apache/jena/query/Query.java
- jena-arq/src/main/java/org/apache/jena/query/QueryVisitor.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/VarExprList.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/ExecutionContext.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIterRoot.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/main/OpExecutor.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/main/QueryEngineMain.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/main/iterator/QueryIterGraph.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/ref/QueryEngineRef.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/ref/RefEval.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/ExprFunctionOp.java
- jena-arq/src/main/java/org/apache/jena/sparql/path/eval/PathEngine.java
- jena-arq/src/main/java/org/apache/jena/sparql/util/ExprUtils.java
- jena-arq/src/test/java/org/apache/jena/riot/out/TestNodeFmtLib.java
- jena-arq/src/test/java/org/apache/jena/sparql/engine/iterator/TestCancelDistinct.java
- jena-arq/src/test/java/org/apache/jena/sparql/engine/iterator/TestDistinctDataBagLimited.java
- jena-arq/src/test/java/org/apache/jena/sparql/engine/iterator/TestDistinctMem.java
- jena-arq/src/test/java/org/apache/jena/sparql/engine/iterator/TestQueryIterSort.java
- jena-arq/src/test/java/org/apache/jena/sparql/engine/iterator/TestSortedDataBagCancellation.java
- jena-arq/src/test/java/org/apache/jena/sparql/engine/join/TestTableJoin.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/TestCastXSD.java
- jena-arq/src/test/java/org/apache/jena/sparql/path/TestPath.java
- jena-cmds/src/main/java/arq/qexpr.java
* Reformat the `Query` class - no other changes
* Reduce the surface of `ExecutionContext`
Use functions, not client code calls to constructors, so they have meaning full names.
----
> Cleaning code -- Query and ExecutionContext

- jena-arq/src/main/java/org/apache/jena/http/sys/ExecHTTPBuilder.java
- jena-arq/src/main/java/org/apache/jena/sparql/algebra/OpAsQuery.java
- jena-arq/src/main/java/org/apache/jena/sparql/algebra/walker/Walker.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/VarExprList.java
- jena-arq/src/main/java/org/apache/jena/sparql/exec/QueryExecDatasetBuilder.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/ExprAggregator.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/ElementTransformSubst.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/QueryScopeException.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/QuerySyntaxSubstituteScope.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/QueryTransformOps.java
- jena-arq/src/test/java/org/apache/jena/riot/out/TestNodeFmtLib.java
- jena-arq/src/test/java/org/apache/jena/riot/system/TS_RiotSystem.java
- jena-arq/src/test/java/org/apache/jena/sparql/syntax/TS_Syntax.java
- jena-arq/src/test/java/org/apache/jena/sparql/syntax/TestQueryParser.java
- jena-arq/src/test/java/org/apache/jena/sparql/syntax/TestSerialization.java
- jena-arq/src/test/java/org/apache/jena/sparql/syntax/syntaxtransform/TestFlattenSyntax.java
- jena-arq/src/test/java/org/apache/jena/sparql/syntax/syntaxtransform/TestQueryOps.java
- jena-arq/src/test/java/org/apache/jena/sparql/syntax/syntaxtransform/TestQueryShallowCopy.java
- jena-arq/src/test/java/org/apache/jena/sparql/syntax/syntaxtransform/TestQuerySubstituteScope.java
- jena-arq/src/test/java/org/apache/jena/sparql/syntax/syntaxtransform/TestQuerySyntaxSubstitute.java
- jena-arq/src/test/java/org/apache/jena/sparql/syntax/syntaxtransform/TestQuerySyntaxTransform.java
- jena-arq/src/test/java/org/apache/jena/sparql/syntax/syntaxtransform/TestSyntaxTransform.java
- jena-geosparql/src/test/java/org/apache/jena/geosparql/implementation/jts/CustomCoordinateSequenceTest.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/model/MutableModel.java
- jena-shacl/src/main/java/org/apache/jena/shacl/engine/constraint/SparqlValidation.java
- jena-shacl/src/main/java/org/apache/jena/shacl/validation/EvalSparql.java
- jena-tdb1/src/main/java/org/apache/jena/tdb1/solver/OpExecutorTDB1.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/solver/OpExecutorTDB2.java
This implements changes for #2799 but it isn't used for `.substitute` yet because complete other cases arise beyond #2799.
It does introduce the right operation in `QueryTrabsformOps` and starts the rename cycle for some `transform` operations because `transform` (different signatures) are used elsewhere.
----
> GH-2799: Include substituted var/value in modified query

- .github/workflows/ui.yml
This PR does two things:
* `cyrpress-run` is made to run after the build job. It appears that the jobs run in parallel at the moment - I see the Cypress runs finish before the build step has. The Cypress job is quick.
* Change the build step to do a "dev" build. Currently, it does not build from the start of the Jena build. If there has been a change in earlier dependency, then the Fuseki steps fail.
If this become smooth, we should consider combining into a PR workflow.
----
> cypress-run to depend on a maven build

- jena-core/src/main/java/org/apache/jena/graph/langtag/LangTags.java
It used `%c` for formatting a `String` (now `%s)`.
Thanks @afs for correcting the [last (bad) PR](https://github.com/apache/jena/pull/2971)!
> Fixes a format string error in LangTags

- jena-base/src/main/java/org/apache/jena/atlas/net/Host.java
- jena-base/src/test/java/org/apache/jena/atlas/net/TestHost.java
- jena-core/src/main/java/org/apache/jena/iri3986/provider/JenaSeveritySettings.java
- jena-core/src/test/java/org/apache/jena/rdf/model/test/AbstractTestPackage.java
- jena-core/src/test/java/org/apache/jena/rdf/model/test/TestProperties.java
- jena-fuseki2/apache-jena-fuseki/fuseki-plain
- jena-fuseki2/apache-jena-fuseki/fuseki-server
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/SPARQLQueryProcessor.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/validation/html/IRIValidatorHTML.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/mod/shiro/TestModShiro.java
GitHub issue resolved #2963
An accumulation of things during the build cycle:
* fix for #2963
* Test rename because two tests classes with the same name is confusing
* Improve the output of the IRI validator 
* Better error messages for SPARQL protocol errors.
* Add a script to the Fuseki download to run Fuseki plain (missed in 5.3.0)
----
> GH-2963: Cope with IPv6 address for the local machine

- jena-fuseki2/jena-fuseki-docker/Dockerfile
GitHub issue resolved #2949 
`eclipse-temurin:21-alpine` base image is multi-platform while `eclipse-temurin:17-alpine` was not
----
----
> GH-2949: Bump base Docker image to `eclipse-temurin:21-alpine`

- jena-fuseki2/jena-fuseki-docker/README.md
> Update to a Jena5 version

- jena-arq/src/main/java/org/apache/jena/sparql/algebra/Algebra.java
- jena-arq/src/main/java/org/apache/jena/sparql/algebra/TableFactory.java
- jena-arq/src/main/java/org/apache/jena/sparql/algebra/table/TableBuilder.java
- jena-arq/src/main/java/org/apache/jena/sparql/algebra/table/TableData.java
- jena-arq/src/main/java/org/apache/jena/sparql/algebra/table/TableN.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/binding/Binding.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/binding/Binding0.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/binding/Binding1.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/binding/Binding2.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/binding/Binding3.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/binding/Binding4.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/binding/BindingBase.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/binding/BindingOverMap.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/binding/BindingProject.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/binding/BindingProjectBase.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/binding/BindingProjectNamed.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/binding/BindingRoot.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIterLateral.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/join/ImmutableUniqueList.java
- jena-arq/src/main/java/org/apache/jena/sparql/exec/QueryExecBuilder.java
- jena-arq/src/test/java/org/apache/jena/query/TestQueryCloningCornerCases.java
- jena-arq/src/test/java/org/apache/jena/sparql/algebra/TestTableBuilder.java
- jena-arq/src/test/java/org/apache/jena/sparql/exec/TestQueryExecution.java
- jena-arq/src/test/java/org/apache/jena/sparql/graph/GraphsTests.java
- jena-tdb1/src/main/java/org/apache/jena/tdb1/solver/BindingTDB.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/solver/BindingTDB.java
GitHub issue resolved #2924
* Added a new test case with nested laterals.
* Fixed nested laterals by merging compatible bindings in `QueryIterLateral`
* While writing the tests, I added a few shorthands to the QueryExecBuilder API: Its now possible to write `QueryExec.dataset(...).query("SELECT ...").table()` to generally safely obtain a detached materialized in-memory table without having to worry about resource leaks or try-with-resources blocks. In the revised tests, the tables are used directly when asserting the equality of expected and actual results. In an attempt to allow for cleanly detaching BindingTDB instances, I added `Binding.detach()` with appropriate implementations. `Binding.detach` avoids copying of bindings that are already in-memory, and is …
> GH-2924: Lateral - fixed injection for tables and enhanced QueryExec API for easier testing.

- jena-extras/jena-serviceenhancer/src/main/java/org/apache/jena/sparql/service/enhancer/impl/BatchQueryRewriter.java
- jena-extras/jena-serviceenhancer/src/test/java/org/apache/jena/sparql/service/enhancer/impl/TestServiceEnhancerBatchQueryRewriter.java
GitHub issue resolved #2992
Pull request Description: Service Enhancer now allocates fresh blank nodes when creating the union members of a bult request.
----
----
> GH-2992: Service Enhancer: Fix bnode naming in bulk requests.

- jena-arq/src/main/java/org/apache/jena/sparql/exec/QueryExecDataset.java
- jena-core/src/main/java/org/apache/jena/util/iterator/NiceIterator.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/geo/topological/GenericPropertyFunction.java
- jena-geosparql/src/test/java/org/apache/jena/geosparql/geo/topological/CancelQueryTest.java
GitHub issue resolved #2930 
Pull request Description: Improves base implementation of `GenericPropertyFunction` to operate lazily using the `QueryIter` machinery and its cancellation features. The class `CancelQueryTest` tests for successful cancellation.
Disclaimer: The core work was done by my colleague @LorenzBuehmann - He suggested that I should take care of the PR.
~~Set to draft because perhaps some more regression testing should be added.~~
There are several tests in the geosparql module. I experimented by introducing intentional errors into the PR, such as setting isSubjectBound hard to false/false or returning empty/unit result sets and they causes failures - so the tests already seem to sufficiently capture cases where bogus results are returned.
----
By submitting this pull …
> GH-2930: Support for query cancellation for spatial property functions

- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestFusekiShaclValidation.java
While looking for the cause of the intermittent test failures on GH builds, I came across a bug.
It does not seem explain the intermittent failures, but if has an effect, that would be useful information. 
----
> Fix: Set the server static variable

- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestCrossOriginFilter.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestFusekiDatasetSharing.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestFusekiStdReadOnlySetup.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestFusekiStdSetup.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestPlainServer.java
May be related to #3008 
There are some more places in tests for jena-fuseki-main and jena-integration-tests 
with the same flaw that #3006 fixes for `TestFusekiShaclValidation`.
----
> Fix: Set the server static variable (pt 2)

- jena-benchmarks/jena-benchmarks-shadedJena510/pom.xml
- jena-core/pom.xml
- jena-extras/jena-querybuilder/pom.xml
- jena-fuseki2/jena-fuseki-core/pom.xml
- jena-fuseki2/jena-fuseki-fulljar/pom.xml
- jena-fuseki2/jena-fuseki-geosparql/pom.xml
- jena-fuseki2/jena-fuseki-server/pom.xml
- jena-permissions/pom.xml
WIP
Looking at build and trying to fix warnings. This goes for both node and java, can split PR if it makes more sense, and squash to logical commits. Currently there are only 5 warnings left related to the geosparql tests. Will try to comment some thoughts inline. Much of the PR is just updating or ignoring warnings or paths.
Maybe some should be seen, or replaced by creating an issue?
----
----
> Cleanup some build warnings

- jena-fuseki2/jena-fuseki-ui/src/utils/validation.js
- jena-fuseki2/jena-fuseki-ui/src/views/dataset/Upload.vue
- jena-fuseki2/jena-fuseki-ui/tests/unit/utils/validation.spec.js
GitHub issue resolved #2370
@afs, @jmkeil, first stab at #2370. Had a look at [^1] and [^2], and I saw some parts of the text mentioning "percent-encoded" in requests, and that the backend is supposed to return 400, as it's doing now. From quickly reading those two (skipping parts, trying to find info for validation), I think
1. empty is valid
2. spaces are no-no
3. otherwise it must be a URI
4. encoded URL is no-no, it must be a valid URI, without encoded parts
I extended the current validation to also check 3 and 4 now. Does that sound right?
This is a draft until I confirm that the fix looks good, then I will either write the tests, or modify the PR again to move the code to some JS module as that a lot easier to write unit-test against, instead of testing …
> GH-2370: Improve validation of dataset graph names

- jena-fuseki2/jena-fuseki-ui/package.json
- jena-fuseki2/jena-fuseki-ui/vite.config.js
- jena-fuseki2/jena-fuseki-ui/yarn.lock
Going through node warnings from the GH-action build.
Changing legacy node-sass api to modern and adding peer dependencies solves the warnings. while the other changes just silences them (1250kb as a bundle limit sounds huge to me). Since the largest number of SASS warnings are inherited from bootstrap, I thought it could make sense to hide them. I am more unsure if it makes sense to up the bundle limit for less noise in the build output (since it looks like an issue).
----
----
See the [Apache Jena …
> Cleanup node warnings in build

- jena-arq/src/main/java/org/apache/jena/sparql/engine/main/OpExecutor.java
- jena-arq/src/main/java/org/apache/jena/sparql/service/ServiceExec.java
- jena-integration-tests/src/test/java/org/apache/jena/test/service/TestCustomServiceExecutor.java
GitHub issue resolved #3016
* Aligned parameter order of `Service.exec`
* Added tests to ensure that starting a service chain over works as expected. The use case is where a plugin modifies a request and wants to have it re-processed by all registered plugins in the execution context.
----
----
> GH-3016: Streamlined methods for starting over custom service execs  + tests

- jena-arq/src/main/java/org/apache/jena/sparql/core/assembler/AssemblerUtils.java
- jena-cmds/src/main/java/tdb/cmdline/ModTDBDataset.java
- jena-cmds/src/main/java/tdb2/cmdline/ModTDBDataset.java
- jena-fuseki2/examples/config-inference-2.ttl
- jena-fuseki2/examples/config-tdb2.ttl
- jena-fuseki2/examples/config-text-tdb2.ttl
- jena-fuseki2/examples/tdb2-select-graphs.ttl
- jena-tdb2/src/main/java/org/apache/jena/tdb2/assembler/VocabTDB2.java
GitHub issue resolved #3014
`:DatasetTDB` and `:DatasetTDB2` have been used in the past. 
Ensure ModAssembler (TDB2) accepts both from the command line `--desc`.
Same for TDB1.
----
> GH-3014: Support both possible TDB dataset type names

- jena-tdb2/src/main/java/org/apache/jena/tdb2/store/DatasetGraphTDB.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/store/StoragePrefixesTDB.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/store/StorageTDB.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/store/TDB2StorageBuilder.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/sys/DatabaseOps.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/sys/DatabaseOpsWindows.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/sys/StoreConnection.java
GitHub issue resolved #3015
Close files after a database has been compacted.
This is done whether it is deleted or not.
This PR does not fix the JVM issue with MSWindows regarding release of memory-mapped files.
----
> GH-3015: Close files after TDB2 compaction

- jena-arq/Grammar/arq.jj
- jena-arq/Grammar/main.jj
- jena-arq/src/main/java/org/apache/jena/query/Query.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/QueryCompare.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/ExprTransform.java
- jena-arq/src/main/java/org/apache/jena/sparql/graph/NodeTransformExpr.java
- jena-arq/src/main/java/org/apache/jena/sparql/lang/arq/ARQParser.java
- jena-arq/src/main/java/org/apache/jena/sparql/lang/sparql_12/JavaCharStream.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/QueryTransformOps.java
- jena-arq/src/test/java/org/apache/jena/sparql/syntax/syntaxtransform/TestQuerySyntaxTransform.java
This included and completes PR #3033. There were two general bugs in JSON-WHERE handling that #3033 uncovers.
1. QueryCompare ignored the JSON template
2. The parser added spurious entries as if it was a SELECT query.
Thank you to @Aklakan for #3033.
----
> QueryTransformOps applied to JSON template queries

- jena-arq/src/main/java/org/apache/jena/sparql/algebra/optimize/TransformScopeRename.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/Rename.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/ExprLib.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/ExprVar.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/NodeValue.java
- jena-arq/src/main/java/org/apache/jena/sparql/graph/NodeTransform.java
- jena-arq/src/main/java/org/apache/jena/sparql/graph/NodeTransformExpr.java
- jena-arq/src/main/java/org/apache/jena/sparql/graph/NodeTransformOp.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/ElementTransformSubst.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/QuerySyntaxSubstituteScope.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/QueryTransformOps.java
- jena-arq/src/test/java/org/apache/jena/sparql/syntax/TS_Syntax.java
- jena-arq/src/test/java/org/apache/jena/sparql/syntax/syntaxtransform/TestQuerySyntaxSubstitute.java
GitHub issue resolved #2799 (record replacements in projection)
GitHub issue resolved #3040 (renaming variables)
Pull request Description: See issues.
----
> GH-2799, GH-3040: QueryTransformOps: Record replacements; support variable renaming.

- jena-integration-tests/src/test/java/org/apache/jena/test/service/TestCustomServiceExecutor.java
GitHub issue resolved #3050 
Pull request Description: Fixes an open iterator warning due to the input iterator not being connected to the returned iterator.
----
----
> GH-3050: Fixed open iterator in test case for custom service executors.

- .github/dependabot.yml
PR #3059, and #3037 before that, consistently fails the UI test matrix in the Firefox upload test.
The PR has 6 minor updates and a cascade of version updates which makes it difficult to find out which update is causing the problem.
This PR switch off grouping for npm updates so there will be individual PRs. We can find which are not causing problems, and get them through, and also see where the problem is.
----
> Don't group npm ecosystem updates

- jena-iri3986/pom.xml
- jena-iri3986/src/test/java/org/apache/jena/rfc3986/TestBuild.java
- jena-iri3986/src/test/java/org/apache/jena/rfc3986/TestParseDID.java
- jena-iri3986/src/test/java/org/apache/jena/rfc3986/TestParseDNS.java
- jena-iri3986/src/test/java/org/apache/jena/rfc3986/TestParseIPv4Address.java
- jena-iri3986/src/test/java/org/apache/jena/rfc3986/TestParseOID.java
- jena-iri3986/src/test/java/org/apache/jena/rfc3986/TestURISchemes.java
This PR cleans up module `jena-iri3986` to use JUnit5 exclusively.
It was a mixture of JUnit4 and JUnit5.
----
> Update jena-iri3986 to all JUnit5

- jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIteratorWrapper.java
Pull request Description: Fix a rare race condition that can cause a test failure during build. `QueryIteratorWrapper` is updated to reuse `QueryIteratorBase.performClose and performRequestCancel`. These methods ensure that the reference to the delegate iterator remains unchanged during the "if not null" check and the subsequent cancel / close action.
Should be unrelated to #3063.
Below is the build error I got for the first time since contributing the `TestQueryExecutionCancel` test case.
```
[ERROR] Tests run: 21, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.723 s <<< FAILURE! -- in org.apache.jena.sparql.api.TestQueryExecutionCancel
[ERROR] org.apache.jena.sparql.api.TestQueryExecutionCancel.test_cancel_concurrent_1 -- Time elapsed: 0.091 s <<< ERROR! …
```
> Update QueryIteratorWrapper to performClose and performRequestCancel

- jena-arq/src/main/java/org/apache/jena/sparql/engine/iterator/QueryIterFilterExpr.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/join/AbstractIterHashJoin.java
- jena-arq/src/main/java/org/apache/jena/sparql/engine/main/solver/StageMatchTriple.java
- jena-arq/src/main/java/org/apache/jena/sparql/exec/RowSetOps.java
- jena-arq/src/main/java/org/apache/jena/sparql/exec/RowSetStream.java
- jena-arq/src/test/java/org/apache/jena/sparql/api/TestQueryExecutionTimeout2.java
- jena-tdb1/src/main/java/org/apache/jena/tdb1/solver/StageMatchTuple.java
- jena-tdb2/src/main/java/org/apache/jena/tdb2/solver/StageMatchTuple.java
GitHub issue resolved #3044 
Pull request Description: Timeouts in QueryExecDataset were postponed until a so-far eager hash probe table construction completed because of locking. This PR proposes to initialize the hash probe table lazily such that the iterator construction becomes cheap and the lock is released quickly.
I added a test case that fails without the proposed fix.
----
- (Documentation change and updates are provided for the [Apache Jena website](https://github.com/apache/jena-site/))
---- …
> GH-3044: HashJoin iterator construction no longer eagerly builds hash probe table.

- .github/workflows/ui.yml
The Firefox upload test now fails nearly every time after a Cypress upgrade. It was failing intermittently.
While there are several Cypress reports are about Firefox+Cypress, none are exactly what we're seeing here which is that the other tests are working with Firefox, it is just `upload.cy.js` that fails.
Changing the timeout does not have any effect, except a longer wait. It is as if whatever Cypress is waiting for, happens and completes (server exit?) before Cypress starts to polling.
Manual testing shows the UI to be functioning in Firefox.
----
> Remove Firefox from test matrix due to Cypress upgrade

- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/server/Dispatcher.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/ActionLib.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/FusekiServer.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/JettyServer.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/sys/FusekiSystemConstants.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/sys/JettyLib.java
GitHub issue resolved #3110 
Pull request Description: See issue.
The maximum form size was being set by hard-wired code.
* Introduce a constants file.
* Improve the error message - no stack trace and then a 500; it becomes a 400.
----
> GH-3110: Set the maximum HTML form size

- jena-db/pom.xml
- jena-langtag/pom.xml
- jena-text/src/test/java/org/apache/jena/query/text/TestTextMultilingualEnhancements.java
Preparation for Jena 5.4.0.
----
> Clean-up for release 5.4.0

- jena-arq/Grammar/grammar
- jena-arq/src/main/java/org/apache/jena/sparql/lang/sparql_12/JavaCharStream.java
- jena-core/src/main/java/org/apache/jena/rdf/model/ModelCon.java
Fix two javadoc warnings: 
* `ModelCon` : two `@param` fixes
* sparql12/JavaCharStream : better fixup for javadoc warnings
----
> Preparation for 5.4.0 - fix javadoc

- jena-arq/src/main/java/org/apache/jena/http/HttpLib.java
- pom.xml
Bump ver.commons-io from 2.18.0 to 2.19.0
Bump ver.shiro from 2.0.2 to 2.0.3
Bump ver.gson from 2.12.1 to 2.13.0
Bump ver.guava from 33.4.6-jre to 33.4.7-jre
Remove unused dependency management of jython
----
> Dependency updates

- jena-arq/src/main/java/org/apache/jena/http/HttpEnv.java
- jena-arq/src/main/java/org/apache/jena/riot/web/HttpNames.java
- jena-arq/src/main/java/org/apache/jena/sparql/exec/http/Service.java
This does not complete issue #3148.
It is a pro-tem change solution that sets a user-agent for `SERVICE` (the original report #3139).
Application use of QueryExecution and GSP/DSP (Graph Store Protocol) though their builders can set the the User-Agent header so they are not blocked at the moment.
`SERVICE` does not expose this possibility.
A complete resolution of #3148 will be to have a way to change the default User-Agent without needing to change the setup via builders.
----
> GH-3148: Set HTTP header User-Agent when calling from SERVICE

- jena-arq/src/main/java/org/apache/jena/sparql/syntax/Element1.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementAssign.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementBind.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementData.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementDataset.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementExists.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementFilter.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementGroup.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementLateral.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementMinus.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementNamedGraph.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementNotExists.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementOptional.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementPathBlock.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementService.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementSubQuery.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementTriplesBlock.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementUnion.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementVisitorBase.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/ElementWalker.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/Template.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/TripleCollector.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/TripleCollectorBGP.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/TripleCollectorMark.java
Reformatting the `Element*` classes for `Query` - layout, no space before `;`, remove trailing white space.
No functional changes.
----
> Reformat query syntax elements

- jena-core/src/main/java/org/apache/jena/vocabulary/SchemaDO.java
The property URI should not have a leading underscore
GitHub issue resolved #3221 
----
----
> GH-3221 Fix `SchemaDO._abstract` URI

- CHANGES.txt
- jena-tdb2/src/main/java/org/apache/jena/tdb2/sys/StoreConnection.java
GitHub issue resolved #3240
Trigger a GC after deleting a database.
This is reported to improve (not completely fix) the situation relating to memory mapped files -- https://bugs.openjdk.org/browse/JDK-4724038
----
> GH-3240: TDB2 database delete

- jena-examples/src/main/java/arq/examples/ExampleDBpedia1.java
- jena-examples/src/main/java/arq/examples/ExampleDBpedia3.java
When I tried to run examples in the jena-examples module, arq.examples.ExampleDBpedia1 and ExampleDBpedia3 failed as follows:
```
$ bin/jena arq.examples.ExampleDBpedia1
2025-06-14T11:52:53.149716377Z main ERROR Reconfiguration failed: No configuration found for '30946e09' at 'null' in 'null'
Exception in thread "main" HttpException: -1 Unexpected error making the query: GET http://dbpedia-live.openlinksw.com/sparql?timeout=2000&query=SELECT+DISTINCT++?company%0AWHERE%0A++%7B+?co
mpany++a++%3Chttp://dbpedia.org/ontology/Company%3E+%7D%0ALIMIT+++20%0A
...
Caused by: java.net.ConnectException: HTTP connect timed out
at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:581)
... 10 more
```
Using dbpedia.org instead of …
> Fix DBpedia examples in the jena-examples module

- jena-arq/src/main/java/org/apache/jena/http/HttpLib.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/system/DataUploader.java
GitHub issue resolved #3258 
Pull request Description: Proposal to add bzip2 as a recognized encoding to `HttpLib` and `DataUploader`.
Note: The Web server from which one attempts to upload a file needs to be configured to serve content type and encoding separately:
```
curl -I http://myserver/file.nt.bz2
Content-Type: application/n-triples
Content-Encoding: bzip2
```
For example, by default, the Apache Web server would serve .bz2 files as `Content-Type: application/x-bzip2`. This way a client wouldn't know what actual content is being encoded.
----
- (No extra tests are so far included because the change turned out to be trivial)
By submitting this pull request, I acknowledge that I am making a contribution to the Apache Software Foundation under the terms and conditions of the …
> GH-3258: Support for bzip2 encoding in upload via GSP and SPARQL LOAD.

- jena-arq/src/test/java/org/apache/jena/arq/junit/TextTestRunner.java
- jena-arq/src/test/java/org/apache/jena/arq/junit/runners/RunnerOneManifest.java
- jena-arq/src/test/java/org/apache/jena/arq/junit/runners/SetupManifests.java
- jena-base/src/test/java/org/apache/jena/atlas/junit/TextListenerLong.java
- jena-cmds/src/test/java/arq/rdftests.java
Make the summary consistent:
```
... last test T-381 ...
Time: 0.133
OK (381 tests)
Tests run: 381
Failures:  0
Manifests: 4
```
not
```
... last test T-381 ...
Time: 0.133
OK (385 tests)
Run: 385
Failures: 0
```
The old form counted manifests as tests.
----
> Adjust output of 'rdftests' to allow for manifests

- jena-arq/src/main/java/org/apache/jena/sparql/expr/E_Exists.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/E_NotExists.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/ExprFunctionOp.java
- jena-arq/src/main/java/org/apache/jena/sparql/syntax/syntaxtransform/ElementTransformSubst.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/TS_Expr.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/TestExprFunctionOp_ExprTransform.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/TestExprFunctionOp_NodeTransform.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/TestExprTransform.java
GitHub issue resolved #3253.
Pull request Description: Transforms now also affect Elements of ExprFunctionOp instances.
----
----
> GH-3253: Apply transforms to present Elements of ExprFunctionOp instances.

- jena-arq/src/main/java/org/apache/jena/query/ParameterizedSparqlString.java
- jena-arq/src/test/java/org/apache/jena/query/TestParameterizedSparqlString.java
This commit adds the ability for `ParameterizedSparqlString` to support injecting the `UNDEF` keyword into `VALUES` clauses as needed.  A new `undef()` method is added to the class that provides access to a special instance level constant `RDFNode` that is used to indicate that the caller wants to inject `UNDEF`.
Under the hood this is just a wrapper around a `Node` constant but due to the `setValues()`/`setRowValues()` part of the API working in `RDFNode`'s rather than `Node`'s went with this approach.  I considered refactoring further to allow that part of the API to take `Node` and `RDFNode` interchangeably **but** given the limitations of Java type erasure generics (several of the methods in that part of the API use `Collection<? extends RDFNode>` and similar) that would effectively …
> Permit injecting UNDEF in ParameterizedSparqlString (GH-3268)

- jena-arq/src/main/java/org/apache/jena/sparql/expr/E_Function.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/TestExprLib.java
Pull request Description: E_Function instances compared to equals regardless of their functionIRI field. This causes caching issues such as with the service enhancer, where the same cache hit is produced for queries that should actually be different.
In our case, two queries that differed only by the geosparql filter functions geof:sfIntersects and geof:sfContains were incorrectly considered to be equal.
----
----
> Fix for E_Function.equals() and hashCode() to also consider the functionIRI

- jena-iri3986/src/main/java/org/apache/jena/rfc3986/AlgResolveIRI.java
- jena-iri3986/src/main/java/org/apache/jena/rfc3986/ParseURN.java
- jena-iri3986/src/test/java/org/apache/jena/rfc3986/TestNormalize.java
GitHub issue resolved #3310
----
> GH-3310: protect against zero array split

- jena-fuseki2/jena-fuseki-ui/yarn.lock
Reverts apache/jena#3339
This PR breaks the Fuseki UI directly under e.g. http://localhost:3030 which then only shows a blank page with the following error in the console.
I used the Fuseki bundle built under `jena-fuseki2/apache-jena-fuseki/target/apache-jena-fuseki-5.6.0-SNAPSHOT.tar.gz`.
I removed the node_modules prior to the build with `rm -rf ./jena-fuseki2/jena-fuseki-ui/node_modules`.
> Revert "Bump @fortawesome/vue-fontawesome from 3.0.8 to 3.1.0 in /jena-fuseki2/jena-fuseki-ui"

- jena-arq/src/main/java/org/apache/jena/sparql/expr/ExprEvalException.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/ExprUndefException.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/VariableNotBoundException.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/nodevalue/XSDFuncOp.java
- jena-cmds/src/test/java/arq/rdftests.java
- jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/Fuseki.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/FusekiMainRunner.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/FusekiServer.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/cmds/FusekiMain.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/cmds/FusekiServerCmd.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/sys/FusekiServerArgsCustomiser.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/mod/FusekiServerModules.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/mod/FusekiServerRunner.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/mod/shiro/FMod_Shiro.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/server/FusekiServerRunner.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/TC_FusekiServer.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestConfigFile.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/TestCrossOriginFilter.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/mod/TS_FusekiMods.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/mod/admin/FusekiServerPerTestClass.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/server/TS_FusekiServer.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/server/TestFusekiServer.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/server/TestFusekiServerCmd.java
- jena-fuseki2/jena-fuseki-webapp/src/main/java/org/apache/jena/fuseki/cmd/FusekiArgs.java
GitHub issue resolved #3348
FusekiServerRunner and FusekiMainRunner have the same function names.
FusekiServerRunner runs the server with management area and UI.
FusekiMainRunner runs the basic server and has no on-disk footprint.
----
> GH-3348: FusekiServerRunner and FusekiMainRunner

- jena-base/src/main/java/org/apache/jena/atlas/lib/Cache.java
- jena-base/src/main/java/org/apache/jena/atlas/lib/Lib.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/main/FusekiMainRunner.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/mgt/FusekiServerCtl.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/mod/FusekiServerRunner.java
- jena-fuseki2/jena-fuseki-main/src/main/java/org/apache/jena/fuseki/server/FusekiServerRunner.java
- jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/server/TestFusekiServerCmd.java
- jena-iri3986/src/main/java/org/apache/jena/rfc3986/IRI3986.java
javadoc clean up, IRI3986 clean-up
Fix handling FUSEKI_BASE for during restart
(second build/tests at same file system location will fail)
----
> Fix handling FUSEKI_BASE for during restart

- jena-ontapi/src/main/java/org/apache/jena/ontapi/OntModelFactory.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/OntSpecification.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/assemblers/DocumentGraphRepositoryAssembler.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/assemblers/OA.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/assemblers/OntModelAssembler.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/assemblers/OntReasonerFactoryAssembler.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/assemblers/OntRuleSetAssembler.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/assemblers/OntSpecificationAssembler.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/common/OntPersonalities.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/repositories/DocumentGraphRepository.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/impl/repositories/OntUnionGraphRepository.java
- jena-ontapi/src/main/java/org/apache/jena/ontapi/sys/InitOntAPI.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/DocumentGraphRepositoryAssemblerTest.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/DocumentGraphRepositoryTest.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/OntModelAssemblerTest.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/OntSpecificationAssemblerTest.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/OntUnionGraphRepositoryTest.java
- jena-ontapi/src/test/java/org/apache/jena/ontapi/testutils/RDFIOTestUtils.java
GitHub issue resolved #3322
Due to a conflict (`assembler.ttl`) I had to copy-paste some components from jena-arq (`ReasonerFactoryAssembler`, etc), so it may not be possible to merge this MR right now and we need to wait until the old API is completely removed.
----
----
> GH-3322: [jena-ontapi] add assemblers

- jena-arq/src/main/java/org/apache/jena/sparql/expr/ExprLib.java
- jena-arq/src/main/java/org/apache/jena/sparql/expr/NodeValue.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/TestExprLib.java
- jena-arq/src/test/java/org/apache/jena/sparql/expr/TestNodeValue.java
GitHub issue resolved #3380
1. Put some checking in `NodeValue.nodeToNodevalue` to enforce the "no variables" rule. Adding this did not require any changes to Jena.
2. `ExprLib.nodeToExpr`, used by the SPARQL parsers, turns concrete triple terms into `NodeValue` objects.
----
> Use NodeValue for concrete triple terms as expressions.

- jena-rdfconnection/src/main/java/org/apache/jena/rdflink/RDFLinkHTTP.java
- jena-rdfconnection/src/test/java/org/apache/jena/rdflink/AbstractTestRDFLink.java
Pull request Description: A small fix + test case to allow sending of the CONSTRUCT_JSON query type via RDFLinkHTTP.
Use case is to send a JSON query via RDFLinkHTTP to a remote Fuseki instance. Without this PR, the request fails due to no accept header having been set (in the client inside of RDFLinkHTTP). The fix sets a json accept header for the CONSTRUCT_JSON query type.
----
----
> Support CONSTRUCT_JSON query type in RDFLinkHTTP.

- jena-cmds/src/main/java/org/apache/jena/cmd/Cmds.java
GitHub issue resolved #3437
Pull request Description: Moved `static { JenaSystem.init() }` after the init of other static fields to get rid of an NPE.
I didn't realize in the issue that I used both `-cp` and `-jar` to run the command. The output of either variant no longer raises an NPE:
```bash
➜ java -cp fuseki-server.jar jena.textindexer
No assembler description given
java -cp fuseki-server.jar jena.textindexer  0,99s user 0,11s system 251% cpu 0,441 total
➜ java -jar fuseki-server.jar jena.textindexer
Exception in thread "main" org.apache.jena.cmd.CmdException: Dataset name provided but 'no dataset' flag given
at org.apache.jena.fuseki.main.cmds.FusekiMain.processStdArguments(FusekiMain.java:396)
[...]
```
By submitting this pull request, I acknowledge that I am making a contribution …
> GH-3437: Initialize fields of Cmds.java before JenaSystem.init()

- jena-fuseki2/jena-fuseki-webapp/src/main/java/org/apache/jena/fuseki/cmd/JettyFusekiWebapp.java
- jena-fuseki2/jena-fuseki-webapp/src/test/java/org/apache/jena/fuseki/TestWebappAdminAddDeleteDatasetTemplate.java
This PR looks for the signature of the recurring failure seen in github actions. The signature is a pattern of exceptions and causes.
The failure is not new but it is inferring with the CI builds in unrelated areas. The failures are in module `jena-webapp` (WAR file form of Fuseki) which proposed for removal in Jena 6. 
Also - address a warning.
----
> Look for test external failure signature

- jena-arq/src/main/java/org/apache/jena/rdfs/DatasetGraphRDFS.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetGraphQuads.java
- jena-arq/src/main/java/org/apache/jena/sparql/core/mem/DatasetGraphInMemory.java
- jena-arq/src/main/java/org/apache/jena/sparql/util/Context.java
- jena-arq/src/test/java/org/apache/jena/rdfs/TestDatasetGraphRDFS.java
- jena-benchmarks/jena-benchmarks-jmh/src/test/java/org/apache/jena/geosparql/query/BenchmarkSpatialQueries.java
- jena-benchmarks/jena-benchmarks-jmh/src/test/java/org/apache/jena/geosparql/query/SpatialQueryTask.java
- jena-benchmarks/jena-benchmarks-jmh/src/test/java/org/apache/jena/geosparql/query/SpatialQueryTask550.java
- jena-benchmarks/jena-benchmarks-jmh/src/test/java/org/apache/jena/geosparql/query/SpatialQueryTaskCurrent.java
- jena-fuseki2/jena-fuseki-mod-geosparql/src/main/java/org/apache/jena/fuseki/mod/geosparql/SpatialIndexerService.java
- jena-fuseki2/jena-fuseki-mod-geosparql/src/main/resources/spatial-indexer/index.html
- jena-geosparql/src/main/java/org/apache/jena/geosparql/geo/topological/GenericGeometryPropertyFunction.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/geo/topological/GenericPropertyFunction.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/geo/topological/SpatialObjectGeometryLiteral.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/implementation/access/AccessGeoSPARQL.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/implementation/access/AccessWGS84.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/implementation/index/QueryRewriteIndex.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/spatial/SpatialIndexFindUtils.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/spatial/index/v2/STRtreeUtils.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/spatial/index/v2/SpatialIndexLib.java
- jena-geosparql/src/main/java/org/apache/jena/geosparql/spatial/property_functions/GenericSpatialPropertyFunction.java
- jena-geosparql/src/test/java/org/apache/jena/geosparql/geo/topological/property_functions/simple_features/SfPFMiscSparqlTest.java
GitHub issue resolved #3473 
Pull request Description: In `jena-geosparql`, replaced all lookups of spatial objects by type with lookups by the corresponding relevant properties. E.g. instead of searching for instances of type `geo:Geometry`, instances with `geo:asWKT`, `geo:asGML` and `geo:hasSerialization` properties are looked for.
* Consolidated all vocabulary-based graph access into `AccessGeoSPARQL` and `AccessWGS84` classes.
* Added benchmark. No performance issues revealed. Detailed results in this thread.
* Spatial Indexer UI: Replace mode with no selected graphs clears the index
* Added `computeIfAbsent/Present` methods to `Context`.
* Fixed missing override of `DatasetGraphRDFS.find()`
* Fixed possible resource leaks by changing `forEachRemaining` to `forEach` which closes the …
> GH-3473: Identify spatial objects by properties instead of types.
